### ISSUE TITLE
App Theme (Ver 0.14.0-beta.3)

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#1907] opened 2022-07-29 11:48 UTC
### Describe the bug

App theme stay on Default (Blue) even when changing to Emerald or Muted Purple. Used to work in Ver 0.13. Know its not a big thing, just saying.

Accessed the app, changed theme to Emerald, all stayed Blue. Force stopped the app and reload, still Blue.

### Application version

0.14.0 Beta 3

### Where did you install the app from?

Google Play

### Device information

Sky Worth Android TV

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment] 2022-07-29 19:10
Unable to reproduce, changing the theme in the preferences updates the theme immediately when closing the preferences overlay. (tested by going from Muted Purple -> Emerald).

**Comment by sourpatched** [comment] 2022-07-30 10:30
As @nielsvanvelzen Said, theme will change once you go back to the home page after selecting theme.
Tested it myself and no issue on beta2

**Comment by ShakeSp33r** [comment] 2022-07-30 12:03
I deleted all cash on the 2 devices I have (Skyworth Android TV & Xiaomi Stick). Both started with the default theme, and then changed it to Emerald, yet everything still show as the default blue even when closing app and go back in.

**Comment by chr-zz** [comment] 2022-07-31 10:55
Same problem here. I always use the emerald theme.
The default skin remains and everything is blue, even after reloading the app.
Beta1-3 on Amazon Stick 2Gen.

**Comment by nielsvanvelzen** [comment] 2022-07-31 11:14
Since I can't reproduce the issue I'll need some logs from the app to see what's going wrong.

**Comment by chr-zz** [comment] 2022-07-31 13:35
I don't know if you can do anything with that. 
Unfortunately, I don't know how to create other logs.
Here i switch from standard to the other 2 themes and go to the start screen.

[logcat.log](https://github.com/jellyfin/jellyfin-androidtv/files/9228957/logcat.log)

**Comment by Fallenbagel** [comment] 2022-08-03 10:40
I'm having the same issue as well on version beta1-beta3+0.14.0 stable.

One thing I noticed is when I installed the android tv app to mobile, and changed theme it worked. But not on tv since beta1

**Comment by sourpatched** [comment] 2022-08-03 13:12
> I'm having the same issue as well on version beta1-beta3+0.14.0 stable.
> 
> One thing I noticed is when I installed the android tv app to mobile, and changed theme it worked. But not on tv since beta1

@Fallenbagel What OS and device are you using?

@chr-zz @Fallenbagel **have you gone into Android Menu to apps, force close Jellyfin and press clear cache, Open the app and try again. ** (Pressing on clean data will remove all settings and you'll have to set everything back up again)

**Comment by Fallenbagel** [comment] 2022-08-03 13:15
> @Fallenbagel What OS and device are you using?
> 
> @chr-zz @Fallenbagel **have you gone into Android Menu to apps, force close Jellyfin and press clear cache, Open the app and try again. ** (Pressing on clean data will remove all settings and you'll have to set everything back up again)

1. I'm on arch with official docker image (so debian 11) and a generic android set box. In v0.13.7 and below themes worked.

2. Yes. Yes I have done all that and even cleared data to set up once again and also uninstalled reinstalled. Didn't change 😔

**Comment by sourpatched** [comment] 2022-08-03 13:30
> > @Fallenbagel What OS and device are you using?
> > @chr-zz @Fallenbagel **have you gone into Android Menu to apps, force close Jellyfin and press clear cache, Open the app and try again. ** (Pressing on clean data will remove all settings and you'll have to set everything back up again)
> 
>     1. I'm on arch with official docker image (so debian 11) and a generic android set box. In v0.13.7 and below themes worked.
> 
>     2. Yes. Yes I have done all that and even cleared data to set up once again and also uninstalled reinstalled. Didn't change 😔
> 
> 
> Thinking of setting up adb to try and see debug the issue

Any crash reports go directly to Jellyfin Server as of 0.14.0.

What Android is the box running?

**Comment by Fallenbagel** [comment] 2022-08-03 13:31
> Any crash reports go directly to Jellyfin Server as of 0.14.0.

Yeah ik but it's not crashing so 🤔 just theme not changing.

> What Android is the box running?

Android 9

**Comment by chr-zz** [comment] 2022-08-03 19:49
> @chr-zz @Fallenbagel have you gone into Android Menu to apps, force close Jellyfin and press clear cache, Open the app and try again. (Pressing on clean data will remove all settings and you'll have to set everything back up again)

everything done, no change

> I'm having the same issue as well on version beta1-beta3+0.14.0 stable.

oh funny 0.14 is out, then I have to try it out.

> What Android is the box running?

no idea, amazon fire tv stick gen2 where i installed via adb

I have an Amazon Fire TV Stick 4k MAX.
but I let the original update come from 0.13.7 to 0.14
can only be a matter of weeks at amazon :) :) then I can also say something about that

I will now install the 0.14 stable on the gen2

**Comment by Fallenbagel** [comment] 2022-08-06 18:23
> same problem with the stable 0.14. let's see what the official update on amazon does in the next few days. on the other stick

I tried stable 0.14 from google play. Theme never changes unfortunately v.v
Seems like the issue started since the kotlin sdk change because I did manually build the debug from master about 2 or so months ago to test some PRs and even then the theme did not work. Theme worked on 0.13.x tho

**Comment by nielsvanvelzen** [comment] 2022-08-11 20:04
I've made a possible fix with #1959. Can someone test if this fixes the issue for them? You can download the APK from the link below and sideload it to your device.

https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2842456378
(click on "Build artifacts" to download the zip with the apk file)

**Comment by chr-zz** [comment] 2022-08-11 22:28
> I've made a possible fix with https://github.com/jellyfin/jellyfin-androidtv/pull/1959. Can someone test if this fixes the issue for them? You can download the APK from the link below and sideload it to your device.

> https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2842456378
(click on "Build artifacts" to download the zip with the apk file)

does not work for me.

**Comment by Fallenbagel** [comment] 2022-08-12 00:06
> I've made a possible fix with #1959. Can someone test if this fixes the issue for them? You can download the APK from the link below and sideload it to your device.
> 
> https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2842456378 (click on "Build artifacts" to download the zip with the apk file)

Unfortunately did not work on mine either. Tried clearing cache, force stopping and everything but no luck

**Comment by nielsvanvelzen** [comment] 2022-08-13 08:03
I believe I know found the culprit and fixed it. I was able to reproduce the issue on an Android 9 emulator and it worked with my fix. Please try it again with this build: https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2851249558

**Comment by ShakeSp33r** [comment] 2022-08-13 13:41
> I believe I found the culprit and fixed it. I was able to reproduce the issue on an Android 9 emulator and it worked with my fix. Please try it again with this build: https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2851249558

It's working.  Thanis

**Comment by chr-zz** [comment] 2022-08-13 20:07
> I believe I found the culprit and fixed it. I was able to reproduce the issue on an Android 9 emulator and it worked with my fix. Please try it again with this build: https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2851249558

it's working :)

**Comment by Fallenbagel** [comment] 2022-08-13 20:54
> I believe I found the culprit and fixed it. I was able to reproduce the issue on an Android 9 emulator and it worked with my fix. Please try it again with this build: https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2851249558

Works as well c:

**Comment by nielsvanvelzen** [comment] 2022-08-14 07:29
Ok thanks for testing all. The fix will be in the next bugfix release.

**Closed** 2022-08-14 13:48 UTC
Labels: bug
