### ISSUE TITLE
(0.15.0-beta.1) Themes not working

### ISSUE THREAD

**Issue by darinmanica** [jellyfin/jellyfin-androidtv#2261] opened 2022-11-15 01:32 UTC
### Describe the bug

Theme settings are saved in the menu, but not used by the app.  (It always uses the "Dark (Default)" theme instead.)

### Steps to reproduce

1. Open Jellyfin AndroidTV
2. Go to "Settings → Customization → App theme"
3. Select either "Classic Emerald" or "Muted Purple"
4. Go back and fully close the app
5. Reopen Jellyfin AndroidTV
6. Notice the selected theme is not used.  It uses "Dark (Default)" instead.

No crash log for this one.  Sorry.  I noticed that the selected theme (Classic Emerald in my case) is still selected in the settings, but not being used by the app.  Occasionally it appears to flash the theme during the splash screen, but is always gone when the splash screen disappears.

### Application version

0.15.0-beta.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield (2019)

### Android version

Android 11

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment] 2022-11-15 09:52
Did this also happen in previous versions of the app for you? Does the theme work when you restart the app?

**Comment by nielsvanvelzen** [comment] 2022-11-15 20:22
I'm unable to reproduce this issue. When I change the theme it applies immediately after closing the settings and it persists after restarting the app. Tried with all themes (dark, emerald, muted purple).

**Comment by darinmanica** [comment] 2022-11-16 04:05
The problem started when I upgraded to 0.15.0-beta1.  (It was not a problem in the 0.14.5 version.)  I'll do some experimenting to see if I can see why.  If there is a log or debug info that would be helpful, just let me know.  Thx!

**Comment by VampiricAlien** [comment] 2022-11-16 05:02
Purple and blue theme working for me

**Comment by satstarter** [comment] 2022-11-17 11:44
Dont know if its normal or not but the background stays black when changing theme to purple or smaragd
on my android tv boxes.
on the windows 11 jellyfin app the background chanches
boxes are formuler z8 and qxsarius q8

**Comment by VampiricAlien** [comment] 2022-11-17 14:05
> on the windows 11 jellyfin app the background chanches boxes are formuler z8 and qxsarius q8

Android 11?

**Comment by satstarter** [comment] 2022-11-17 15:59
> > on the windows 11 jellyfin app the background chanches boxes are formuler z8 and qxsarius q8
> 
> Android 11?

no windows 11 on pc

**Comment by nielsvanvelzen** [comment] 2022-11-17 16:52
This is the repository for the Android TV app. Not the Windows app.

**Comment by satstarter** [comment] 2022-11-17 18:38
> This is the repository for the Android TV app. Not the Windows app.

Yes i know maybe i didn't explaind right or you dont understand the background on my tv boxes stays black after theme change to muted purple or classic smaragd (dont know if this is normal) but on my windows 11 pc the background chanches
so because the background changes in the app for windows if i change theme there i thought it would be the same in
the android tv app but there the background stays black

**Closed** 2022-11-25 10:54 UTC
Labels: bug
