### ISSUE TITLE
UI glitch

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-androidtv#2937] opened 2023-08-01 23:27 UTC
### Describe the bug

There's a little glitch in the UI when trying to play a trailer.

- Open the page for a movie.
- You get Play | Version | Watched | Other Options. Select Other Options.
- Play Trailer(s).
- You get Open with WebView Shell. Below this there might be other options like Youtube.
- The dialog box is too far down. It's bottom is off screen. "Just once" etc. are not visible.

Is it possible to move this dialog further up?

### Application version

Latest release

### Where did you install the app from?

Google Play

### Device information

TCL Android TV

### Android version

No idea

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2023-08-02 07:15
The dialog to choose the app is actually not from the app. It's the Android system showing it. I guess the text is not visible because you have [overscan](https://en.wikipedia.org/wiki/Overscan). You should be able to disable that behavior in the device settings to fix the issue.

**Comment by ThomasPGH** [comment] 2023-08-02 19:01
Thanks for the reply.
Although the TV has this Overscan option it has been off. There's also an Auto format option. Both settings on or off in any combination don't seem to make a difference.
Look like I got to live with it ;)

**Comment by nielsvanvelzen** [comment] 2023-08-02 19:37
I'll close the issue since it's not caused by the app. I'm quite sure you should be able to fix the overscan issue but I can't really help with that as each device implements it differently.

**Closed by nielsvanvelzen** 2023-08-02 19:37 UTC
Labels: bug
