### ISSUE TITLE
Unnecessary transcoding

### ISSUE THREAD

**Issue by elmuz** [jellyfin/jellyfin-androidtv#1523] opened 2022-03-13 14:28 UTC
### Describe the bug

Setup:
Android-based media center (Chinese brand from Amazon), connected via HDMI to the TV. The media center has the Jellyfin client installed.
- The media center is capable of direct-playing this movie.
- TV cannot handle TrueHD audio (resulting in smooth video, audio not present).
- Asking the Jellyfin client for "stereo" instead of passing-through, makes the server fully-transcoding the movie instead of copying video track and encoding audio only.

I know this is a topic that sometimes pops up, but I cannot find a reasonable debugging process for this. I can't understand if it's the client that sends wrong info to the server or if it is the server that misunderstands client requests and opts for transcoding even when it's not necessary.

### Logs
I cannot sniff client logs but here's some interesting elements I find from the server:
```
[2022-03-13 00:39:44.190 +01:00] [INF] [71] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "120", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2022-03-13 00:39:44.198 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "funkysloth". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-03-13 00:39:44.198 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "~~~HIDDEN~~~", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-03-13 00:39:44.198 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "~~~HIDDEN~~~" with codec "hevc"
[2022-03-13 00:39:44.202 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 40000000, RemoteIp: "~~~HIDDEN~~~", IsInLocalNetwork: True
[2022-03-13 00:39:44.202 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "~~~HIDDEN~~~", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-03-13 00:39:44.202 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "~~~HIDDEN~~~" with codec "hevc"
[2022-03-13 00:39:44.206 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 40000000, RemoteIp: "~~~HIDDEN~~~", IsInLocalNetwork: True
[2022-03-13 00:39:44.206 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "~~~HIDDEN~~~", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-03-13 00:39:44.206 +01:00] [INF] [71] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", No video direct play profiles found for "~~~HIDDEN~~~" with codec "hevc"
[2022-03-13 00:39:44.670 +01:00] [INF] [37] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2022-03-13 00:39:44.672 +01:00] [INF] [37] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device qsv=hw -filter_hw_device hw -i file:"~~~HIDDEN~~~" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset faster -look_ahead 0 -b:v 28552800 -maxrate 28552800 -bufsize 57105600 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -vf "vpp_qsv=format=nv12" -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/17395876fd6cac50df6cfafdec7841ae%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/17395876fd6cac50df6cfafdec7841ae.m3u8"
```

### FFmpeg logs
FFmpeg does its job, no complains here.

### Media info of the file

```
Input #0, matroska,webm, from '/data/movies/~~~HIDDEN~~~':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-07-09T06:52:32.000000Z
  Duration: 02:13:46.78, start: 0.000000, bitrate: 17131 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 16360260
      DURATION        : 02:13:46.769000000
      NUMBER_OF_FRAMES: 192450
      NUMBER_OF_BYTES : 16415004287
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s
    Metadata:
      title           : English
      BPS             : 768000
      DURATION        : 02:13:46.784000000
      NUMBER_OF_FRAMES: 250837
      NUMBER_OF_BYTES : 770571264
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(spa): Subtitle: subrip
    Metadata:
      title           : Spanish
      BPS             : 40
      DURATION        : 02:12:22.985000000
      NUMBER_OF_FRAMES: 1301
      NUMBER_OF_BYTES : 40373
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(fre): Subtitle: subrip
    Metadata:
      title           : French Canadian
      BPS             : 43
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 1319
      NUMBER_OF_BYTES : 43678
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(ger): Subtitle: subrip
    Metadata:
      title           : German
      BPS             : 35
      DURATION        : 02:12:01.505000000
      NUMBER_OF_FRAMES: 1204
      NUMBER_OF_BYTES : 35621
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(nor): Subtitle: subrip
    Metadata:
      title           : Norwegian
      BPS             : 34
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 1299
      NUMBER_OF_BYTES : 34572
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(dut): Subtitle: subrip
    Metadata:
      title           : Dutch
      BPS             : 35
      DURATION        : 02:12:30.859000000
      NUMBER_OF_FRAMES: 1114
      NUMBER_OF_BYTES : 35756
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(por): Subtitle: subrip
    Metadata:
      title           : Brazilian Portuguese
      BPS             : 39
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 1297
      NUMBER_OF_BYTES : 39375
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(fre): Subtitle: subrip
    Metadata:
      title           : French
      BPS             : 33
      DURATION        : 02:12:01.505000000
      NUMBER_OF_FRAMES: 1256
      NUMBER_OF_BYTES : 33216
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(spa): Subtitle: subrip
    Metadata:
      title           : European Spanish
      BPS             : 36
      DURATION        : 02:12:22.985000000
      NUMBER_OF_FRAMES: 1277
      NUMBER_OF_BYTES : 35886
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10(jpn): Subtitle: subrip
    Metadata:
      title           : Japanese
      BPS             : 32
      DURATION        : 02:12:41.954000000
      NUMBER_OF_FRAMES: 1257
      NUMBER_OF_BYTES : 32388
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:11(swe): Subtitle: subrip
    Metadata:
      title           : Swedish
      BPS             : 35
      DURATION        : 02:12:31.911000000
      NUMBER_OF_FRAMES: 1080
      NUMBER_OF_BYTES : 35644
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:12(dan): Subtitle: subrip
    Metadata:
      title           : Danish
      BPS             : 33
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 923
      NUMBER_OF_BYTES : 33222
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:13(por): Subtitle: subrip
    Metadata:
      title           : Portuguese
      BPS             : 38
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 1273
      NUMBER_OF_BYTES : 38552
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:14(ita): Subtitle: subrip
    Metadata:
      title           : Italian
      BPS             : 40
      DURATION        : 02:12:31.952000000
      NUMBER_OF_FRAMES: 1278
      NUMBER_OF_BYTES : 40041
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:15(fin): Subtitle: subrip
    Metadata:
      title           : Finnish
      BPS             : 39
      DURATION        : 02:12:31.944000000
      NUMBER_OF_FRAMES: 1300
      NUMBER_OF_BYTES : 39180
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:16(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS             : 39
      DURATION        : 02:12:22.985000000
      NUMBER_OF_FRAMES: 1306
      NUMBER_OF_BYTES : 39685
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:17(eng): Subtitle: subrip
    Metadata:
      title           : English [SDH]
      BPS             : 46
      DURATION        : 02:13:27.466000000
      NUMBER_OF_FRAMES: 1630
      NUMBER_OF_BYTES : 46838
      _STATISTICS_WRITING_APP: mkvmerge v58.0.0 ('Supper's Ready') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-09 06:52:32
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

### Application version

0.13.0-beta.4

### Device information

X8TMAX

### Android version

Android 6

### Jellyfin server version

10.7.7 via ghcr.io/hotio/jellyfin:latest

**Comment by mueslimak3r** [comment] 2022-03-13 14:53
closing this as a duplicate of #1275 

I've looked into this a little bit in the past. It seems that there is an issue with how the client capabilities (the "device profile") is communicated to the server.

The three types of playback are Transcoding (full conversion), Direct Play (no conversion), and Direct Stream (partial conversion). afaik the issue is that the ability to direct stream (only convert audio in this case) isn't being communicated properly.

If you're interested in looking into this, I good place to start might be comparing the code between this app and some other clients for creating and sending the device profile.

**Closed by mueslimak3r** 2022-03-13 14:53 UTC
Labels: bug, playback

**Comment by mueslimak3r** [comment] 2022-03-13 15:01
Here's where the profile are defined for this app. It's then sent to the server in JSON format. In the server logs you can see the json and compare clients.

https://github.com/jellyfin/jellyfin-androidtv/tree/master/app/src/main/java/org/jellyfin/androidtv/util/profile
