### ISSUE TITLE
Consistent Error downloading subtitles

### ISSUE THREAD

**Issue by KyleSanderson** [jellyfin/jellyfin-androidtv#1704] opened 2022-05-07 21:25 UTC
### Describe the bug

1. Play media
2. Turn on Subtitles that are embedded in the MKV
3. Error downloading subtitles
4. ???
5. Turn on same subtitle again
6. Sometimes loads?

This is a direct play - no transcoding.

### Logs

```shell
05-07 14:08:48.056 21977 21977 D PlaybackController: Setting subtitle index to: 3
05-07 14:08:48.058 21977 21977 D jellyfin-apiclient: Adding request to queue: http://*:8096/Videos/f7b6defbf3512adbec/f7b6defbf3512adbec/Subtitles/3/0/Stream.JSON?format=json
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: VolleyError com.android.volley.TimeoutError: null
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: com.android.volley.TimeoutError
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:162)
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
05-07 14:09:18.063 21977 21977 E jellyfin-apiclient: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
05-07 14:09:18.064 21977 21977 E PlaybackController: Error downloading subtitles
05-07 14:09:18.064 21977 21977 E PlaybackController: org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.TimeoutError: 
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at org.jellyfin.apiclient.interaction.VolleyErrorListener.onErrorResponse(VolleyErrorListener.java:25)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.Request.deliverError(Request.java:648)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at android.os.Handler.handleCallback(Handler.java:873)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at android.os.Looper.loop(Looper.java:193)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at android.app.ActivityThread.main(ActivityThread.java:6740)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-07 14:09:18.064 21977 21977 E PlaybackController: Caused by: com.android.volley.TimeoutError
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:162)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
05-07 14:09:18.064 21977 21977 E PlaybackController: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

### Application version

0.13.4

### Where did you install the app from?

Amazon Appstore

### Device information

AMZN Firestick Max

### Android version

retail

### Jellyfin server version

retail

**Comment by nielsvanvelzen** [comment] 2022-05-08 08:13
Duplicate of #145

**Closed by nielsvanvelzen** 2022-05-08 08:13 UTC
Labels: bug, playback
