### ISSUE TITLE
Latest TV Shows - Mixed Views

### ISSUE THREAD

**Issue by MRobi1** [jellyfin/jellyfin-androidtv#1294] opened 2021-12-17 21:56 UTC
### Describe the bug

Testing out Jellyfin again to see if it's a viable replacement for Emby.

Loaded up the Android TV app. In the "Latest TV Shows" view, I'm getting a mix of episode thumbnails, series/movie posters, and series/movie thumbnails. 

Looking at my screen right now I see:
Shrink Next Door: Episode thumbnail
The Witcher: Series poster
Dickinson: Episode thumbnail
Big Sky: Series thumbnail
Million Dollar Listing: Episode thumbnail
Grand Tour: Series thumbnail
Dragon's Den: Series poster

The same list on the webapp is all series posters which is what I would prefer.

I've browsed the settings and can't find one to replicate what I see on the webapp. The only one I can see that would be even slightly related is "Prefer series thumbnails" which seems to only affect the Next Up column.

Am I missing something or is this expected behavior?

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by MRobi1** [comment] 2021-12-17 22:06
WebApp
![image](https://user-images.githubusercontent.com/34860474/146613279-fd4a6786-21ac-4cbd-b8c8-24e150048ac0.png)

TvApp
![20211217_180245 (2)](https://user-images.githubusercontent.com/34860474/146613388-ff1c7c8f-ea2e-4e19-89e8-44c4dfb054b3.jpg)

**Comment by cebo55** [comment] 2022-04-01 20:44
I'm getting this too.  

It seems if there is only 1 episode I get a thumbnail, but if there are two or more then it's a poster.  

Not the end of the world - but it doesn't look right.

**Comment by tomaswl1** [comment] 2022-04-02 12:06
Same its abit annoying

**Comment by MRobi1** [comment] 2022-06-06 19:58
Just dropping in to say 0.13.6 still has the same issue. 
The homescreen looks great in the webapp, but android tv where 99% of the viewing is done still looks terrible. When people speak of Jellyfin looking "unpolished" compared to the competition, this is exactly the type of thing they speak of.

**Comment by MRobi1** [comment] 2022-08-03 18:52
Still an issue on 0.14.0-beta.3.

Web App
![Capture1](https://user-images.githubusercontent.com/34860474/182686526-c33d2b02-ca6e-4fe4-bb8b-0ca61deeb210.PNG)

Jellyfin Android TV App
![Jellyfin_20220803_154501](https://user-images.githubusercontent.com/34860474/182686604-32741aed-f732-4a91-af85-86c576df4be9.png)

It was suggested this may be because of "Single Episodes" however, every single show that's displaying thumbnails instead of posters has multiple unwatched episodes.

**Comment by MRobi1** [comment] 2022-08-03 19:00
@thornbill @nielsvanvelzen Can you please explain how this random mixture of posters and thumbnails that differs from the jellyfin webapp is a planned feature for android and not a bug? Genuinely curious on the mindset behind this design implementation.

**Comment by MRobi1** [comment] 2022-08-11 22:03
I should also add that I have multiple libraries tagged as "shows", this only occurs on the main tv series library and not any of the other ones I have such as "kids tv" or "french tv"

**Comment by MRobi1** [comment] 2023-01-24 16:59
Android TV app version 0.15.2
Server version 10.8.9

Still seeing this bug.

![Jellyfin_20230124_125403](https://user-images.githubusercontent.com/34860474/214357962-470866ae-dd38-4dbd-9325-dee5c4a3bf60.png)

**Comment by d03j** [comment] 2023-02-26 11:47
I have the same issue and agree: if this issue is an enhancement, does it mean the web app's behaviour is a bug or is there a rationale for having different UX?

**Comment by d8f6** [comment] 2023-02-27 00:13
> I have the same issue and agree: if this issue is an enhancement, does it mean the web app's behaviour is a bug or is there a rationale for having different UX?

After doing some more testing, the behavior is inconsistent. Having one unwatched show sometimes shows a poster, and other times a thumbnail. It is due to this inconsistency (the feature not working as intended) that this issue is indeed a bug as opposed to an enhancement. I understand why the label was changed, but the change in this instance seems to have been a bit premature.

**Comment by d8f6** [comment] 2023-02-27 22:21
I am no longer seeing this issue on version 0.15.4. I am unsure if this is because I remove/add media so frequently that it is just different or if this issue has been fixed. MRobi1 and d03j can you confirm issue as solved on your end or is it just my library?

**Comment by MRobi1** [comment] 2023-02-27 22:35
Still present on 0.15.4 and can confirm it is not related to how many unwatched episodes of a show. It appears to be entirely at random and only shows up on Android TV and only on my latest tv shows. Latest movies, latest kids tv, latest kids movies, latest stand-up, etc.. etc... are all entirely posters and mimic every other Jellyfin UI on every other platform. 

I am certain this is a bug, and the lack of response or acknowledgement from the devs on this for over a year now is exactly why I have recommended Emby over Jellyfin in every since VS post I've seen online, which has been many. I'd love to give Jellyfin a fair try, but with such basic UI issues going unresolved for so long it shows it is not ready for everyday use just yet. Can't wait for the day it gets there.

**Comment by nielsvanvelzen** [comment] 2023-02-28 07:47
I've explained this in multiple issues already but I guess you didn't find it; this is "intentional" behavior as in, this is how it was programmed to work years ago before Jellyfin existed. The code that chooses which image type to display is a mess and I don't touch it, if someone were to make a PR to fix the behavior I'd accept it. I'm too busy myself with all the other 200+ issues, mainly related to playback right now. This issue is still not a bug though.

**Comment by MRobi1** [comment] 2023-02-28 11:35
@nielsvanvelzen saying "it's intended so it's not a bug" and then not answering any questions as to why it's intended this way and what logic is used to select whether a poster or thumbnail is used doesn't give any clarity on the issue at all. The only possible explanation given was that it's based on if there is 1 episode unwatched or multiple. However I, as well as others, have seen both views presented regardless ofnunwatched count. So if that is the logic, it does not work properly and is indeed a bug. If the logic is to just pick a view completely at random and present it in a jumbled mess but only with 1 of several libraries, then you are correct, it's working like a charm! Although I never had this "feature" throughout the many years of using it pre-fork so I assume there must be some sort of logic behind picking which image is displayed. 

Regardless of whether the Devs feel it's a feature request or a bug, as a user it's not expected behavior and does not match the look and feel of jellyfin on any other platform.

**Comment by anthonylavado** [comment] 2023-02-28 12:19
> not answering any questions as to why it's intended this way

(from earlier, emphasis mine)
> how it was programmed to work years ago **before** Jellyfin existed

**Comment by anthonylavado** [comment] 2023-02-28 12:23
>not answering any questions as to why it's intended this way

(from earlier, emphasis mine)
>how it was programmed to work years ago **before** Jellyfin existed

**Comment by MRobi1** [comment] 2023-02-28 12:26
> > not answering any questions as to why it's intended this way
> 
> (from earlier, emphasis mine)
> 
> > how it was programmed to work years ago **before** Jellyfin existed

And also from earlier, emphasis mine

> Although I never had this "feature" throughout the many years of using it pre-fork

Your response did not explain how an image type was selected with the current code. Maybe an explanation of what criteria is used to select an image can help the rest of us understand if this "feature" is indeed functioning as it should.

**Comment by thornbill** [comment] 2023-02-28 13:02
No one here owes you anything, including an explanation.

**Comment by MRobi1** [comment] 2023-02-28 13:59
> No one here owes you anything, including an explanation.

A simple "I'm not really sure how it's supposed to work but I'll look into it" would have sufficed.

This type of "holier than thou" attitude from a dev is exactly how a project gets a bad reputation which deters potential users and future Devs from contributing. Why would a user report a bug in an attempt to help the project if this is the type of response they're going to get?

If you can say "it's working as expected" but can not explain to us how it's expected to work so we can agree with you that it is indeed working as expected, then we will have no choice but to continue to push back that this must be a bug as it is not expected behavior to us.

**Comment by d8f6** [comment] 2023-02-28 19:03
> I've explained this in multiple issues already but I guess you didn't find it; this is "intentional" behavior as in, this is how it was programmed to work years ago before Jellyfin existed. The code that chooses which image type to display is a mess and I don't touch it, if someone were to make a PR to fix the behavior I'd accept it. I'm too busy myself with all the other 200+ issues, mainly related to playback right now. This issue is still not a bug though.

I think I understand now. I am new to jellyfin and this client application so I do not really know all the history here. This client appplication was originally a fork of another appplication and the entire section of this codebase will eventually have to be rewritten anyways so fixing it now would be a waste of time/resources? So, this is not a bug because it is not new code? If this is the case, then this isn't a bug and I was wrong in my initial assumption. More of a wontfix/wait for the new ui code type of scenario. I will update my other (duplicate issue) post to reflect this in case someone comes across this issue while searching assuming my understanding of the issue here is now correct. Is what I am saying correct? This client application was originally a fork of another application? 



> Still present on 0.15.4 and can confirm it is not related to how many unwatched episodes of a show. It appears to be entirely at random and only shows up on Android TV and only on my latest tv shows. Latest movies, latest kids tv, latest kids movies, latest stand-up, etc.. etc... are all entirely posters and mimic every other Jellyfin UI on every other platform.
> 
> I am certain this is a bug, and the lack of response or acknowledgement from the devs on this for over a year now is exactly why I have recommended Emby over Jellyfin in every since VS post I've seen online, which has been many. I'd love to give Jellyfin a fair try, but with such basic UI issues going unresolved for so long it shows it is not ready for everyday use just yet. Can't wait for the day it gets there.

I do not use jellyfin due to feature parity or comparitive functionality. I use it because it is GPL. So, I disagree with both your sentiment and ideological perspective (recommending emby/plex/etc...). My perspective is that all proprietary software is malware, so I would not recommend it to anyone anyway.  Even if development on this client stopped right now, I would still use it for this reason indefinitely.

**Comment by MRobi1** [comment] 2023-02-28 20:59
> I think I understand now. I am new to jellyfin and this client application so I do not really know all the history here. This client appplication was originally a fork of another appplication and the entire section of this codebase will eventually have to be rewritten anyways so fixing it now would be a waste of time/resources? 

Correct. Jellyfin is a fork of Emby and it's "starting point" is the final version of Emby before they switched from an open to closed source model. Emby was first released as Media Browser (hence M.B) roughly 15 years ago with Jellyfin forking off from it a little over 4 years ago now in late 2018. I personally first started using Emby roughly around the start of 2014. Initially using Kodi as a player but then moved to the Android-TV based app in early 2017. When the Jellyfin server was initially released, users could still use the Emby app connecting to a Jellyfin back-end. But as the 2 projects headed off on different paths, the Jellyfin Android-TV app was launched in July of 2019. Now whether this was forked off of the late 2018 version of the app or the July 2019 version, I honestly do not know. 

What I can say with certainty is that from the day I started using the Android-TV Emby app in early 2017, there has never been a mismatch of posters and thumbnails at random in the Latest TV section only of the app. I used the app. I beta tested the app. I beta tested the server. To simply respond with "It's functioning as it should because that's how the code from Emby was" sounds extremely off-putting to me. If that's how it was designed to function, I definitely would have seen it.

With 6+ years of using and testing both the server and the app, I feel as though I have a grasp on what is expected behavior and what isn't. But I'm being told what I'm expecting based on what I have used during those 6+ years is not how it was ever designed to be. (Do you see how that can be off-putting?) We all know when driving a car, you press the brakes to stop. What if one day those brakes failed and the mechanic told you that brakes were never designed to stop your car in the first place and not being able to stop was completely normal. Would you continue to drive the car and recommend that mechanic to others? Or would you take it somewhere else and get the brakes fixed? I can appreciate one's perspective behind open source projects over proprietary software. This is why I keep coming back to see if it's made it to a usable state. But I'm not one to sacrifice core functions to support the cause. I'm not going to be the one telling everyone to go drive that car with no brakes because my mechanic told me it's ok.

A simple explanation of how it's designed to work and what criteria are used to select which image is displayed clears this whole thing up. But I'm just a lowly user so I don't overly expect it after this has been open for more than a year now.

**Comment by d8f6** [comment] 2023-02-28 23:56
@MRobi1: Well, one or two unpaid volunteer developers rewriting/refactoring over 10,000 lines of code in their spare time may take a while. Perhaps the reason that a simple explanation hasn't been given is because it is not entirely known? Also, playback being a current development priority for an application that is a media player seems relatively logical to me. I'm sure this issue will get fixed in time as the code is rewritten, but it may be quite a while still without more volunteers and/or some type of funding/hiring programmers. I'm just going to be patient and help out if I can since my java is too weak to help directly with the code. I looked into this issue myself, but I could not figure it out (I would probably just end up breaking something anyway haha). Thanks for answering my fork question. It clears things up for me completely. I'm going to unsubscribe from this thread now. Okay, take care.

**Comment by thornbill** [comment] 2023-05-26 13:28
No one is saying this won't be changed at some point. The whole thing about what classifies as a bug versus an enhancement comes down to if the code is doing what it is expected to do as it is currently written. In this case it does so changing this behavior would be an enhancement. Arguing about that is mostly pointless because it doesn't really affect much beyond how we track things here on GitHub and which release a change ends up going in.

As far as whether it could be added as an option, I'm sure it could but I don't think anyone is disagreeing that this should be changed at some point.

**Comment by MRobi1** [comment] 2023-05-26 13:40
>The whole thing about what classifies as a bug versus an enhancement comes down to if the code is doing what it is expected to do as it is currently written. In this case it does so changing this behavior would be an enhancement. 

I think the big issue is that in the 17 months that this has been open, not 1 single person has been able to say how it's expected to work! All we get is "It's not a bug because we say so" and "no one owes you an explanation". 

Give us some sort of understanding on what logic the app uses to select whether it should display a poster or a thumbnail so that the rest of us can see that it's an enhancement and not actually a bug and people will stop pushing back on you. For you to be able to say the code is doing what is expected, then you clearly know how it is expected to work. So why not just put an end to this whole debate and share some of that insight?

**Comment by thornbill** [comment] 2023-05-26 15:48
It happens when only a single episode of a show is returned in the latest items query which could happen for any number of reasons (too many new items for all to be listed, one new episode in an existing show, etc.).

**Comment by MRobi1** [comment] 2023-05-26 16:31
OK, so that does kind of follow along with the "only 1 unwatched episode" theory from above. If it's deciding based on the latest items query, it's obviously querying the server for that data.

Now if we take a look at some of the screenshots from above...
> WebApp ![image](https://user-images.githubusercontent.com/34860474/146613279-fd4a6786-21ac-4cbd-b8c8-24e150048ac0.png)
> Web App: ![Capture1](https://user-images.githubusercontent.com/34860474/182686526-c33d2b02-ca6e-4fe4-bb8b-0ca61deeb210.PNG)
Looking here, The Witcher and Reservoir Dogs shows 20XX-Present while the rest are showing an individual episode. We also saw above, at least for the Egypt show, there were multiple unwatched episodes. 

And if we compare that to the Android TV App
> Jellyfin Android TV App: ![Jellyfin_20220803_154501](https://user-images.githubusercontent.com/34860474/182686604-32741aed-f732-4a91-af85-86c576df4be9.png)
> TvApp ![20211217_180245 (2)](https://user-images.githubusercontent.com/34860474/146613388-ff1c7c8f-ea2e-4e19-89e8-44c4dfb054b3.jpg)
All of the ones where the server shows an individual episode on the bottom, the Android TV App shows a thumbnail EXCEPT for Motherland and What We Do In The Shadows.

Thinking of that Egypt show, with multiple unwatched episodes I would almost expect to see something like The Witcher and 20XX - Present. If the server only sees 1 episode as latest and that's what it sends to the app, then the app would indeed be working as expected. Although I don't have any theories on Motherland and WWDITS. So could this mean there is a bug on the server side?

**Comment by thornbill** [comment] 2023-05-26 16:55
Check server logs for the api request or fire up Android Studio and attach a debugger is my recommendation.

**Comment by sevenrats** [comment] 2023-09-20 17:50
i think the mixed posters look great.

**Comment by nielsvanvelzen** [comment] 2023-09-20 18:45
Should be fixed in the next beta when the "prefer series posters" customization is enabled.

**Closed by nielsvanvelzen** 2023-09-20 18:45 UTC
Labels: enhancement
