### ISSUE TITLE
Next episode is miscalculated in season with a double episode

### ISSUE THREAD

**Issue by TheHYPO35** [jellyfin/jellyfin-androidtv#3954] opened 2024-08-31 08:59 UTC
### Describe the bug

This applies to a show like Star Trek TNG (and other Star Treks) that premiered with a 2 hour “feature-length” episode. This was later cut into two regular episodes for re-airing. The single video file is marked as episodes “1-2”, and the next episode is “3”.

If you go to any episode page from that season, the “next episode” will skip one. e.g. s1e4 Shows s1e6 as next. Also, after watching s1e4, the series page will show episodes 5,7,8 as next, skipping 6. I don’t know why the two pages skip different episodes.

### Application version

0.17.4

### Where did you install the app from?

None

### Device information

Firestick AFTKA

### Android version

Unknown

### Jellyfin server version

10.9.10

**Comment by nielsvanvelzen** [comment] 2024-09-02 09:29
Closing as duplicate of #1297

**Closed by nielsvanvelzen** 2024-09-02 09:29 UTC
Labels: bug
