### ISSUE TITLE
Home Section - My Media (small) not working

### ISSUE THREAD

**Issue by ktdt00** [jellyfin/jellyfin-androidtv#2093] opened 2022-09-24 17:01 UTC
### Describe the bug

When arranging home sections, for the first section I choose "My Media (Small)". I choose "None" for all other sections. 

Expected behavior is that the choices under "My Media" on the home page become "labeled buttons" rather than remaining large posters/images.  From what I can tell there is no difference between "My Media (small)" and "My Media"? The expected behavior is observed in the web UI as well as the Android app.

### Application version

0.14.3

### Where did you install the app from?

Amazon Appstore

### Device information

AFTV Stick 4K

### Android version

6.2.8.0

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment] 2022-09-24 17:34
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed by nielsvanvelzen** 2022-09-24 17:34 UTC
Labels: bug, duplicate

**Comment by ktdt00** [comment] 2022-09-24 19:32
That's kinda like an electrician putting a light switch in the middle of the living room wall that doesn't do anything. {Evil Laugh} - those pesky homeowners will never figure this thing out! :) :)
