### ISSUE TITLE
Live TV guide with multiple pages do not line up. 

### ISSUE THREAD

**Issue by junobomb** [jellyfin/jellyfin-androidtv#1543] opened 2022-03-21 19:17 UTC
### Describe the bug

Jellyfin client 0.13.0 on FireTV - Live TV guide information with multiple pages will no longer line up guide info with channel list due to next/previous page selection button being too large and getting channels out of alignment.    

See screenshot...

Guide was working previously on 0.12.0

### Application version

0.13.0

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireStick 4k Max

### Android version

7.2.5.5

### Jellyfin server version

10.7.7

![20220321_150626](https://user-images.githubusercontent.com/102076949/159348195-efcb5fae-e6cd-474d-be4f-6a0dbfbb6867.jpg)
![20220321_150612](https://user-images.githubusercontent.com/102076949/159348212-64c5ecc4-001b-41cf-9689-09e59de6fb38.jpg)

**Comment by junobomb** [comment] 2022-03-25 19:58
Just checked the Live TV guide on version 0.13.2 and its is still not lining up.  Next / Previous page selection bar is way too wide and causes channels to misalign.

**Comment by junobomb** [comment] 2022-03-31 13:19
Hi, any word on whether this will be addressed in a new release?

**Comment by mopeygoff** [comment] 2022-04-25 15:12
I am seeing the same thing on my fire tvs, dumb tvs with fire tv sticks, and my android sets. Came to report this, found this report.

**Comment by junobomb** [comment] 2022-04-25 17:01
> I am seeing the same thing on my fire tvs, dumb tvs with fire tv sticks, and my android sets. Came to report this, found this report.

**Comment by junobomb** [comment] 2022-04-25 17:03
@mopeygoff, yeah havent heard anything on it since 0.13.0 broke the guide alignment. 

@nielsvanvelzen is this on the fix radar anytime soon?

**Comment by nielsvanvelzen** [comment] 2022-04-25 17:08
I don't have Live TV setup on my server so I'm unable to reproduce the issue, and thus can't work on it. If someone is able to fix it we can release it in a patch release though.

(re-opened the issue as I suspect you closed it accidentally)

**Comment by junobomb** [comment] 2022-04-25 17:34
@nielsvanvelzen oops, yes that was totally by mistake, thanks for reopening.  

I guess, god willing ( and perhaps an engineer lol) will grace us with a fix sometime soon.  :-)

**Comment by junobomb** [comment] 2022-06-30 14:13
@nielsvanvelzen if you'd like I can give you access to my Jellyfin server with Live TV lineup so you can see the problem with the channel line up.

**Comment by junobomb** [comment] 2022-07-25 16:07
Just verified the guide alignment on 14 Beta 2 and although it is working under the normal live tv guide, the pop-up guide is still misaligned while viewing a channel. 
![20220725_113058](https://user-images.githubusercontent.com/102076949/180824303-9b8e0ae9-e613-48c2-826f-38b1bb5c7251.jpg)

**Closed** 2022-07-25 20:02 UTC
Labels: bug, confirmed, live-tv
