### ISSUE TITLE
Movie versions issue

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2686] opened 2023-04-20 15:34 UTC
### Describe the bug

I have multiple versions of movies in folders via the naming scheme below. I can select the version I want to play, but the client doesn't respect my choice and always plays the first video in the version list. 

├── Best Movie Ever (1999)
│   ├── Best Movie Ever (1999) - 1080P.mkv
│   ├── Best Movie Ever (1999) - 2160P Extended Cut.mkv

### Application version

0.15.6 debug

### Device information

Sony Bravia 4k VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.9

**Comment by mikewesten** [comment] 2023-04-22 12:08
Does it appear on the Jellyfin AndroidTV app in the following order?

├── Best Movie Ever (1999)
│ ├── Best Movie Ever (1999) - 2160P Extended Cut.mkv
│ ├── Best Movie Ever (1999) - 1080P.mkv

ie: the reverse order of they appear on the main web and desktop clients

That's the source of the conflict, I believe

The AndroidTV app prioritizes resolution over alphabetical naming, whereas the main clients respect alphabetical ordering and deprioritize resolution highest-to-lowest ordering.

**Comment by MichaelRUSF** [comment] 2023-04-23 18:15
I did some limited testing on the issue and it seems there is a bug with files labeled 1080p. 
For the test, I have four different tv shows (that way it is easier to tell if the correct version is playing) as labeled below. 

├── Best Movie Ever (2103)
│ ├── Best Movie Ever (2013) – 480p
│ ├── Best Movie Ever (2013) – 720p
│ ├── Best Movie Ever (2013) – 1080p
│ ├── Best Movie Ever (2013) – 2160p

Version 480p, 720p, 2160p plays correctly on the AndroidTV client. 
  
Only the 1080p version did not play the correct version. It plays the first one listed in the AndroidTV client, the 2160p version.

Everything plays as expected using the web client on a PC. 

I am aware that the server presents the movie versions in alphabetically order, with the exception being that named resolutions are sorted highest to lowest: 2160p, 1080p, 720p, 480p, 360p. 

Versions as listed by AndroidTV client:
![JFATVClient](https://user-images.githubusercontent.com/78215956/233857344-6724e402-14b4-4eec-affa-1a36a0039cc9.png)

Versions as listed by web client:  
![JFWebUI](https://user-images.githubusercontent.com/78215956/233857168-bcd36a3c-5c7b-442e-953a-f53453941e3d.png)

**Comment by mikewesten** [comment] 2023-04-23 21:20
I use brackets exclusively and I've come to realize my bracket naming (as per the documentation, which says it's okay to do) doesn't actually perform the expected behavior. My versions are all labeled [480p], [720p], [1080p], etc., which the server apparently treats as alphabetical labels instead of resolution tags.
On the sever they are ordered...
Movie (year) - [1080p]
Movie (year) - [480p]
Movie (year) - [720p]
On the AndroidTV client they are ordered...
Movie (year) - [1080p]
Movie (year) - [720p]
Movie (year) - [480p]

(provided the labels actually correctly match the video metadata)

If I rename them with [Source 1], [Source 2], [Source 3], appended to the front, the server will order them as...
Movie (year) - [Source 1] [1080p]
Movie (year) - [Source 2] [720p]
Movie (year) - [Source 3] [480p]
And the AndroidTV client will order them as...
Movie (year) - [Source 1] [1080p]
Movie (year) - [Source 2] [720p]
Movie (year) - [Source 3] [480p]

3 things going on here.
- The documentation is wrong ( https://jellyfin.org/docs/general/server/media/movies ), labels can NOT be placed between brackets with the "same result".
- The server and AndroidTV client have different ordering rules, the server respects alphabetical orders when provided them, whereas the AndroidTV client does not and will always default to the video resolutions per the video metadata (ignoring tags and their alphabetical order)
- 3rd thing - There's a possible trancoding issue involving 2160p videos, as noted by another Github user in another bug report. I have no experience with that since I don't have any 4k stuff in my Jellyfin library.

Your issue has some differences from the issue I'm experiencing. I'm using brackets, which evidently opens up a different can of worms. But ignoring that for the moment, your AndroidTV client is able to list 480p and 720p and 1080p in a seemingly alphabetical (and reverse low-to-high resolution) ordering. Mine cannot and will not do that, ever.

If I took a 480p video and falsely labeled it with a [720p] tag, and vice versa for a 720p video, falsely labeled with a [480p] tag. My server will order them as...
Movie (year) - [480p] [Says 480p but is actually 720p]
Movie (year) - [720p] [Says 720p but is actually 480p]
AndroidTV client will order as...
Movie (year) - [480p] [Says 480p but is actually 720p]
Movie (year) - [720p] [Says 720p but is actually 480p]

If I correctly label them,
my server will order them as...
Movie (year) - [480p] [Says 480p and actually is 480p]
Movie (year) - [720p] [Says 720p and actually is 720p]
AndroidTV client will order them as...
Movie (year) - [720p] [Says 720p and actually is 720p]
Movie (year) - [480p] [Says 480p and actually is 480p]

**Comment by MichaelRUSF** [comment] 2023-04-25 23:27
I just realized that the AndroidTV client doesn’t rely on filenames for sorting. In my prior test, the filenames did not match the resolutions, e.g., the 2160p file name was actually a 1080p file. That’s why the ordering was different on the AndroidTV client. I reran the test with files that actually match the resolutions and the ordering occurred from highest resolution to lowest (screenshot). However, the 1080p file still did not play. 

![JFATV](https://user-images.githubusercontent.com/78215956/234425470-3c5f89ff-843d-40ac-8623-69e3d448d6d7.png)


Seems like there is an issue b/c the server uses file names to determine sorting order. Whereas the AndroidTV client uses resolution size to sort the files.  Here are a few tests that I ran with the results. 

Server order 			{notes on file, not naming scheme} -Result
Movie (year) – abc		{2160p file}
Movie (year) – bcd 		{1080p file}

AndroidTV order						
Movie (year) – abc		{2160p file} -abc plays
Movie (year) – bcd 		{1080p file} -bcd plays
_________________________________________________________________________________
Server order 		
Movie (year) – abc		{1080p file}
Movie (year) – bcd 		{2160p file}

AndroidTV order
Movie (year) – bcd		{2160p file} -bcd plays		
Movie (year) – abc 		{1080p file} -**_bcd plays_**
_________________________________________________________________________________

Server order 		
Movie (year) – 2160p		{2160p file}
Movie (year) – 1080p 		{1080p file}
Movie (year) – 720p 		{720p file}
Movie (year) – 480p		{480p file}


AndroidTV order
Movie (year) – 2160p		{2160p file} - 2160p plays		
Movie (year) – 1080p 		{1080p file} - _**2160p plays**_
Movie (year) – 720p		{720p file}   - 720p plays		
Movie (year) – 480p 		{480p file}   - 480p plays

**Comment by nielsvanvelzen** [comment] 2023-05-09 13:59
The app relies on the server to send the versions in the correct order. There is no client-side sorting done. If the order is not correct that's an issue on the server, not the client.
Closing as invalid (upstream issue).

**Closed as not planned by nielsvanvelzen** 2023-05-09 13:59 UTC
Labels: bug, playback
