### ISSUE TITLE
Next Up/Homescreen/Display Settings not updating

### ISSUE THREAD

**Issue by Eyadish** [jellyfin/jellyfin-androidtv#2419] opened 2023-01-14 20:12 UTC
### Describe the bug

Different elements on the homescreen isn't updating automatically (within unknown timeperiod). 

- New episodes added 2 days ago to media library didn't show up on homescreen under "Lastest <Library>" or "Next Up" when I've watched previously episodes of it.
If you go into a media library new content shows up there, go back to homescreen and still nothing

- When updating homescreen settings such as "Home Sections" or "Show watched indicators" it doesn't update anything on the homescreen.

To force an update, I've found that exiting the app completely and relaunching it forces an update. 
Doesn't seem like an new issue, found old reddit threads and old bug reports and is either [a bug that is closed/marked as fixed](https://github.com/jellyfin/jellyfin-androidtv/issues/1043), or an [enchacement label](https://github.com/jellyfin/jellyfin-androidtv/issues/1149). 

### Application version

0.15.2

### Where did you install the app from?

Google Play

### Device information

Chromecast Google TV 4k

### Android version

Android TV OS 12

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment] 2023-01-14 20:24
The homepage doesn't update automatically, this is not a bug. Closing as duplicate of #1149.

**Closed by nielsvanvelzen** 2023-01-14 20:24 UTC
Labels: bug
