### ISSUE TITLE
Music playback crashes on Fire Stick Gen 2

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#3414] opened 2024-02-28 19:38 UTC
### Describe the bug

1. Go to music library
2. Play song or album
3. App crashes

This crash only occurs in my old fire stick, new versions are not affected. Audio type didn't seem to matter, cashed playing flac or mp3.  

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.6
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
	at com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper.gasWaiters(AbstractFuture.java:1411)
	at com.google.common.util.concurrent.AbstractFuture.releaseWaiters(AbstractFuture.java:1126)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1005)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:782)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptiblySuccess(TrustedListenableFutureTask.java:136)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:88)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```  
***Logcat***: 
```log
02-28 14:17:26.830 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=fb525b7c-4fc4-9c82-92e9-7bac96d52fbe&GroupItems=true&format=json
02-28 14:17:26.837 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=79a2726d-3c50-e769-a8af-1e4184e4fccf&GroupItems=true&format=json
02-28 14:17:26.849 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=cdf09f64-0761-678f-9d34-c7ad7ed9ae22&GroupItems=true&format=json
02-28 14:17:27.020 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=f9421004-8c04-7bf6-c2f6-3200e9d5ad0b&GroupItems=true&format=json
02-28 14:17:27.040 I/Choreographer(13164): Skipped 147 frames!  The application may be doing too much work on its main thread.
02-28 14:17:27.057 I/art     (13327): Bumping SignalCatcher priority from 5 to 10
02-28 14:17:27.138 I/art     (13164): Background sticky concurrent mark sweep GC freed 28705(1296KB) AllocSpace objects, 0(0B) LOS objects, 6% free, 19MB/21MB, paused 34.087ms total 89.600ms
02-28 14:17:27.392 I/ContextImpl(13327): com.amazon.client.metrics.api registered service at i = 79
02-28 14:17:27.527 W/art     (13327): Suspending all threads took: 13.568ms
02-28 14:17:27.698 W/art     (13327): Suspending all threads took: 12.194ms
02-28 14:17:27.732 I/art     (13164): Background sticky concurrent mark sweep GC freed 8449(355KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 20MB/21MB, paused 10.814ms total 37.711ms
02-28 14:17:27.810 I/art     (13164): Background sticky concurrent mark sweep GC freed 1753(73KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 21MB/21MB, paused 7.507ms total 22.335ms
02-28 14:17:27.863 I/art     (13164): Background sticky concurrent mark sweep GC freed 2311(96KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 21MB/21MB, paused 9.575ms total 40.464ms
02-28 14:17:28.122 W/art     (13164): Suspending all threads took: 47.413ms
02-28 14:17:28.145 I/art     (13164): Rejecting re-init on previously-failed class java.lang.Class<androidx.exifinterface.media.ExifInterface$1>
02-28 14:17:28.145 I/art     (13164): Rejecting re-init on previously-failed class java.lang.Class<androidx.exifinterface.media.ExifInterface$1>
02-28 14:17:28.180 I/art     (13164): Background partial concurrent mark sweep GC freed 13895(817KB) AllocSpace objects, 9(515KB) LOS objects, 15% free, 21MB/25MB, paused 54.588ms total 314.125ms
02-28 14:17:28.342 W/art     (13327): Suspending all threads took: 8.416ms
02-28 14:17:28.352 I/ACRA    (13327): Sending report /data/data/org.jellyfin.androidtv/app_ACRA-approved/2024-02-28T14:17:02.049-05:00.stacktrace
02-28 14:17:28.472 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=52f1cc5c-fe5b-a8c9-452c-ebe7bca9e026&GroupItems=true&format=json
02-28 14:17:28.487 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=87686cb8-4850-0f36-1a88-0c827050ccef&GroupItems=true&format=json
02-28 14:17:28.490 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=bdf38141-c3a3-66eb-1a2a-8240d2e65e68&GroupItems=true&format=json
02-28 14:17:28.536 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=1a3f4e31-d2ac-2bcf-3b79-9d7e4566202e&GroupItems=true&format=json
02-28 14:17:28.608 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=0b1dd830-f92c-fda4-fcb7-23fead1927b7&GroupItems=true&format=json
02-28 14:17:28.629 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=a656b907-eb3a-7353-2e40-e44b968d0225&GroupItems=true&format=json
02-28 14:17:28.790 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=dab85afd-bad2-b355-18e1-d5d0e7356c51&GroupItems=true&format=json
02-28 14:17:28.910 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=9fcf63d9-3232-c8f3-246c-83c6611ed78d&GroupItems=true&format=json
02-28 14:17:28.916 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=d49a1e03-df26-2eef-307a-b2ec0b67fa4e&GroupItems=true&format=json
02-28 14:17:28.952 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=c248dc0b-ec4b-0ce8-fb01-231d1f12c5c1&GroupItems=true&format=json
02-28 14:17:29.151 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=63091556-61af-e2b1-a275-0be5d21f4fdf&GroupItems=true&format=json
02-28 14:17:29.174 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=8dacf156-4e6e-eff3-bdd6-31a91ef20b51&GroupItems=true&format=json
02-28 14:17:29.183 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=7e64e319-657a-9516-ec78-490da03edccb&GroupItems=true&format=json
02-28 14:17:29.363 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=d3d533b2-09b4-1c72-2103-a7213b3f994b&GroupItems=true&format=json
02-28 14:17:29.369 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=1daddc98-34a5-4a33-404f-9eb50cd25810&GroupItems=true&format=json
02-28 14:17:29.373 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Views?format=json
02-28 14:17:29.467 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=0b804f14-a558-3d70-ca12-5d42f6bbf98c&GroupItems=true&format=json
02-28 14:17:29.537 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CSeriesPrimaryImage&ParentId=d7e58e58-ad49-209c-5917-1d6a3ecd6952&GroupItems=true&format=json
02-28 14:17:29.809 I/art     (13164): Background sticky concurrent mark sweep GC freed 14175(608KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 23MB/24MB, paused 14.544ms total 73.943ms
02-28 14:17:29.885 I/Choreographer(13164): Skipped 169 frames!  The application may be doing too much work on its main thread.
02-28 14:17:30.266 W/art     (13164): Suspending all threads took: 7.028ms
02-28 14:17:30.283 I/art     (13164): Background sticky concurrent mark sweep GC freed 7428(403KB) AllocSpace objects, 7(112KB) LOS objects, 1% free, 24MB/24MB, paused 9.226ms total 168.151ms
02-28 14:17:30.463 I/art     (13164): Background partial concurrent mark sweep GC freed 31612(1907KB) AllocSpace objects, 27(1495KB) LOS objects, 15% free, 21MB/25MB, paused 2.285ms total 175.749ms
02-28 14:17:32.483 W/art     (13164): Suspending all threads took: 5.750ms
02-28 14:17:32.501 I/art     (13164): Background sticky concurrent mark sweep GC freed 44946(1989KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 21MB/23MB, paused 7.866ms total 54.599ms
--------- beginning of amazon_main
02-28 14:17:32.749 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 1, Repeat: 0, EventTime: 727410, Latency: 1319, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:32.749 I/Choreographer(13164): Skipped 151 frames!  The application may be doing too much work on its main thread.
02-28 14:17:33.154 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 727470, Latency: 1701, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.179 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 1, Repeat: 0, EventTime: 727650, Latency: 1545, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.186 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 727772, Latency: 1430, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.208 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 1, Repeat: 0, EventTime: 728509, Latency: 715, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.215 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 728649, Latency: 582, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.238 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 1, Repeat: 0, EventTime: 728910, Latency: 344, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.303 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 728990, Latency: 329, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:33.843 I/art     (13164): Background sticky concurrent mark sweep GC freed 15720(790KB) AllocSpace objects, 7(112KB) LOS objects, 4% free, 22MB/23MB, paused 22.543ms total 193.934ms
02-28 14:17:34.370 I/art     (13164): Background partial concurrent mark sweep GC freed 11579(601KB) AllocSpace objects, 9(237KB) LOS objects, 14% free, 23MB/27MB, paused 10.017ms total 319.240ms
02-28 14:17:35.263 I/art     (13164): Background sticky concurrent mark sweep GC freed 907(40KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 27MB/27MB, paused 6.531ms total 21.845ms
02-28 14:17:35.494 I/art     (13164): Background partial concurrent mark sweep GC freed 5235(282KB) AllocSpace objects, 1(16KB) LOS objects, 12% free, 28MB/32MB, paused 10.564ms total 228.294ms
02-28 14:17:35.717 I/AutoBitrate(13164): Auto bitrate set to: 2048393
02-28 14:17:35.816 I/art     (13164): Background partial concurrent mark sweep GC freed 1392(73KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 33MB/37MB, paused 1.984ms total 187.895ms
02-28 14:17:37.422 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 733169, Latency: 269, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:37.859 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?Filters=IsFavorite&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&recursive=true&Limit=60&SortBy=SortName&IncludeItemTypes=MusicAlbum%2CMusicArtist&ParentId=7e64e319-657a-9516-ec78-490da03edccb&format=json
02-28 14:17:37.871 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2CCumulativeRunTimeTicks%2CChildCount&recursive=true&sortOrder=Descending&Limit=60&SortBy=DateCreated&IncludeItemTypes=Playlist&format=json
02-28 14:17:38.013 W/View    (13164): requestLayout() improperly called by android.widget.TextView{12de7bed V.ED.... ......ID 120,40-1600,126 #7f0b02f5 app:id/title} during layout: running second layout pass
02-28 14:17:38.013 W/View    (13164): requestLayout() improperly called by android.widget.LinearLayout{18cb2a22 V.E..... ......ID 120,132-1620,172 #7f0b01a7 app:id/infoRow} during layout: running second layout pass
02-28 14:17:38.030 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?Filters=IsPlayed&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&SortBy=DatePlayed&IncludeItemTypes=Audio&ParentId=7e64e319-657a-9516-ec78-490da03edccb&EnableTotalRecordCount=false&recursive=true&Limit=50&format=json
02-28 14:17:38.412 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/Latest?Limit=50&IncludeItemTypes=Audio&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=7e64e319-657a-9516-ec78-490da03edccb&GroupItems=true&format=json
02-28 14:17:38.707 I/art     (13164): Background sticky concurrent mark sweep GC freed 26136(1179KB) AllocSpace objects, 2(32KB) LOS objects, 3% free, 35MB/36MB, paused 7.924ms total 101.181ms
02-28 14:17:39.091 I/art     (13164): Background sticky concurrent mark sweep GC freed 4326(233KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 35MB/36MB, paused 7.431ms total 35.405ms
02-28 14:17:39.130 W/View    (13164): requestLayout() improperly called by android.widget.LinearLayout{18cb2a22 V.E..... ......ID 120,132-1620,172 #7f0b01a7 app:id/infoRow} during layout: running second layout pass
02-28 14:17:39.130 W/View    (13164): requestLayout() improperly called by android.widget.TextView{12de7bed V.ED.... ......ID 120,40-1600,126 #7f0b02f5 app:id/title} during layout: running second layout pass
02-28 14:17:39.170 I/Choreographer(13164): Skipped 32 frames!  The application may be doing too much work on its main thread.
02-28 14:17:39.228 W/art     (13164): Suspending all threads took: 9.927ms
02-28 14:17:39.268 I/art     (13164): Background sticky concurrent mark sweep GC freed 3313(308KB) AllocSpace objects, 7(112KB) LOS objects, 0% free, 35MB/36MB, paused 29.940ms total 83.151ms
02-28 14:17:39.500 I/art     (13164): Background partial concurrent mark sweep GC freed 16530(1076KB) AllocSpace objects, 24(4MB) LOS objects, 11% free, 31MB/35MB, paused 4.749ms total 231.633ms
02-28 14:17:41.754 W/art     (13164): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-28 14:17:41.847 I/ItemListFragment(13164): Got playback state change event IDLE for item <unknown>
02-28 14:17:41.889 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items/27acbb0b-2361-293b-aec9-046f49823995?format=json
02-28 14:17:42.091 I/jellyfin-apiclient(13164): Response received from: http://192.168.1.2:8096/Users/2e695138-b100-4cd4-89c0-bc17f36c8608/Items?Fields=PrimaryImageAspectRatio%2CGenres%2CChildCount&recursive=true&Limit=200&SortBy=SortName&IncludeItemTypes=Audio&ParentId=27acbb0b2361293baec9046f49823995&format=json
02-28 14:17:44.968 W/!Amazon (13164): remote_perf key event latency detected [Source: ViewRootImpl, KeyCode: KEYCODE_XXXX, IsDown: 0, Repeat: 0, EventTime: 740750, Latency: 234, DeviceId: 5, AppPackage: org.jellyfin.androidtv]
02-28 14:17:44.992 I/MaliEGL (13164): [Mali]window_type=1, is_framebuffer=0, errnum = 0
02-28 14:17:44.992 I/MaliEGL (13164): [Mali]surface->num_buffers=3, surface->num_frames=2, win_min_undequeued=1
02-28 14:17:44.992 I/MaliEGL (13164): [Mali]max_allowed_dequeued_buffers=2
02-28 14:17:46.932 W/InputEventReceiver(13164): Attempted to finish an input event but the input event receiver has already been disposed.
02-28 14:17:46.940 I/HomeRowsFragment(13164): Updating audio queue in HomeFragment (onQueueStatusChanged)
02-28 14:17:46.985 I/org.jellyfin.sdk.api.client.KtorClient(13164): POST http://192.168.1.2:8096/Items/3845bb25-c8b8-2ef2-3fb8-437f38c7c15b/PlaybackInfo
02-28 14:17:47.392 I/art     (13164): Background sticky concurrent mark sweep GC freed 44269(2009KB) AllocSpace objects, 14(2MB) LOS objects, 5% free, 33MB/35MB, paused 21.112ms total 263.311ms
02-28 14:17:47.426 E/ACRA    (13164): ACRA caught a NoSuchMethodError for org.jellyfin.androidtv
02-28 14:17:47.426 E/ACRA    (13164): java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper.gasWaiters(AbstractFuture.java:1411)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.AbstractFuture.releaseWaiters(AbstractFuture.java:1126)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1005)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:782)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptiblySuccess(TrustedListenableFutureTask.java:136)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:88)
02-28 14:17:47.426 E/ACRA    (13164): 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
02-28 14:17:47.426 E/ACRA    (13164): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-28 14:17:47.426 E/ACRA    (13164): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-28 14:17:47.426 E/ACRA    (13164): 	at java.lang.Thread.run(Thread.java:818)

```  

### App information

***App version***: `0.16.6` (`160699`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"tank","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"tank","DISPLAY":"LVY48F","FINGERPRINT":"Amazon\/full_tank\/tank:5.1.1\/LVY48F\/288.6.8.8_user_688804020:user\/release-keys","HARDWARE":"mt8127","HOST":"i3-ri-14-use1a-b-16-04-fos-6","ID":"LVY48F","IS_DEBUGGABLE":false,"MANUFACTURER":"Amazon","MODEL":"AFTT","PRODUCT":"full_tank","RADIO":"unknown","REQ_BATTERY_LEVEL":0,"SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1700534536000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","WAN":false,"VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"288.6.8.8_user_688804020","RELEASE":"5.1.1","RESOURCES_SDK_INT":22,"SDK":"22","SDK_INT":22,"SECURITY_PATCH":"2022-00-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160699,"VERSION_NAME":"0.16.6"}
```  

### Device information

***Android version***: `5.1.1`  
***Device brand***: `Amazon`  
***Device product***: `full_tank`  
***Device model***: `AFTT`  

### Crash information

***Start time***: `2024-02-28T14:17:15.267-05:00`  
***Crash time***: `2024-02-28T14:17:47.677-05:00`  

### Application version

.16.6

### Where did you install the app from?

Sideloaded APK

### Device information

Fire TV Stick – 2nd Gen 2016

### Android version

Fire OS 5.2.9.5 (Andriod 5.1.1)

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment] 2024-02-28 19:50
Duplicate of #3305

**Closed by nielsvanvelzen** 2024-02-28 19:50 UTC
Labels: bug
