### ISSUE TITLE
Add subtitle download to vidéo panel

### ISSUE THREAD

**Issue by bibitocarlos** [jellyfin/jellyfin-androidtv#3027] opened 2023-09-06 16:03 UTC
### Describe the feature you'd like

Hi, 
Everything is in the topic, could you add à download subtitles button in the vidéo play-back panel ?
Currently i have to download them from kodi and then play the vidéo in jellyfin... 
Thanks for your hard work.

**Comment by nielsvanvelzen** [comment] 2024-02-12 08:14
Closing as duplicate of #690

**Closed by nielsvanvelzen** 2024-02-12 08:14 UTC
Labels: enhancement
