### ISSUE TITLE
Screensaver option safe for OLED TVs

### ISSUE THREAD

**Issue by kingp0dd** [jellyfin/jellyfin-androidtv#3269] opened 2023-12-30 04:04 UTC
### Describe the feature you'd like

The new screensaver option looks good.

Would it be possible to have an option for OLED TVs that are susceptible to screen burn-in?

A plain black screensaver would be nice. Or maybe have the Jellyfin logo in the current screensaver to move around?

**Comment by nielsvanvelzen** [comment] 2023-12-30 08:57
Duplicate of #1888

**Closed by nielsvanvelzen** 2023-12-30 08:57 UTC
Labels: enhancement
