### ISSUE TITLE
My Media (small) not working

### ISSUE THREAD

**Issue by obendev** [jellyfin/jellyfin-androidtv#3176] opened 2023-11-15 13:26 UTC
### Describe the bug

In Jellyfin Settings, for **Home screen section 1**, selecting **My Media (small)** will use **My Media** (the default (not the small one)) instead.

### Application version

0.16.0-beta.5

### Where did you install the app from?

Google Play

### Device information

Sony XR-83A90J

### Android version

Android 10

### Jellyfin server version

10.8.12

**Comment by nielsvanvelzen** [comment] 2023-11-15 13:36
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed by nielsvanvelzen** 2023-11-15 13:36 UTC
Labels: bug
