### ISSUE TITLE
Add "Edit subtitles" 3-dot menu choice

### ISSUE THREAD

**Issue by nylimited** [jellyfin/jellyfin-androidtv#3696] opened 2024-06-25 14:29 UTC
### Describe the feature you'd like

When opensubtitles plugin is installed Jellyfin adds an "Edit subtitles" choice to the 3-dot menu of the TV episode or movie which will allow the viewer to try and import subtitles for the media in their choice language. This is available and working fine on the web interface of Jellyfin but is non-existent in the Android app.  Since I have not seen this choice in this app before I am guessing it is a feature request, not a bug ...  using v0.16.11 on Samsung and LG TVs ..

**Comment by nielsvanvelzen** [comment] 2024-06-25 14:40
Duplicate of #690

**Closed by nielsvanvelzen** 2024-06-25 14:40 UTC
Labels: enhancement

**Comment by nylimited** [comment] 2024-06-25 15:03
Thanks for the quick notice!  I obviously missed #690, my bad ...
