### ISSUE TITLE
Android TV App - Next Up/Play Next Episode Automatically Issue

### ISSUE THREAD

**Issue by AnotherDaftPunk** [jellyfin/jellyfin-androidtv#3971] opened 2024-09-08 03:31 UTC
### Describe the bug

*These issues only apply to Android TV client on Zidoo Z9X as far as i'm aware. i don't have another box to test on.

The issue that i'm having is that ever since the Android TV client went from 0.15.12 to 0.16.0 and beyond, when an episode is over and you have "play next episode automatically" checked, it used to show a background image with a "cancel" button and a "play now" button in the bottom right corner of the screen, and it would wait the allotted amount of time you selected for "next up timer duration". now, it just goes straight to next episode immediately and doesn't display that screen or the buttons at the bottom.

Another issue that's related is that on the Zidoo there's a setting to have the front display show the clock, time remaining or time played. i usually have this set to show time remaining and since 0.16.0 and beyond, it will only show time remaining for the first episode and when the next episode starts, it just reverts my front display to the regular clock instead of time remaining. all of this was working perfectly in 0.15.12. is there any chance this gets looked at and possibly fixed, since it seems like it's a Jellyfin issue and not a Zidoo issue? 

### Application version

0.17.4

### Where did you install the app from?

Sideloaded APK

### Device information

Zidoo Z9X

### Android version

Android 9

### Jellyfin server version

10.9.10

**Comment by nielsvanvelzen** [comment] 2024-09-08 08:08
The "next up" screen is no longer used when an external video player is used. This change was made in #2745 for 0.16.0 to improve the stability of the app. It should be possible to re-introduce this screen for external video players and we would accept a pull request for that. It would be considered a feature, not a bug.

The only preference in the app related to the clock is where it will show (always/in menus/player only/never). There is no option to change if it shows time remaining or time of completion. I guess you're confused with a setting in the external video player or I don't understand the question correctly.

**Comment by AnotherDaftPunk** [comment] 2024-09-08 16:58
I think the clock issue is just a side effect of whatever changed with the next up screen disappearing. the clock feature i'm speaking about is in the zidoo settings and not the jellyfin android tv app settings. in the zidoo settings, there's an option for the front display to show "the normal clock", "time remaining" or "time played". i have this set to "time remaining" so i can easily see how much of the film or episode is remaining without having to pause or hit the info button. as a side effect of the next up screen disappearing in 0.16.0 and there being no delay between episodes, it bugs out the zidoo on the start of the following episodes and causes the zidoo to show the basic clock instead of the "time remaining" on each episode. this isn't an issue on the first episode played, just on following episodes. 

honestly this is my biggest problem with the change. i don't necessarily need the next up screen to pop, i just need my zidoo to not bug out and to actually display the time remaining of each episode like it should. that's why i figured this was a bug with jellyfin and not the zidoo since it worked perfectly fine before the change. as it stands now, i've had to turn off the "play next episode automatically" option on jellyfin then press stop on the remote when the credits roll and then manually start the next episode. that's the only way my zidoo display doesn't bug out and does what it's supposed to do.

**Comment by nielsvanvelzen** [comment] 2024-09-08 17:36
If the clock is really in the external player app then I can't imagine it being an issue with the Jellyfin app. When opening videos in a different app on Android you use an "Intent" which contains some information. In the case of a video that is the URL to the video. We did not change anything in this part in 0.16.

What I can imagine is that the video player you're using has a bug where it doesn't reset something internally when it's opened to play the next episode immediately after closing the previous one. This is just guessing work though as I've never used the Zidoo app myself. I would advise contacting the developer for this problem.

**Comment by AnotherDaftPunk** [comment] 2024-09-08 19:48
Zidoo is not an app, it's a media player box like nvidia shield or say dune homatics 4k box. so the clock options are in the box's default OS. it does have it's own media player engine (i think it's called vs10 engine) and i have "use external player" selected in jellyfin so that it uses Zidoo's internal player. admittedly this is all technically over my head, i just know what settings work and now don't work anymore. and if it's truly not a jellyfin issue, then the problem will never be fixed because the z9x box is now 2 generations old and they just released the last firmware update that they're likely to ever release for it. appreciate the info though.

**Comment by nielsvanvelzen** [comment] 2024-09-08 20:03
Sorry I meant the video player app on the Zidoo devices. I'm aware it's a media box. It's unfortunate to hear the manufacturer stopped support for it as I'm confident the issue is on their side.

The video player app is just an app though so you may be able to sideload a newer version of it to your older generation hardware if you can find it somewhere.

I'll close this issue for now as there doesn't seem to be anything to do on our side, if however you find more info/hear back from the manufacturer feel free to let me know!

**Closed by nielsvanvelzen** 2024-09-08 20:03 UTC
Labels: bug
