### ISSUE TITLE
Movie sorting is broken when sorting by Date Added with no filters

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-androidtv#2719] opened 2023-04-28 13:25 UTC
### Describe the bug

I had originally logged this against the Jellyfin server, but I have come to realize that it is probably a client-side bug that exists similarly in many different clients. This is a weird bug, and it's taken me a while to narrow down the scope.

https://github.com/jellyfin/jellyfin/issues/7959

To reproduce:
* View the _Movies_ library folder, in the view that shows you everything. My _Movies_ library folder happens to be a combination of various folders in my library, but I'm not sure if that matters for this bug.
* Sort the view by **Date Added, Descending** so that the most-recently added movies appear first.
* When there are no filters applied, the sorting does not appear to be correct:
  * I do not expect to see Collections in this view, but I do.
  * Only one page (approximately) worth of items is present in the resulting set of items with no indication of the actual total number of items
  * The N items that are displayed *are* the latest N items, but they appear to be sorted first by whether or not they are a Collection or a Movie (Collections come first), and then by **Name** in descending order. (This is a bit weird, so I hope I've explained it well.)
* When I apply a filter, such as **Unplayed**, which should not affect the order of the items, just filter some out, I get a *completely* different ordering of the items (the *correct* ordering), as well as seeing multiple pages of results, as I should.

The easiest way to see this in action is to go into that _Movies_ view, sorted by **Date Added, Descending** and just toggle the **Unplayed** or **Played** filters on and off. The order shouldn't change, but it does. I can try and take a screen capture video of this issue if necessary.

I do NOT see this bug in the Jellyfin-Vue client, nor the Findroid third-party client, but I DO see it in Jellyfin-Android, Jellyfin-AndroidTV, and Jellyfin-Web. I've looked at the server's code, and I don't see anywhere that I think could be causing this kind of behaviour. Also, the number of items shown is dependent on the client: **Android TV** shows **56** items, while the **web** and **android** clients are dependant on the user's _library page size_ setting.

### Application version

0.15.7

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

12

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2023-04-29 08:17
You're saying jellyfin-vue doesn't have this issue but that client doesn't allow sorting by date added, only release date (which in the other clients is called premiere date). I can't reproduce the issue with the ATV client (sorting stays the same when I toggle the watched filter) so I'm not sure what goes wrong here.
These are the network requests for jellyfin-web and jellyfin-androidtv:
```
WEB
/Users/{{uuid}}/Items?SortBy=DateCreated%2CSortName%2CProductionYear&SortOrder=Descending&IncludeItemTypes=Movie&Recursive=true&Fields=PrimaryImageAspectRatio%2CMediaSourceCount%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&StartIndex=0&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&Limit=100&Filters=IsUnPlayed
ATV
/Users/{{uuid}}/Items?ParentId=f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805&SortBy=DateCreated%2CSortName&recursive=true&Filters=IsUnplayed&Fields=PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId&sortOrder=Descending&Limit=55&IncludeItemTypes=Movie&format=json
```

Here is a table for comparison:
| Parameter        | Web                                                        | ATV                                                                                       |
| ---------------- | ---------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| EnableImageTypes | Primary%2CBackdrop%2CBanner%2CThumb                        | -                                                                                        |
| SortBy           | DateCreated%2CSortName%2CProductionYear                    | DateCreated%2CSortName                                                                    |
| Fields           | PrimaryImageAspectRatio%2CMediaSourceCount%2CBasicSyncInfo | PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId |
| Filters          | IsUnPlayed                                                 | IsUnplayed                                                                                |
| ImageTypeLimit   | 1                                                          | -                                                                                        |
| IncludeItemTypes | Movie                                                      | Movie                                                                                     |
| Limit            | 100                                                        | 55                                                                                        |
| ParentId         | f137a2dd21bbc1b99aa5c0f6bf02a805                           | f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805                                                      |
| Recursive        | true                                                       | true                                                                                      |
| SortOrder        | Descending                                                 | Descending                                                                                |
| StartIndex       | 0                                                          | -                                                                                        |
| Format           | -                                                          | json                                                                                      |


As you can see both clients use a nearly equal request, so that probably explains the equal behavior. Those requests looks valid to me though, so it's probably a server issue.

**Comment by SteveDinn** [comment] 2023-04-29 14:29
Ok. I am totally willing to admit that it is actually a server issue. That's what I thought it was in the first place.

So you can't reduce it either...  I had reported a version of this defect against the server more than a year ago, but it was closed as unreproducible; I thought because I didn't explain it clearly. 

Are there any docs on how to get started debugging the server? I'm a dotNET dev, but I have little to no experience with Jellyfin's code.

**Comment by SteveDinn** [comment] 2023-05-02 04:11
It's definitely a server problem. I can reproduce it with the API.

**Comment by nielsvanvelzen** [comment] 2023-05-02 07:19
Thanks for confirming. I'll close this issue in favor of the server issue (jellyfin/jellyfin#7959).

**Closed by nielsvanvelzen** 2023-05-02 07:19 UTC
Labels: bug
