### ISSUE TITLE
Title below poster within library

### ISSUE THREAD

**Issue by TotoCon** [jellyfin/jellyfin-androidtv#2088] opened 2022-09-23 15:11 UTC
### Describe the feature you'd like

On the homescreen and the search results are displayed with the title below the posters.
Would it be possible to make the titles shown below posters within a library as well?

**Comment by nielsvanvelzen** [comment] 2022-09-23 17:00
Duplicate of #1778

**Closed by nielsvanvelzen** 2022-09-23 17:00 UTC
Labels: duplicate, enhancement
