### ISSUE TITLE
Play Version

### ISSUE THREAD

**Issue by RemuxKid** [jellyfin/jellyfin-androidtv#834] opened 2021-04-24 10:19 UTC
**Describe the feature you'd like**	
I have merged the same movies together where there are more than one resolutions. I only have one combined library. At the moment I cannot play a specific version (i.e. 4K on my TV). By default it plays the 1080p version. I would like a way for me to select the version I would like Jellyfin to Play.

**Comment by NebelNidas** [comment] 2021-04-24 10:35
Duplicate of #173.

**Closed** 2021-04-24 11:59 UTC
Labels: enhancement
