### ISSUE TITLE
No video only blackscreen with audio playing

### ISSUE THREAD

**Issue by TheCaging** [jellyfin/jellyfin-androidtv#3817] opened 2024-07-29 22:29 UTC
### Describe the bug

Been using jellyfin for awhile but recently its become entirely unusable. Couple days ago I uploaded a few movies to my server and went to my AndroidTV to see if they were scanned in. Then I tried playing one and all I get is a black screen with only the Audio. I know the files are good as they playback fine through the browser on my computer and android app on my phone but on my AndroidTV it gives the above behavior. This behavior extends to all video content through the AndroidTV app even stuff that worked before the bug appeared. I've tried rebooting multiple times, I've deleted the app and reinstalled, I've even deleted the server and started from scratch and it still does the same thing. I know In the log file there are issues with the trickplay but I was having this issue even with the trickplay disabled.

### Logs

https://pastebin.com/VUS6EtHA

### Application version

0.16.11

### Where did you install the app from?

None

### Device information

Sony x90L 4k SmartTV

### Android version

Android 10

### Jellyfin server version

10.9.6

**Comment by ThomasPGH** [comment] 2024-08-10 13:48
I now got one film with the same issue. Audio plays fine but there's no video. Only a black screen. The video plays fine inside a browser and the iPhone client. I haven't tried the Android client but the Android TV client only shows a black screen while the audio plays and the film advances normally.

From what looks different to me is that when you click on Media Info the video track is not the first track at the top.

![Screenshot 2024-08-10 144649](https://github.com/user-attachments/assets/4aca6fca-e226-479d-a24b-2251be541ba9)
![Screenshot 2024-08-10 144749](https://github.com/user-attachments/assets/e7b52241-4ec0-48a1-bb9b-68a314b9743e)

**Comment by ThomasPGH** [comment] 2024-08-10 18:23
On an Android tablet, the video plays when Web Player is selected but a black screen is displayed when set to Integrated Player. The audio plays in both cases.

**Comment by zkhcohen** [comment] 2024-08-10 18:40
> On an Android tablet, the video plays when Web Player is selected but a black screen is displayed when set to Integrated Player. The audio plays in both cases.

Does this issue appear to be related? https://github.com/jellyfin/jellyfin-androidtv/issues/3830

Were these files modified with FFMPEG 6 or mkvtoolnix v85.0.0?

**Comment by ThomasPGH** [comment] 2024-08-10 18:45
> Does this issue appear to be related? #3830

I don't know. The film actually plays but no video shows up.

> Were these files modified with FFMPEG 6 or mkvtoolnix v85.0.0?

The file has in fact been modified with mkvtoolnix but v86.

**Comment by zkhcohen** [comment] 2024-08-10 18:48
> The file has in fact been modified with mkvtoolnix but v86.

Can you try remuxing it in FFMPEG and see if it suddenly works?

```ffmpeg -i input.mkv -c copy output.mkv```

**Comment by ThomasPGH** [comment] 2024-08-10 18:51
> > Were these files modified with FFMPEG 6 or mkvtoolnix v85.0.0?
> 
> The file has in fact been modified with mkvtoolnix but v86.

To explude mkvtoolnix I just restored the untouched (at least by me) version and the result is the same: audio but no video.

**Comment by ThomasPGH** [comment] 2024-08-10 18:56
> Can you try remuxing it in FFMPEG and see if it suddenly works?
> 
> `ffmpeg -i input.mkv -c copy output.mkv`

Just started. It'll take a few minutes to complete.

**Comment by TheCaging** [comment] 2024-08-10 19:33
Well I've been fiddling with it for a while. I accidently popped the breaker that the server was being powered with, after that it had a hard reboot and the issue went away.

**Comment by ThomasPGH** [comment] 2024-08-10 20:08
> > Can you try remuxing it in FFMPEG and see if it suddenly works?
> > `ffmpeg -i input.mkv -c copy output.mkv`
> 
> Just started. It'll take a few minutes to complete.

This'll take ages to complete, not just a few minutes ;)

**Comment by zkhcohen** [comment] 2024-08-10 20:14
> > > Can you try remuxing it in FFMPEG and see if it suddenly works?
> > > `ffmpeg -i input.mkv -c copy output.mkv`
> > 
> > 
> > Just started. It'll take a few minutes to complete.
> 
> This'll take ages to complete, not just a few minutes ;)

If it's properly remuxing, I'm surprised it's taking so long. Afterwards can you confirm that it didn't actually transcode the media, please?

I remuxed a 2GB file in about a minute on a notebook i7.

**Comment by ThomasPGH** [comment] 2024-08-10 21:07
> > > > Can you try remuxing it in FFMPEG and see if it suddenly works?
> > > > `ffmpeg -i input.mkv -c copy output.mkv`
> > > 
> > > 
> > > Just started. It'll take a few minutes to complete.
> > 
> > 
> > This'll take ages to complete, not just a few minutes ;)
> 
> If it's properly remuxing, I'm surprised it's taking so long. Afterwards can you confirm that it didn't actually transcode the media, please?
> 
> I remuxed a 2GB file in about a minute on a notebook i7.

I had accidentally specified two output files.

**Comment by ThomasPGH** [comment] 2024-08-10 21:22
The output version is about 12 GiB smaller than the original but the issue persists. Audio plays but no video. The output version only has one audio track, which is the one the input version had as default.

The web player happily plays both versions with video and audio while the Android TV version only plays both with missing video.

**Comment by ThomasPGH** [comment] 2024-08-10 21:42
> Well I've been fiddling with it for a while. I accidently popped the breaker that the server was being powered with, after that it had a hard reboot and the issue went away.

I thought I could give this a go too. I shut down the machine, switched it off, and back on again. It did not fix it.

Note that I only got one film with this issue. Others play with video and audio.

**Comment by ThomasPGH** [comment] 2024-08-11 16:14
> @ThomasPGH Does your Tv/device support HEVC level 153? does it also support DV?

I don't know but considering it works with the web player even on Android (not Android TV) this is probably not relevant.

**Comment by ThomasPGH** [comment] 2024-08-12 19:22
Nah, it didn't fix it.

**Comment by dtrexler** [comment] 2024-09-17 01:45
The video being DV profile 7 can cause issues from what I've seen, had the same issue with some movies on an incompatible device. Converting to something like DV profile 8 may be a band-aid solution if you want a quick fix.

**Comment by suncokret12** [comment] 2024-11-09 01:51
I have the same problem; however, if I go into the options and choose the external player option, then play the movie with VLC, it works just fine, but it doesn't work with the native player. My TV supports Dolby and HDR10. It's annoying because I need the option to adjust the bitrate in a VLC player. I just switched from the Plex free version to Jellyfin, and I'm disappointed; everything worked fine on Plex.

**Comment by Dnkhatri** [comment] 2024-12-17 11:15
Kodi seems to have fixed the problem  it works by completely removing the metadata from the bitstream prior to decoding
https://github.com/xbmc/xbmc/pull/24584

I hope something similar can be added to the android tv player app.

**Comment by nielsvanvelzen** [comment] 2024-12-18 18:14
Closing as duplicate of #2700

**Closed by nielsvanvelzen** 2024-12-18 18:14 UTC
Labels: bug, playback
