### ISSUE TITLE
Choosing "Play all" or "Shuffle all" from an artist page plays the whole music library instead

### ISSUE THREAD

**Issue by ZHoob2004** [jellyfin/jellyfin-androidtv#3318] opened 2024-01-19 19:16 UTC
### Describe the bug

1. Select an artist in a music library
2. Press "Play all"
3. Every album from the library is now queued in alphabetical order by album title.

Same behavior if choosing "Shuffle all". It doesn't even shuffle them, which would at least be half correct...

### Application version

0.16.4

### Device information

Google Chromecast with Google TV

### Android version

Android TV OS 12

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment] 2024-01-20 11:21
I'm unable to reproduce this issue. When I use the "play now" or "shuffle all" buttons from the artist page it will only queue items from that specific artist.

**Comment by ZHoob2004** [comment] 2024-01-21 04:42
Hmmm, well it's definitely doing it here. I thought maybe it was only if I went from a recent album to the artist and then played but I just double checked and it does so no matter what path I take. 

What is needed from me, is there a log I can collect to capture this?

**Comment by nielsvanvelzen** [comment] 2024-01-21 11:06
Can you check if this issue also happens with the Jellyfin web client? Right now the app just asks the server to provide the items to play, so it might be an issue on the server-side.

**Comment by ZHoob2004** [comment] 2024-01-21 17:23
Just got a chance to test on desktop and the main android app. Behavior is closer to correct, but not exactly. Both "Play all" and "Shuffle all" correctly queue only tracks from the selected artist, and "Shuffle all" behaves exactly as expected.

"Play all" on the browser queues the most recent album in order, but then the rest of the tracks are mixed up, but always in the same order. ~~I can't immediately see what method is being used to sort them~~ it seems to be taking the first track in each album, alphabetizing them, the adding them to the queue, and so on for each album.

**Comment by nielsvanvelzen** [comment] 2024-02-03 14:15
It is possible that your music library does not follow the correct directory structure. That would cause the server to send wrong queues.

**Comment by ZHoob2004** [comment] 2024-02-03 23:25
I think my file structure is fine, but here's a screenshot just to make sure. I'm getting similar behavior on other clients so I should probably create a new issue in the main jellyfin github to maybe get to the bottom of this.

![image](https://github.com/jellyfin/jellyfin-androidtv/assets/6957037/1d858661-b9da-4fbb-b74b-a2ddc0d127bd)

**Comment by nielsvanvelzen** [comment] 2024-02-04 17:00
That looks like a valid file structure yes. I'd suggest using our troubleshooting channels on Matrix/forum/discord so the folks over there can help figure out what goes wrong.

https://jellyfin.org/contact

Closing this issue for now as currently it does not seem like a problem with the client.

**Closed by nielsvanvelzen** 2024-02-04 17:00 UTC
Labels: bug, playback
