### ISSUE TITLE
Seeking does not respect preferences and is locked to 30 seconds

### ISSUE THREAD

**Issue by brettp** [jellyfin/jellyfin-androidtv#2592] opened 2023-03-14 03:25 UTC
### Describe the bug

Opening an issue as requested by @mueslimak3r for the problem as reported here: https://reddit.com/r/jellyfin/comments/xzyhv9/seek_is_stuck_to_30_seconds_when_using_google_tv/

1. Set seeking preferences for profile
2. Open a video
3. Try to seek
4. Observe seeking is locked at 30s intervals

### Application version

0.15.4

### Device information

CCWGTV

### Android version

Android 12, STTE.220920.015.H1.9408258

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment] 2023-03-14 08:21
Duplicate of #2529

**Closed by nielsvanvelzen** 2023-03-14 08:21 UTC
Labels: bug, playback
