### ISSUE TITLE
Media Playback info

### ISSUE THREAD

**Issue by shimulroy842** [jellyfin/jellyfin-androidtv#1769] opened 2022-06-10 13:36 UTC
### Describe the feature you'd like

First of all a Huge thanks to jellyfin dev team for your work. 
I was wondering if it is possible to get media playback info or Nerd state on Android Tv. Both Desktop and Android App have it.
Thank You.

**Comment by nielsvanvelzen** [comment] 2022-06-10 14:33
Duplicate of #1637

**Closed by nielsvanvelzen** 2022-06-10 14:33 UTC
Labels: enhancement
