### ISSUE TITLE
How can I change subtitle sync (delay etc.)

### ISSUE THREAD

**Issue by tundrablasen** [jellyfin/jellyfin-androidtv#3904] opened 2024-08-18 07:47 UTC
### Describe the feature you'd like

Since libVLC was removed:

how can I change subtitle sync if they are out of sync? 

Before I could just go with the remote to the subtitles sync button in the GUI and change with + or - sync buttons

**Comment by nielsvanvelzen** [comment] 2024-08-18 07:51
The subtitle delay option was only ever implemented for the experimental LibVLC integration. So it is no longer available. Closing as duplicate of #2479

**Closed by nielsvanvelzen** 2024-08-18 07:51 UTC
Labels: enhancement
