### ISSUE TITLE
can't use another port #

### ISSUE THREAD

**Issue by sbcrumb** [jellyfin/jellyfin-androidtv#52] opened 2019-02-22 14:07 UTC
Running jellyfin through a proxy so https://jellyfin.domainname.com:443 then forwards to the default port.
but in the app I can't tell it to use 443 even with adding it at the end of the url. however I can in the android phone app give it a port number.

**Comment by thornbill** [comment] 2019-02-22 22:26
Thanks for the report! I'm closing this because it sounds like a duplicate of #36.

**Closed by thornbill** 2019-02-22 22:26 UTC
Labels: duplicate

**Comment by sbcrumb** [comment] 2019-02-22 22:31
Thanks sorry didn't see that one.
