### ISSUE TITLE
Allow search and download subtitle.

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1497] opened 2022-03-05 12:56 UTC
### Describe the feature you'd like

Currently, the open subtitle plugin is available. It should download the subtitle while the media file is scanned. But most of the time, it doesn't work. Please make the subtitle search and download option as plex have.

**Comment by nielsvanvelzen** [comment] 2022-03-05 12:59
Duplicate of #406

**Closed by nielsvanvelzen** 2022-03-05 12:59 UTC
Labels: enhancement
