### ISSUE TITLE
What should be black bars appear as the show's background when playing next episode 

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-androidtv#3764] opened 2024-07-16 23:03 UTC
### Describe the bug

1. Play an episode of TV where black bars will be visible on the sides or top & bottom. 
2. Ensure there is also an upcoming episode to play after the current one. 
3. When playing the initial episode, the bars will be black. 
4. After allowing the next episode to play, the bars will show the background of the show's page in the app instead of being black.

### Application version

0.17.0-beta3

### Where did you install the app from?

Google Play

### Device information

CCwGTV

### Android version

current firmware

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment] 2024-07-17 06:45
Duplicate of #3728, already fixed in #3751 for next beta. Thanks for reporting!

**Closed by nielsvanvelzen** 2024-07-17 06:45 UTC
Labels: bug
