### ISSUE TITLE
Folder View in Android Tv

### ISSUE THREAD

**Issue by DBX31** [jellyfin/jellyfin-androidtv#1606] opened 2022-04-03 10:23 UTC
Un### Describe the feature you'd like

Hi
Because I have a not regular organisation of my folder (movie are with movies an tv shiw), it is possible to include in main view the folder view? (Live web accec or mobile phone apps) ?

maybe, the best for me… is to have the possiblity to manage in the server (type  of mediateque)… select witch folder movies can be include a view a « tv show » view inside 😬

I'm clear 🤔???

Thanks 🙏
Regards
DBX

**Comment by sourpatched** [comment] 2022-04-03 23:31
Are you talking about a filter?
Your library have movies and tv shows together? and you want to only view one type at a time, this this what you're asking?

**Comment by DBX31** [comment] 2022-04-04 08:45
hi,

My organization of files:

In "mediateque", I have made one part "movies" with movies type of file.
My folder have inside (example): 

Children/Avatar/Avatar.mkv
Children/[Série]/Tex Avery/      ... (many many small files .mkv)....

This is my problem... When I use movie display, I don't see only the movies... I have all small movies....
Ok, it's normal because, for resolve this, it's necessary to indicate the foler "tex Avery" is like "TV Show"
My idea is indicate when I create the movie in mediateque setting, exclude some folder or indicate some folder like "TV Show"
.... so... I'm not sure to be clear ???

Regards
DBX

**Comment by nielsvanvelzen** [comment] 2022-04-04 09:21
Closing as duplicate of #700.

**Closed by nielsvanvelzen** 2022-04-04 09:21 UTC
Labels: enhancement
