### ISSUE TITLE
Able to select the quality

### ISSUE THREAD

**Issue by DKB0512** [jellyfin/jellyfin-androidtv#1088] opened 2021-08-14 18:27 UTC
The "Select Quality" Feature that Android and Desktop has right now will be very useful. If I have a movie with 3 qualities then I can't select which quality I want to play and it just gets the default one. Instead of this, it would be very helpful that we can choose either we want to play for example 720p or 1080p stream of the same show/movie.

**Comment by nielsvanvelzen** [comment] 2021-08-15 08:28
Duplicate of #685

**Closed by nielsvanvelzen** 2021-08-15 08:28 UTC
Labels: enhancement
