### ISSUE TITLE
On-screen LiveTV channels menu broken in 0.15.4

### ISSUE THREAD

**Issue by osscombat** [jellyfin/jellyfin-androidtv#2580] opened 2023-03-10 11:31 UTC
### Describe the bug

Hi,
Looks like it started in v0.15.4. When you call the LiveTV channles quick menu with the down arrow remote button, the channel list appears blinking, with defaulting to the first channel in the row. So it's practically unusable, as you can see on the attached video.

https://user-images.githubusercontent.com/30649369/224305243-ee9e1347-abe3-4429-b1f1-9aced51f8df9.mp4

### Application version

0.15.4

### Where did you install the app from?

Google Play

### Device information

Mi box S

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment] 2023-03-10 12:08
Closing as a duplicate of #2375, thanks for the video though that should help finding the issue.

**Closed by nielsvanvelzen** 2023-03-10 12:08 UTC
Labels: bug
