### ISSUE TITLE
请在二级目录下的海报墙下面显示标题

### ISSUE THREAD

**Issue by 275106590** [jellyfin/jellyfin-androidtv#3141] opened 2023-10-25 18:50 UTC
### Describe the feature you'd like

1.进入媒体库后海报墙下面没有标题，媒体库视频比较多的时候很难快速找到自己想看的视频
2.媒体库所有视频下面相同系列的电影应该增加:合集方式展现，比如我有007系列20部 每个单独显示太浪费空间 应该有以合集方式展现

**Comment by nielsvanvelzen** [comment] 2023-10-25 19:57
> **Please display the title under the poster wall in the secondary directory**
> 1. There is no title under the poster wall after entering the media library, it is hard to find the video you want to watch quickly when there are more videos in the media library.
> 2. The same series of movies under all the videos in the media library should be added: collection way to show, for example, I have 20 James Bond series, each individual display is too wasteful of space, should have a collection way to show

Closing as duplicate of #1778

**Closed by nielsvanvelzen** 2023-10-25 19:57 UTC
Labels: enhancement
