### ISSUE TITLE
Next episode with subtitles from previous

### ISSUE THREAD

**Issue by joaovitoriasilva** [jellyfin/jellyfin-androidtv#477] opened 2020-05-19 13:34 UTC
When seeing multiple episodes, imagine just finished the first episode and the second one starts automatically, the second episode uses the subtitles from the first episode. If I set the subtitles to off and then to ENG again, then it uses the correct subtitles.

**Comment by AndreasGB** [comment] 2020-05-26 18:40
Hi there, this seems to be a duplicate of #108, so I'll close this for now. If that is incorrect, feel free to reopen :)

**Closed by AndreasGB** 2020-05-26 18:40 UTC
Labels: bug
