### ISSUE TITLE
TV episodes repeat

### ISSUE THREAD

**Issue by FudgeSack** [jellyfin/jellyfin-androidtv#2426] opened 2023-01-17 04:12 UTC
### Describe the bug

When watching TV episodes from my server, the same episode plays over and over.

When an episode is almost finished "next up" shows the correct next episode but the episode that just finished plays again from the beginning.

I only have the issue on the android tv app.  Windows and web play proper next episode.  Does this on 3 different Nvidia Shields models.

### Application version

0.15.2

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield P2571 2015, Nvidia Shield Pro P2897 2017 and 2019 models

### Android version

11

### Jellyfin server version

10.8.8

**Comment by sledgeha1** [comment] 2023-01-19 15:33
Exact the same problem here on a Sony Android TV.

**Comment by reynn** [comment] 2023-01-22 00:50
Happening for me as well, TV and playlists, maybe just anything that does a "next up"

Jellyfin App Version: 0.15.2 release
Android TV OS: 10
Android TV Kernel: 4.19.75

**Comment by 7hr08ik** [comment] 2023-01-22 21:52
Same issue here. Multiple User accounts.

Android TV app
Jellyfin server on UnRaid

Even removed all my plugins, thinking Track or something was causing issues

**Comment by 7hr08ik** [comment] 2023-01-24 19:22
Hello,

After the 10.8.8 update the issue continues. Started on S03E02 watched > S03E04 then repeat of E04.
E03 + E04 where not updated with the watched status.

**Comment by HillBobby** [comment] 2023-01-25 17:27
Same issue. Just now was watching Seinfeld, S02E05. It tried to repeat it, so I skipped to E06, it played that and then tried to go back to E05 again. And yeah, E05 was not updated as "Watched" so maybe it not marking episodes as watched is what is causing it.
Sony Bravia 4K VH2 
Android 10,
Kernel 4.19.75 
Jellyfin App Version 0.15.2
Jellyfin Server Version 10.8.8 running on an Ubuntu Server VM.

**Comment by FudgeSack** [comment] 2023-01-27 02:57
So far this seems to be fixed in  0.15.3

Thanks to the devs

**Comment by HillBobby** [comment] 2023-01-27 15:34
Updated my app to 0.15.3 and immediately had it repeat again so no fix for me.

**Comment by Tumpo** [comment] 2023-01-29 15:32
I have this same problem happening sometimes. Restarting watching fixes problem for awhile.

**Comment by j-dasilva** [comment] 2023-02-06 18:27
Same problem.

**Comment by HillBobby** [comment] 2023-02-07 18:49
I checked the logs right after it happened again and didn't see anything about it. Activity log does log that playback stopped on the episode and then starts again on the episode.

I do have **a lot** of this in my logs though:
[WRN] Slow HTTP Response from "http://192.168.1.5:8096/Sessions/Playing/Progress" to "192.168.1.47" in 0:00:00.7087185 with Status Code 204

**Comment by notpatrickadams** [comment] 2023-02-09 02:20
Same issue here
Chromecast with Google TV on Jellyfin v0.15.3

**Comment by insignia96** [comment] 2023-02-10 05:10
I can also confirm the same bug. It has happened for me on two devices, on both v0.15.2 and v0.15.3
NVIDIA Shield TV 9.0.3
Sony TV BRAVIA 4K VH2 Android TV 10
Jellyfin Server Version 10.8.1

**Comment by 7hr08ik** [comment] 2023-02-10 11:05
This Issue persists.

Server Version: 10.8.9
Operating System: UnRaid / Docker

Client: Jellyfin for Android TV

Logs dont show anything.

**Comment by SouzaRDG** [comment] 2023-02-19 20:49
I'm having this issue on a firestick too.

Tested v0.15.3 with several server versions since 10.8 and the problem persists.
It seems to be the same problem as https://github.com/jellyfin/jellyfin-androidtv/issues/2378 

Since I have a small library, dindt tested it too much, only with series with 100+ episodes.

**Comment by GGProGaming** [comment] 2023-03-18 19:43
Same issue on Chromecast running GoogleTV. I get it when shuffle playing a tv show though.

**Comment by mikezila** [comment] 2023-04-16 16:10
Same issue. Everything looks correct (the right episode is shown as up next) but it just keeps playing the same episode over and over. What's more it get stuck on one episode, because if I hit the next button while it's playing it'll move to the next episode, but after that one is done it'll go back and start playing the stuck episode again, over and over.

**Comment by klueman** [comment] 2023-04-21 03:13
Same problem here. Episodes get "stuck", repeat endlessly, and even after hitting skip, it will return to the stuck episode after it plays the next one and continues to loop

**Comment by Tumpo** [comment] 2023-04-21 09:26
If you manually skip to next episode it works but if you let it skip itself, it just plays the first episode again which you watched first in that session.

**Comment by NightHammer1000** [comment] 2023-06-05 19:10
Can Confirm this. 
For me it only happens when jump to the next Episode manually before it finishes. Doing this will cause the Player to return to that Episode I was on every time the Episode ends.
Stopping and manually marking the causing Episode as watched fixes it.

**Comment by klueman** [comment] 2023-07-03 17:08
Still happening after recent update.

Not to be annoying, I know it's a small team, but is there any development on this? It's a pretty consistent issue, especially in my usecase, that I don't have with any other Jellyfin app except the AndroidTV one. Even an acknowledgement would nice.

Is there anything else I can do to help diagnose this? I'm not confident enough with Android development to try anything myself but this issue is so annoying I'll do whatever if it means being able to use Jellyfin on my Shield without this problem.

Something I've noticed is it happens routinely enough with certain series but never happens with others, and always happens with a playlist or use of shuffle. Something about the way it's handling certain data from Jellyfin or even filenames, maybe? Like if the data from show A follows a certain pattern, the issue does not present when watching the show in sequence. But if the data from show B is not following the same patterns, the issue happens when watching that show in sequence. Then, in the case of shuffling or a playlist that jumps between various shows or seasons, it inevitebtly hits some data from a certain show or episode with a different pattern or data, and that triggers the bug. I'm just blind guessing, but that's the pattern I've started to see.

Maybe there's a way to adjust info coming from Jellyfin so it will not trigger this bug in AndroidTV? Again, no other version of the Jellyfin app has this bug, I'd have to adjust Jellyfin metadata for this app alone, but I'm willing to do that.

**Comment by klueman** [comment] 2023-07-03 17:22
@NightHammer1000 That sounds like it might be a related but seperate issue. The issue described here is the opposite: during playback, an episode gets "stuck" in the autoplay next slot, and even though you can manually skip to the next episode, if you let autoplay move to the next episode, it will play that "stuck" episode, and continue to do it on a loop.

I've had this happen on episodes already marked watched and episodes marked as unwatched, that doesn't seem to make a difference.

**Comment by nielsvanvelzen** [comment] 2023-07-03 17:38
> Not to be annoying, I know it's a small team, but is there any development on this? It's a pretty consistent issue, especially in my usecase, that I don't have with any other Jellyfin app except the AndroidTV one. Even an acknowledgement would nice.

Well since you ask for it, it probably won't be the answer you want to hear but here we go:

I've spend multiple hours on this issue trying to reproduce it (without success) and looking trough the code to find possible issues (also without success). I'm using the app on a daily bases and the issue never appeared for me. I don't have a clue what could cause it. In the end I have other issues to work on too and the rewrite of the playback code which will also fix this issue (but will also take a lot of time).

**Comment by NightHammer1000** [comment] 2023-07-04 08:18
Strange. I have 5 Users on my Server. All of them have this Issue.

On thing we all have in common is that we use an FireTV 4K Max Stick.

**Comment by klueman** [comment] 2023-07-04 21:09
I can very reliably recrate the issue. I'm not sure exactly how to trigger it, but if I play enough episodes, it will happen for certain sooner or later. So what can I provide for you to help diagnose it? If for no other reason than to be sure the playback changes will solve it.

As far as I can tell, there are no avaialble logs from the app itself, only the Jellyfin logs that show the app calling for the same episodes over and over. Like I said, I only have a passing knoweldge of Android development, but I know my way around Android's file system and how to use ADB, so if there's some log or something hidden in there, I can pull it.

I can also set up Android Studio to maybe run some debugging, too, though I'm in the dark on how Gradle works.

**Comment by reynn** [comment] 2023-07-07 17:22
@nielsvanvelzen curious if you think somehow the server could be introducing the issue somehow? Interestingly sometimes I go a week or so and never get the issue then I'll get it after every 2-3 episodes of a TV show.

I run the server through a kubernetes pod on a dedicated media server.

**Comment by nielsvanvelzen** [comment] 2023-07-07 19:11
> @nielsvanvelzen curious if you think somehow the server could be introducing the issue somehow? Interestingly sometimes I go a week or so and never get the issue then I'll get it after every 2-3 episodes of a TV show.
> 
> I run the server through a kubernetes pod on a dedicated media server.

The issue is definitely within the client, the server setup might help reproducing the issue though. Perhaps it could be caused by a high latency/slow response on certain endpoints, which would mean the cause is a race condition.

**Comment by reynn** [comment] 2023-07-08 01:20
@nielsvanvelzen yeah sorry for not being more clear, I only meant server deployment not necessarily server code. I was thinking along the lines of latency issues as well.

**Comment by NightHammer1000** [comment] 2023-07-08 02:57
> > @nielsvanvelzen curious if you think somehow the server could be introducing the issue somehow? Interestingly sometimes I go a week or so and never get the issue then I'll get it after every 2-3 episodes of a TV show.
> > I run the server through a kubernetes pod on a dedicated media server.
> 
> The issue is definitely within the client, the server setup might help reproducing the issue though. Perhaps it could be caused by a high latency/slow response on certain endpoints, which would mean the cause is a race condition.

This could really be it. Most of my Library runs of an RClone Google Drive and I exclusivly notice this Issue with Series that are on there and not the local onces.

**Comment by jwynn6** [comment] 2023-08-15 11:09
I don't think it's a server issue. I have a Chromecast with multiple users and this issue only happens for one of them. It's the most recently created and is a heavily restricted user in terms of access to libraries and rated content.

**Comment by jwynn6** [comment] 2023-08-15 11:44
I don't think it's a server issue. I have a Chromecast with multiple jf users in the androidtv app and this issue only happens for one of them. It's the most recently created and is a heavily restricted user in terms of access to libraries and rated content.

**Comment by Kylar514** [comment] 2023-08-27 02:27
I am having this same issue.  I don't see anyone mentioning that the episode that finishes, and then repeats, is not getting marked as 'watched'.  It seems like Jellyfin is playing the next episode that is not marked as watched, and for some reason it is having a hard time marking the current episode as marked at the very end.  

This happens to me atleast 1x a day of watching, maybe 5-7 episodes?  (watching 20 min episodes of the nanny in the background lol).

I have just been backing out of the current glitched episode.  marking it as watched, backing out again, than the next episode that will show in my timeline to watch, will be the correct next episode.

**Comment by cheGGo** [comment] 2023-08-27 18:22
same issue here.
The transition screen for the "next episode" ist showing the correct next episode in watchlist but repeats the last viewed episode.

**Comment by francis2054** [comment] 2023-09-18 01:59
Same thing here still, fresh installation, Google TV chromecast

**Comment by witt0** [comment] 2023-11-19 15:57
I also have this issue.

**Application version**
0.15.12

**Where did you install the app from?**
Amazon Appstore

**Device information**
Amazon Fire Cube (2nd gen)

**Software Version**
Fire OS 7.6.6.4 (PS7664/3772)

**Fire TV Home Version**
6480055.1

**Jellyfin server version**
10.8.11

**OS**
Docker on Synology NAS

I have a folder containing 1000+ video files, they are all in a playlist, I shuffle play this playlist and the 1st video plays fine. The 2nd video plays fine, towards the end of 2nd video, it shows what the next video will be (something different), but the 2nd video is played instead, this 2nd video is played over and over. If you press next video button, it plays the one it said would be next, but once that is finished, it goes back to the 2nd video again and then repeats over and over.

This issue says logs are needed, I'm happy to provide them, I just don't know where to look.

**Comment by rmatte** [comment] 2023-11-25 22:11
Happening for me as well with the Android TV app, super annoying. Completely ruins the experience having to constantly watch for it looping. Can't just let it run through automatically like it should be able to.

**Comment by rmatte** [comment] 2023-11-26 23:42
I see comments that this needs logs but based on what I've personally seen this seems to very likely be some kind of client side issue with the Android app itself. I've never seen this looping while using jellyfin through a web browser. Not sure if there's some way to get logs from the android app? Maybe that feature needs to be added if it doesn't already exist? Something to send client logs back to the server side so that we can get to them from the admin interface?

**Comment by klueman** [comment] 2023-11-27 13:13
I asked a similar question a few months ago and have not gotten a response.

I can recreate this issue, routinely, but the app simply isn't logging or reporting enough information to the user to identify what's going wrong. That's why I asked if there was some hidden or inaccessible logs in the file system that could be reached by ADB. More baked in logging functions would be great but I think that's hitting the same wall where it would require the dev to devote time they don't seem to have to implement it.

That said, it's frustrating to have the issue so obvious and recurring, to want to help diagnose it, but have no means to.

**Comment by nielsvanvelzen** [comment] 2023-11-27 13:26
I've heard from multiple people this issue might be gone with 0.16. I'm not sure which change caused it and since I was never able to reproduce it I cannot say for sure that 0.16 does fix it. Please let me know if you encounter this issue with 0.16 (currently in Google Play beta or with sideloading only).

**Comment by nathangur** [comment] 2023-11-27 18:07
> I've heard from multiple people this issue might be gone with 0.16. I'm not sure which change caused it and since I was never able to reproduce it I cannot say for sure that 0.16 does fix it. Please let me know if you encounter this issue with 0.16 (currently in Google Play beta or with sideloading only).

I'm testing the Android TV beta, and I can confirm that this bug is gone in 0.16

**Comment by nielsvanvelzen** [comment] 2023-11-27 20:46
> I'm wondering if this commit had anything to do with fixing this...
> 
> [53b9218](https://github.com/jellyfin/jellyfin-androidtv/commit/53b92184a4e0fa38907d03ca89cda1facdc32713)

This change is in 0.15.7 and newer and all 0.16 beta releases and is related to track selection according to the pull request #2692. So unlikely to be the cause or fix of this issue.

**Comment by rmatte** [comment] 2023-11-27 21:23
I just grabbed the beta, will run with it for a few days to confirm that it resolves the issue for me as well.

**Comment by rmatte** [comment] 2023-12-08 17:29
After using the beta for a while I can confirm that it resolves the looping issue for me and also seems just more stable and performant in general. Thanks.

**Closed** 2023-12-08 17:54 UTC
Labels: bug, needs-logs

**Comment by maester-of-bots** [comment] 2024-02-11 16:05
I'm still having this issue even after updating to the latest version.

**Comment by nielsvanvelzen** [comment] 2024-02-11 21:26
> I'm still having this issue even after updating to the latest version.

Are you using 0.16.4?

**Comment by fpytloun** [comment] 2024-05-03 15:54
Same issue here, using Infuse on AppleTV.

**Comment by somethingstarted** [comment] 2025-02-04 04:02
happens too. we're using it on the browser and are hosting it on windows 10(win server 22)

**Comment by maester-of-bots** [comment] 2025-02-04 21:58
> > I'm still having this issue even after updating to the latest version.
> 
> Are you using 0.16.4?

Looks like I'm on 10.9.11, so I might be looking at something different from you...but I'm also thrilled to say that this no longer happens for me!!
