### ISSUE TITLE
External Subtitles Are No Longer Shared With External Player.

### ISSUE THREAD

**Issue by jaytrinitron** [jellyfin/jellyfin-androidtv#4342] opened 2024-12-25 02:54 UTC
### Describe the bug

If using an external player like justplayer or kodi, the external subtitle file with the same name as the media filename no longer gets shared to the external player. This used to work just a few weeks ago but no longer works on android app 0.18.2. Tested on multiple files.

### Application version

0.18.2

### Device information

Sony BRAVIA 4K VH22

### Android version

Android 10, Sony Firmware v6.7612

### Jellyfin server version

10.10.3

**Comment by thornbill** [comment] 2024-12-25 04:26
Duplicate of #4310

**Closed** 2024-12-25 04:26 UTC
Labels: bug, duplicate, playback
