### ISSUE TITLE
TV show theme support

### ISSUE THREAD

**Issue by dasfuu** [jellyfin/jellyfin-androidtv#2872] opened 2023-07-05 08:57 UTC
### Describe the feature you'd like

I would like to have support for the tv show theme on androidtv too.

Kinda related: Do you accept (bug) bounties?

**Comment by nielsvanvelzen** [comment] 2023-07-05 12:57
Closing as a duplicate of #1150.

> Kinda related: Do you accept (bug) bounties?

No, but you can always [sponsor me](https://github.com/sponsors/nielsvanvelzen) if you appreciate my work on the app.

**Closed by nielsvanvelzen** 2023-07-05 12:57 UTC
Labels: enhancement
