### ISSUE TITLE
Cant open movie libary on FireTv Stick

### ISSUE THREAD

**Issue by NextGen77** [jellyfin/jellyfin-androidtv#2182] opened 2022-10-15 22:31 UTC
### Describe the bug

1. Open Jellyfin App on FireTv Stick
2. Open my movie libary
3. Get informed what the crash report was saved
4. Jellyfin app automaticly closed

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: this.type must not be null
	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:431)
	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:321)
	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:93)
	at org.jellyfin.androidtv.util.ImageUtils.getPrimaryImageUrl(ImageUtils.java:125)
	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.getPrimaryImageUrl(BaseRowItem.java:239)
	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.getImageUrl(BaseRowItem.java:227)
	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:435)
	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1118)
	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1646)
	at androidx.leanback.widget.StaggeredGrid.appendVisibleItemToRow(StaggeredGrid.java:388)
	at androidx.leanback.widget.StaggeredGridDefault.appendVisibleItemsWithoutCache(StaggeredGridDefault.java:300)
	at androidx.leanback.widget.StaggeredGrid.appendVisibleItems(StaggeredGrid.java:281)
	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028)
	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
	at android.view.Choreographer.doFrame(Choreographer.java:620)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

```  
***Logcat***: 
```log
--------- beginning of main
10-16 00:13:24.375 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:24.392 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:24.408 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:24.424 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:24.762 I/art     (22827): Background partial concurrent mark sweep GC freed 27337(1808KB) AllocSpace objects, 7(536KB) LOS objects, 6% free, 53MB/57MB, paused 1.267ms total 101.594ms
10-16 00:13:26.445 I/AuthenticatedUserCallba(22827): Activity org.jellyfin.androidtv.ui.startup.StartupActivity is ignored
10-16 00:13:26.446 I/AppThemeCallbacks(22827): Applying theme: DARK
10-16 00:13:26.458 I/BackgroundService(22827): Adding BackgroundServiceFragment to activity
10-16 00:13:26.493 I/MediaManager(22827): Firing queue state change listener. false
10-16 00:13:26.612 E/ThemeUtils(22827): View class androidx.appcompat.widget.AppCompatButton is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:26.626 E/ThemeUtils(22827): View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:26.645 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.ExpandableTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:26.686 I/KtorClient(22827): GET http://192.168.0.222:8096/Users/Public
10-16 00:13:26.703 I/KtorClient(22827): GET http://192.168.0.222:8096/Branding/Configuration
10-16 00:13:26.736 I/KtorClient(22827): GET http://192.168.0.222:8096/Users/Public
10-16 00:13:26.782 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:26.795 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:26.811 W/OpenGLRenderer(22827): Points are too far apart 4.000003
10-16 00:13:26.858 I/KtorClient(22827): GET http://192.168.0.222:8096/System/Info/Public
10-16 00:13:26.979 I/art     (22827): Background partial concurrent mark sweep GC freed 41623(3MB) AllocSpace objects, 4(3MB) LOS objects, 7% free, 51MB/55MB, paused 1.759ms total 106.894ms
10-16 00:13:27.938 I/KtorClient(22827): GET http://192.168.0.222:8096/Users/Me
10-16 00:13:27.961 I/KtorClient(22827): GET http://192.168.0.222:8096/DisplayPreferences/livetv?userId=97f0499b-20c5-4bd5-b626-c89c15494924&client=jellyfin-androidtv
10-16 00:13:27.984 I/KtorClient(22827): GET http://192.168.0.222:8096/DisplayPreferences/usersettings?userId=97f0499b-20c5-4bd5-b626-c89c15494924&client=emby
10-16 00:13:28.009 I/StartupActivity$onPermi(22827): Found a session in the session repository, waiting for the currentUser in the application class.
10-16 00:13:28.011 I/StartupActivity$onPermi(22827): CurrentUser changed to 97f0499b-20c5-4bd5-b626-c89c15494924 while waiting for startup.
10-16 00:13:28.016 I/KtorClient(22827): POST http://192.168.0.222:8096/Sessions/Capabilities?playableMediaTypes=Video%2CAudio&supportedCommands=DisplayMessage%2CSendString&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
10-16 00:13:28.025 I/KtorClient(22827): GET http://192.168.0.222:8096/Users/Me
10-16 00:13:28.056 I/KtorClient(22827): GET http://192.168.0.222:8096/Playback/BitrateTest?size=4000000
10-16 00:13:28.088 W/OpenGLRenderer(22827): Points are too far apart 4.000003
10-16 00:13:28.098 I/WM-WorkerWrapper(22827): Worker result FAILURE for Work [ id=fca2f6f2-1eec-42a3-83ae-11b0729658c0, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
10-16 00:13:28.181 I/AppThemeCallbacks(22827): Applying theme: DARK
10-16 00:13:28.195 I/BackgroundService(22827): Adding BackgroundServiceFragment to activity
10-16 00:13:28.212 I/BackgroundService(22827): Adding BackgroundServiceFragment to activity
10-16 00:13:28.222 I/HomeFragment(22827): Updating audio queue in HomeFragment (onResume)
10-16 00:13:28.230 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/LiveTv/Programs/Recommended?Limit=1&UserId=97f0499b-20c5-4bd5-b626-c89c15494924&IsAiring=true&EnableTotalRecordCount=false&ImageTypeLimit=1&format=json
10-16 00:13:28.271 W/OpenGLRenderer(22827): Points are too far apart 4.000003
10-16 00:13:28.282 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Views?format=json
10-16 00:13:28.368 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items?Filters=IsResumable&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&ExcludeLocationTypes=Virtual&SortBy=DatePlayed&MediaTypes=Audio&EnableTotalRecordCount=false&recursive=true&Limit=50&format=json
10-16 00:13:28.368 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items?Filters=IsResumable&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&ExcludeLocationTypes=Virtual&SortBy=DatePlayed&MediaTypes=Video&EnableTotalRecordCount=false&recursive=true&Limit=50&format=json
10-16 00:13:28.387 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Views?format=json
10-16 00:13:28.397 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.424 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.437 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.449 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.468 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=7a2175bccb1f1a94152cbd2b2bae8f6d&GroupItems=true&format=json
10-16 00:13:28.487 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=be9cf652bb84e1aad118cb9bfc5fdf54&GroupItems=true&format=json
10-16 00:13:28.506 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.521 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.534 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.549 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.562 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.574 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.587 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.599 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.612 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.626 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.638 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.650 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.663 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.676 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.689 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.701 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.714 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.727 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.753 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=f68afde20073191efc6792df0803cfa6&GroupItems=true&format=json
10-16 00:13:28.756 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=a41169fa9ec7dd1ecc27162e3798fee1&GroupItems=true&format=json
10-16 00:13:28.758 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Shows/NextUp?Limit=50&UserId=97f0499b-20c5-4bd5-b626-c89c15494924&ImageTypeLimit=1&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&format=json
10-16 00:13:28.759 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=43cfe12fe7d9d8d21251e0964e0232e2&GroupItems=true&format=json
10-16 00:13:28.767 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items/Latest?Limit=50&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&ParentId=8a05b0252259a1dbd62df97522638439&GroupItems=true&format=json
10-16 00:13:28.782 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.802 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.820 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.834 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.855 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.870 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.884 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.926 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.942 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.955 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.968 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.981 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:28.994 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.007 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.020 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.033 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.050 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.072 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.085 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:29.563 I/AutoBitrate(22827): Auto bitrate set to: 21234240
10-16 00:13:30.249 I/KtorClient(22827): GET http://192.168.0.222:8096/DisplayPreferences/be9cf652bb84e1aad118cb9bfc5fdf54?userId=97f0499b-20c5-4bd5-b626-c89c15494924&client=jellyfin-androidtv
10-16 00:13:30.342 I/AppThemeCallbacks(22827): Applying theme: DARK
10-16 00:13:30.358 I/BackgroundService(22827): Adding BackgroundServiceFragment to activity
10-16 00:13:30.375 I/art     (22827): Do partial code cache collection, code=20KB, data=26KB
10-16 00:13:30.377 I/art     (22827): After code cache collection, code=20KB, data=26KB
10-16 00:13:30.377 I/art     (22827): Increasing code cache capacity to 128KB
10-16 00:13:30.454 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:30.535 I/jellyfin-apiclient(22827): Response received from: http://192.168.0.222:8096/Users/97f0499b-20c5-4bd5-b626-c89c15494924/Items?Fields=PrimaryImageAspectRatio%2CChildCount%2CMediaSources%2CMediaStreams%2CDisplayPreferencesId&recursive=true&sortOrder=Ascending&Limit=36&SortBy=SortName&IncludeItemTypes=Movie&ParentId=be9cf652-bb84-e1aa-d118-cb9bfc5fdf54&format=json
10-16 00:13:30.579 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:30.596 E/ThemeUtils(22827): View class org.jellyfin.androidtv.ui.AsyncImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
10-16 00:13:30.607 E/ACRA    (22827): ACRA caught a NullPointerException for org.jellyfin.androidtv
10-16 00:13:30.607 E/ACRA    (22827): java.lang.NullPointerException: this.type must not be null
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:431)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:321)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.util.sdk.compat.ModelCompat.asSdk(ModelCompat.kt:93)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.util.ImageUtils.getPrimaryImageUrl(ImageUtils.java:125)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.getPrimaryImageUrl(BaseRowItem.java:239)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.ui.itemhandling.BaseRowItem.getImageUrl(BaseRowItem.java:227)
10-16 00:13:30.607 E/ACRA    (22827): 	at org.jellyfin.androidtv.ui.presentation.CardPresenter.onBindViewHolder(CardPresenter.java:435)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:1118)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1646)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.StaggeredGrid.appendVisibleItemToRow(StaggeredGrid.java:388)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.StaggeredGridDefault.appendVisibleItemsWithoutCache(StaggeredGridDefault.java:300)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.StaggeredGrid.appendVisibleItems(StaggeredGrid.java:281)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1870)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2303)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028)
10-16 00:13:30.607 E/ACRA    (22827): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:878)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.view.Choreographer.doFrame(Choreographer.java:620)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:864)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.os.Handler.handleCallback(Handler.java:751)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.os.Looper.loop(Looper.java:154)
10-16 00:13:30.607 E/ACRA    (22827): 	at android.app.ActivityThread.main(ActivityThread.java:6194)
10-16 00:13:30.607 E/ACRA    (22827): 	at java.lang.reflect.Method.invoke(Native Method)
10-16 00:13:30.607 E/ACRA    (22827): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
10-16 00:13:30.607 E/ACRA    (22827): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

```  

### App information

***App version***: `0.14.3` (`140399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mantis","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"mantis","DISPLAY":"NS6292","FINGERPRINT":"Amazon\/mantis\/mantis:6.0\/NS6292\/4226N:user\/amz-p,release-keys","HARDWARE":"mt8695","HOST":"i3-ri-14-use1a-b-16-04-fos-113","ID":"NS6292","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTMM","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"mantis","RADIO":"unknown","REQ_BATTERY_LEVEL":0.3,"SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1663375877000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"NHG47K","CODENAME":"REL","INCREMENTAL":"0008020591236","PREVIEW_SDK_INT":0,"RELEASE":"7.1.2","RESOURCES_SDK_INT":25,"SDK":"25","SDK_INT":25,"SECURITY_PATCH":"2022-01-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140399,"VERSION_NAME":"0.14.3"}
```  

### Device information

***Android version***: `7.1.2`  
***Device brand***: `Amazon`  
***Device product***: `mantis`  
***Device model***: `AFTMM`  

### Crash information

***Start time***: `2022-10-14T23:43:30.808+02:00`  
***Crash time***: `2022-10-16T00:13:30.675+02:00`  

### Application version

0.14.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Tv Stick 4k Ultra HD with Alexa

### Android version

7.1.2

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment] 2022-10-16 07:45
Duplicate of #2125. This issue is already fixed in the latest version. Update your app or downgrade your server.

**Closed by nielsvanvelzen** 2022-10-16 07:45 UTC
Labels: bug

**Comment by NextGen77** [comment] 2022-10-16 10:28
Thank you for the fast feedback.
Unfortunately there is no newer version in the App Store than 0.14.3
Is there another way to update the app?

**Comment by nielsvanvelzen** [comment] 2022-10-16 10:33
You can sideload the latest version, but that means you won't get newer updates automatically. Unfortunately Amazon is really slow with publishing, we submitted the app for review almost two weeks ago.
