### ISSUE TITLE
When unchecked, the "Show next video info during playback" option for user playback does not apply during Android TV playback.

### ISSUE THREAD

**Issue by LucasCrowe** [jellyfin/jellyfin-androidtv#1131] opened 2021-09-06 18:15 UTC
**Describe the feature you'd like**	
When unchecked, the "Show next video info during playback" option for user playback does not apply during Android TV playback. This is particularly disruptive when the individual episodes do not have credits.

**Additional context**

**Comment by nielsvanvelzen** [comment] 2021-09-06 18:23
Duplicate of #1130

**Closed by nielsvanvelzen** 2021-09-06 18:23 UTC
Labels: enhancement

**Comment by LucasCrowe** [comment] 2021-09-06 18:44
It's not a duplicate. This is an enhancement request. The other is a bug request.
