### ISSUE TITLE
Live Tv quick menu

### ISSUE THREAD

**Issue by DaOsmo76** [jellyfin/jellyfin-androidtv#2375] opened 2022-12-30 08:33 UTC
### Describe the bug

Quick menu to change channel (pressing down on the remote) the menu shows but is blinking and one cant navigate to a other channel.
Regardless choosen channel the quick menu for changing channel, it jumps back to first channel in quick menu so if you are at channel 35 it starts at channel 1.

Uninstall and install 0.14.5 it works again until it auto update. 

### Application version

0.15 test 0.15.3 same issue

### Where did you install the app from?

Google Play

### Device information

Chromecast TV and Philips android tv 

### Android version

Android 12 Android 11

### Jellyfin server version

10.8.8

**Comment by DaOsmo76** [comment] 2023-01-25 15:16
Reinstalled version 014.5 and changing channel with quick menu works.

**Comment by Mavyre** [comment] 2023-02-02 09:29
Good to know that 0.14.5 works better. Additionnally, TV channels that don't have any guide data don't have this issue. Only channels with Guide data have that blinking behaviour.

**Comment by anthonylavado** [comment] 2023-02-10 21:31
Hrm. I'm using 15.3 on a Chromecast with Google TV and I'm not experiencing this. All 12 Live TV channels have full guide data from the antenna as well.

**Comment by nielsvanvelzen** [comment] 2023-03-10 20:39
I also cannot reproduce this issue. If someone experiencing the bug wants to share some client logs we can look further into the issue.

**Comment by Mavyre** [comment] 2023-03-11 13:18
How may we share those logs? I couldn't find them and that may help us track down more issues!

**Comment by nielsvanvelzen** [comment] 2023-03-11 13:19
You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat. Make sure to reproduce the issue just before getting the logs.

**Comment by helptiger** [comment] 2023-03-26 11:14
The problem is reproducible for me when playback is selected via vlclib. With selection exoplayer it does not occur. Alternatively, it works when playback is paused.

**Comment by nielsvanvelzen** [comment] 2023-03-26 13:18
Still unable to reproduce with the live tv video player set to always use LibVLC.

**Comment by Ritchie1108** [comment] 2023-07-12 06:27
have the same problem with selection exoplayer
using ccwgtv 4k

**Comment by osscombat** [comment] 2023-07-17 14:42
> You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat. Make sure to reproduce the issue just before getting the logs.

So the logs are necessary to fix this issue? That manual from LineageOS is quite obscure, are there more precise steps on what to do on the androidTV box to grab them?

**Comment by nielsvanvelzen** [comment] 2023-07-17 16:58
Not particularly necessary but they might help. I need as much information as possible so I can reproduce/understand the issue. With the current info I have not been able to find it and thus unable to make a fix.

**Comment by osscombat** [comment] 2023-07-18 15:03
> Not particularly necessary but they might help. I need as much information as possible so I can reproduce/understand the issue. With the current info I have not been able to find it and thus unable to make a fix.

Here is the log by logcat, capturing the moment when the quick channels menu being called. This is in the very end of it, and I stopped logging after that...

[logcat.log](https://github.com/jellyfin/jellyfin-androidtv/files/12082059/logcat.log)

**Comment by Mavyre** [comment] 2023-11-16 05:01
Still an issue

**Comment by carfanatic93** [comment] 2024-04-18 16:46
Same issue here. VLCLlib, Nvidia Shield.

**Comment by nielsvanvelzen** [comment] 2024-04-18 17:32
Is anyone able to share a screen recording of this issue? Perhaps this could help figure out the problem.

**Comment by osscombat** [comment] 2024-04-18 19:14
> Is anyone able to share a screen recording of this issue? Perhaps this could help figure out the problem.

Already uploaded it [here](https://github.com/jellyfin/jellyfin-androidtv/issues/2580)

**Comment by nielsvanvelzen** [comment] 2024-04-18 19:21
> > Is anyone able to share a screen recording of this issue? Perhaps this could help figure out the problem.
> 
> Already uploaded it [here](https://github.com/jellyfin/jellyfin-androidtv/issues/2580)

Thank you. I digged through the code earlier and found one specific code path that might cause this behavior and looking at the video helped me confirm this suspicion.

I've made a potential fix in #3522. Could you sideload this to your device and verify it works?

You can download the app from this page: https://github.com/jellyfin/jellyfin-androidtv/actions/runs/8742457676?pr=3522. Scroll down and click on "build-artifacts". The zip file contains an .apk file that you want to install on your device.

**Comment by DaOsmo76** [comment] 2024-04-18 19:42
I just tried it.
Menu dont blink for me anymore. But quick menu entry jumps to first channel.

Cant use exoplayer have to use libvlc.

**Comment by osscombat** [comment] 2024-04-18 19:51
Great! It's not blinking anymore in the debug version, with libVLC - ExoPlayer totally fails the playback. Tested on mi box s.

**Comment by nielsvanvelzen** [comment] 2024-04-18 20:06
Thanks for confirming, I'm glad we've finally been able to solve this problem. The fix will be released in 0.16.9 which should be published in the coming days/week.

**Closed** 2024-04-18 20:12 UTC
Labels: bug, confirmed, live-tv

**Comment by helptiger** [comment] 2024-04-26 09:24
Unfortunately, the problem with version 0.16.10 has not yet been completely resolved. It occurred again with the new version. However, as some channels no longer start at all with this version (player error), I have not tested it any further.
I assume that other users will now also report this. In my opinion, the patch has not completely solved the problem and has caused new playback issues.

**Comment by osscombat** [comment] 2024-04-26 11:51
For me this issue is resolved with 0.16.10. No other new issues with playback etc. noticed.

**Comment by nielsvanvelzen** [comment] 2024-04-26 16:33
If you still experience this problem, please open a new issue with as much detail as possible. Do make sure both your app and server are up-to-date.
