### ISSUE TITLE
In App Volume Control

### ISSUE THREAD

**Issue by Phoenix-004** [jellyfin/jellyfin-androidtv#1250] opened 2021-11-15 01:57 UTC
### Describe the feature you'd like

Ability to control media volume from within the app and have the volume localized to the app. An example of this is with Kodi. There, You can have your TV volume set at whatever you want but still have control of the media volume within Kodi.

So this would have Up/Down keys on the remote contlVolume Up and down, right and left keys control seek forward or back. OK/Centre key brings up the Media OSD in which case all aro keys go back to their current navigation functions.

**Comment by nielsvanvelzen** [comment] 2021-11-15 08:38
Duplicate of #867

**Closed** 2021-11-15 08:38 UTC
Labels: duplicate, enhancement
