### ISSUE TITLE
Continue Watching now working 

### ISSUE THREAD

**Issue by Sergiomg86** [jellyfin/jellyfin-androidtv#3503] opened 2024-04-11 14:22 UTC
### Describe the bug

Go to Continue Watching in homescreen
Clic on video for continue
not working

I have a strange error where playback does not continue on my SmartTV using the official Google Play application.

For example, if I watch an episode of a series with a total duration of 1 hour and I watch a total of 30 and I come back the next day... it does not play where I left it, it starts from the beginning.

Does anyone know what can happen and how I can fix it?

Thank you!

### Application version

0.16.7

### Where did you install the app from?

Google Play

### Device information

Xiaomi MI TV Box S

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by Sergiomg86** [comment] 2024-04-11 16:23
The problem is that I finish watching something and it doesn't automatically go to "continue watching" unless I exit the app.

I have reinstalled the app and restarted the device.

I'm trying an option that says "enable reactive home page" to see if that fixes it.

**Comment by nielsvanvelzen** [comment] 2024-04-11 17:08
Closing as duplicate of [this forum topic](https://forum.jellyfin.org/t-error-continuing-transmission).

**Closed by nielsvanvelzen** 2024-04-11 17:08 UTC
Labels: bug
