### ISSUE TITLE
FireTV episodes end abruptly

### ISSUE THREAD

**Issue by buzzkillingtonne** [jellyfin/jellyfin-androidtv#1339] opened 2022-01-08 23:57 UTC
### Describe the bug

With or without "Queue all subsequent episodes" enabled...
1. Go to a TV show, open and episode and play it with either libvlc, exo player, vlc, mxplayer, or kodi.
2.  Wait a few minutes until playback fails, it will either attempt to play the next episode or end entirely depending on the setting I mentioned above

I expect the videos to play through to their end.

### Logs

I uploaded the log file from adb logcat due to the length being too long for here and pastebin.
[logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7834229/logcat.txt)

### Application version

0.12.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV

### Android version

Fire OS 6.2.8.1

### Jellyfin server version

10.8 alpha5 (happened on 10.7.7 too)

**Comment by mueslimak3r** [comment] 2022-01-09 09:46
That log doesn't contain any of the normal debug logging from the jellyfin app. You may need to either enable debug mode in the app's settings or side load the debug apk from the releases page on this repo

**Comment by TheHellSite** [comment] 2022-01-09 21:08
I am having the same issue. I first thought it was related to the max streaming bitrate, but at this moment it doesn't matter which settings are set. It will stop either directly at the beginning or during a playback.

https://github.com/jellyfin/jellyfin-androidtv/issues/1227

**Comment by Bandid0** [comment] 2022-01-10 04:22
I am having the same issue.

**Comment by buzzkillingtonne** [comment] 2022-01-11 05:54
I sideloaded the debug apk from the repo and tested playback in it, it did not break like the regular app.

I checked the logcat while playing video in the debug app and found nothing different from my logs I posted. This got me thinking that if what you're expecting isn't in the logs then it can't be a jellyfin issue....

I then uninstalled and reinstalled the Jellyfin app from the Amazon store on my FireTV and the issue stopped occuring... for about 30 minutes.

Now it just outright crashes comming up with the crash report screen. (both in the regular app and the debug app). Here is the newest logcat. I ran this with the command: adb logcat -d > logcat.txt
[logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7844003/logcat.txt)

I'm so far it only crashes with that one episode, so I think that this is likely a different problem all together. If so I will close this sisue and open a different one.

**Comment by Mettchen** [comment] 2022-01-21 01:21
Having the same issue on Chromecast with Google TV. However only using LibVLC not using Exoplayer.
Running JF 10.7.2

**Comment by GerardGarcia** [comment] 2022-01-24 14:56
Same here on Chromecast with Google TV, running  `10.8.0.alpha5.r63.gcd4587b43f-1` (jellyfin-git arch linux pacakge). I haven't been able to find anything interesting in the logs.

**Comment by Mettchen** [comment] 2022-02-01 20:49
Currently **not** experiencing the issue in 0.13.0-beta.1

**Comment by mueslimak3r** [comment] 2022-02-21 12:00
Is anyone seeing this issue in the latest beta?

If it happens while transcoding and using libVLC, it may be related to this server-side bug:
https://github.com/jellyfin/jellyfin/issues/6957

**Comment by buzzkillingtonne** [comment] 2022-02-22 02:22
Ill have to take another look at it and see, but im willing to bet that it is likely the same issue.

For me it happens for sure in libvlc and exoplayer, i haven't tried the latest beta on the firetv, but i have tried with server versions 10.7.7 and 10.8.

**Comment by mueslimak3r** [comment] 2022-02-27 12:39
Marked this as confirmed again because this issue can be reproduced specifically with libVLC when transcoding

**Comment by shaino** [comment] 2022-02-28 03:23
It should be libVLC playing issue.
Android 5.1.1/7/9 system playback with libVLC is the same issue in Ver0.13 beta4.
Playback crashes occur after the server has completed the full video transcoding.
Enabling PGS subtitles or not is independent of this issue.
I have enabled limit transcoding speed in the console. Unfortunately, when the client plays anywhere, the server continues to transcode to the end.Then issues appeared.Curiously, with exoplayer playback, the server will also transcode the full video, but it will not trigger the issue.

**Comment by Mettchen** [comment] 2022-03-13 15:35
Started experiencing this again using LibVLC, server 10.7.7, and beta 5.
Expected to be connected to HLS from https://github.com/jellyfin/jellyfin-androidtv/issues/1239 ?

**Comment by mueslimak3r** [comment] 2022-03-13 16:59
> Started experiencing this again using LibVLC, server 10.7.7, and 0.1.13 beta 5.
> Expected to be connected to HLS from https://github.com/jellyfin/jellyfin-androidtv/issues/1239 ?

Yeah, I think so

**Comment by buzzkillingtonne** [comment] 2022-04-29 20:15
So far it looks like this was fixed, so I'm closing it.

**Closed** 2022-04-29 20:15 UTC
Labels: bug, playback, confirmed
