### ISSUE TITLE
v0.12.0-beta.4: Authentication: Disabling of "Automatic sign in" does not re-prompt for password

### ISSUE THREAD

**Issue by hashnag** [jellyfin/jellyfin-androidtv#1058] opened 2021-08-01 11:04 UTC
Issue: The options(s) to disable "Automatic sign in" do not work.

Steps required to reproduce: Simply try to disable "Automatic sign in".

Work around: Roll back to v0.11.5.

Long version:
No matter what I set as my options under Authentication the most recent user is automatically signed when the application starts.

In fact the only way I've been able to get beta 2 to prompt me for any password is by fully uninstalling the Jellyfin ATV app (simply clearing data from ATV settings doesn't do it). Having removed the app the next time I launch I will be prompted for the password and thereafter it will automatically sign in as the most recently signed in user.

As an aside, there seems to be no more option for pin based login or the fancy d-pad option. I sure hope those are coming back.

Thanks!

**Comment by nielsvanvelzen** [comment] 2021-08-01 12:18
I can't reproduce this. When changing Settings -> Authentication Settings -> Automatic sign in to "Disable" and restarting the app I need to select my user again like expected.

![image](https://user-images.githubusercontent.com/2305178/127770568-25e31e95-6529-4ba0-8ca9-17a114c8e9c9.png)

**Comment by hashnag** [comment] 2021-08-01 12:22
Huh. Using the most recent v0.12.0-beta.2?

**Comment by eglia** [comment] 2021-08-01 12:31
I see the same behaviour in the debug beta2 build. When force-closing the app, the login window is shown, but when simply exiting the app by pressing back, the last user is automatically logged in.
Hardware is Nvidia Shield.

Another point I noticed is that the username of the current user is no longer shown. In the previous version this was displayed in the corner by the clock.

**Comment by nielsvanvelzen** [comment] 2021-08-01 12:57
> Huh. Using the most recent v0.12.0-beta.2?

Yes

> when simply exiting the app by pressing back, the last user is automatically logged in.

Going back doesn't close the app, it only hides it. So that's why it doesn't work in this case.

> In the previous version this was displayed in the corner by the clock.

We removed that as it didn't fit in the current user interface, we might add the name back in the future.

**Comment by nielsvanvelzen** [comment] 2021-08-01 13:04
I've made a change to fix "when simply exiting the app by pressing back, the last user is automatically logged in." in #1059, which will be in the next beta/release.

**Comment by hashnag** [comment] 2021-08-01 13:11
@nielsvanvelzen 
Great. I'll look forward to testing it. I appreciate all the hard work and polish going into this.

**Comment by hashnag** [comment] 2021-08-10 15:12
Still having the same issue. Sorry about the horrible video, but I figured it might be the best way to show what I'm getting.

**Comment by hashnag** [comment] 2021-08-11 02:27
Still seeing the same issue with disabling of Automatic sign in now working. Just to make sure it's not just on soft-close I've been doing a force stop through ATV settings. Prior to installing the beta I've done an uninstall.  

https://user-images.githubusercontent.com/88272316/128960238-0baa1515-36e5-413b-b465-2b4cc442708b.mp4

**Comment by nielsvanvelzen** [comment] 2021-08-11 07:00
Your video shows the login screen once opening the app again so that works as expected.

**Comment by hashnag** [comment] 2021-08-11 07:04
Sure. But after entering your password the first time it never prompts you again unless I manually log out by going to server settings.

So yes, I do get the login screen, however I'm still not prompted to authenticate.

**Comment by nielsvanvelzen** [comment] 2021-08-11 07:07
That is intended. Authentication tokens are stored in the Android Account manager and you need to explicitly sign out your account in the app settings. The "automatic sign in" feature just means the account to automatically open on app-start.

**Comment by hashnag** [comment] 2021-08-11 07:11
I see. So this is a departure from the previous version.

Having kids this feature would be problematic. Is this something I should write up as a feature request and close out as a bug?

**Comment by nielsvanvelzen** [comment] 2021-08-11 07:22
It would be a feature request since the current behavior is intended

**Comment by hashnag** [comment] 2021-08-11 07:24
Okay. Thanks.

**Closed** 2021-08-11 07:24 UTC
Labels: bug
