### ISSUE TITLE
"Latest TV Shows" section sometimes shows episode thumbnail instead of tv show poster

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#2528] opened 2023-02-22 04:12 UTC
### Describe the bug

Not much more to add to the title. Sometimes instead of seeing a vertically oriented poster image I see a horizontally oriented thumbnail from the episode itself. I checked in the desktop app and the web app and this issue is specific to jellyfin androidtv.

Edit: I tested this on an androidtv device that has gapps installed and the issue persists there as well.

### Application version

0.15.3

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield 2015

### Android version

LineageOS for microG [foster]

### Jellyfin server version

10.8.9

**Comment by thornbill** [comment] 2023-02-23 03:40
Duplicate of #1294

**Closed** 2023-02-23 03:41 UTC
Labels: bug, duplicate
