### ISSUE TITLE
0.17.x lost the subtitles time shift functionnality

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-androidtv#3883] opened 2024-08-11 20:57 UTC
### Describe the feature you'd like

It is not possible anymore to shift the subtitles when their are out-of-sync.
Can it be bring back ?

**Comment by nielsvanvelzen** [comment] 2024-08-12 06:48
The subtitle delay option was only ever implemented for the experimental LibVLC integration. So it is no longer available. Closing as duplicate of #2479

**Closed by nielsvanvelzen** 2024-08-12 06:48 UTC
Labels: enhancement
