### ISSUE TITLE
My media (small) section showing as full size My Media section

### ISSUE THREAD

**Issue by justinbyoung** [jellyfin/jellyfin-androidtv#2012] opened 2022-08-27 09:13 UTC
### Describe the bug

Trying to set My media (small) as a section on the Home screen. From the description I expect to get a smaller text only buttons.

Preferences > Customization > Home. Selected My media (small) as Home section 1. It is displayed on the Home page as full size My Media, there is no visible difference between the two options.

I get the same result on two different devices.

### Application version

0.14.2

### Where did you install the app from?

Google Play

### Device information

NVidia Shield TV 2017

### Android version

Android TV 11

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment] 2022-08-27 09:24
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed by nielsvanvelzen** 2022-08-27 09:24 UTC
Labels: bug
