### ISSUE TITLE
[FIRE TV APP] My Media Section 

### ISSUE THREAD

**Issue by TheBobBelcher** [jellyfin/jellyfin-androidtv#2325] opened 2022-12-08 17:50 UTC
### Describe the bug

My Media (small) isnt working and shows the normal My Media 

same issue with v0.15.0-beta.3

### Application version

0.14.5

### Where did you install the app from?

Amazon Appstore

### Device information

FIRE TV

### Android version

FIRE OS 7.6.0.8

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment] 2022-12-08 18:28
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed by nielsvanvelzen** 2022-12-08 18:28 UTC
Labels: bug
