### ISSUE TITLE
NullPointerException after playback

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin-androidtv#3277] opened 2024-01-02 13:05 UTC
### Describe the bug

Hi,
with Fire TV Stick 4K Max 2nd generation (Android 11) I experienced a NullPointerException after playback end.
It happens when a series episode finished and another should begin, but appear a message "no playable objects found" and the app crashes.
I'm using MPV external player (as ExoPlayer is very limited, LibVLC has many bugs, and external VLC app works but not keep the sign if I interrupt the playback).
I see in same episodes with the bug also an about 5 seconds delay before direct playback start.
Regards

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.2
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7dcef8b, Dispatchers.IO]

```  
***Logcat***: 
```log
--------- beginning of main
01-01 23:01:13.810 I/lyfin.androidt(28504): Bumping SignalCatcher priority from 10 to 10
01-01 23:01:13.817 E/lyfin.androidt(28504): Not starting debugger since process cannot load the jdwp agent.
01-01 23:01:14.175 I/ACRA    (28504): ACRA is enabled for org.jellyfin.androidtv, initializing...
01-01 23:01:14.299 W/lyfin.androidt(28504): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
01-01 23:01:14.299 W/lyfin.androidt(28504): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-01 23:01:14.300 W/lyfin.androidt(28504): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-01 23:01:14.305 I/TetheringManager(28504): registerTetheringEventCallback:org.jellyfin.androidtv
01-01 23:01:14.335 I/LogInitializer(28504): Debug tree planted
01-01 23:01:14.368 W/lyfin.androidt(28504): Accessing hidden method Landroid/graphics/ImageDecoder;->createSource([B)Landroid/graphics/ImageDecoder$Source; (greylist-max-o, linking, denied)
01-01 23:01:14.387 I/MigrationContext(28504): Requested migration from 2 to 2. Found 1 migrations in total.
01-01 23:01:14.442 I/SessionRepositoryImpl$restoreSession(28504): Restoring session
01-01 23:01:14.459 I/org.jellyfin.sdk.api.client.KtorClient(28504): GET http://<IP>:8096/Branding/Configuration
01-01 23:01:14.607 I/MigrationContext(28504): Requested migration from 7 to 7. Found 1 migrations in total.
01-01 23:01:14.611 I/ActivityThemeExtensionsKt(28504): Applying theme DARK
01-01 23:01:14.640 I/ExoPlayerImpl(28504): Init 8370e4e [ExoPlayerLib/2.19.1] [karat, AFTKRT, Amazon, 30]
01-01 23:01:14.641 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.643 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.643 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.643 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.644 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.644 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.644 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.644 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.648 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.648 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.649 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.649 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.649 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Reconnecting
01-01 23:01:14.649 I/org.jellyfin.sdk.api.sockets.SocketInstance(28504): Cancelling reconnect because baseUrl is null
01-01 23:01:14.656 E/ACRA    (28504): ACRA caught a NullPointerException for org.jellyfin.androidtv
01-01 23:01:14.656 E/ACRA    (28504): java.lang.NullPointerException
01-01 23:01:14.656 E/ACRA    (28504): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
01-01 23:01:14.656 E/ACRA    (28504): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
01-01 23:01:14.656 E/ACRA    (28504): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
01-01 23:01:14.656 E/ACRA    (28504): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
01-01 23:01:14.656 E/ACRA    (28504): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7dcef8b, Dispatchers.IO]
01-01 23:01:14.692 I/DefaultRenderersFactory(28504): Loaded FfmpegAudioRenderer.
01-01 23:01:14.714 I/HomeRowsFragment(28504): Updating audio queue in HomeFragment (onQueueStatusChanged)
01-01 23:01:14.717 W/MainActivity(28504): Activity org.jellyfin.androidtv.ui.browsing.MainActivity started without a session, bouncing to StartupActivity

```  

### App information

***App version***: `0.16.2` (`160299`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"karat","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"karat","DISPLAY":"<ID>","FINGERPRINT":"Amazon\/karat\/karat:11\/<ID>\/0021810856068:user\/amz-p,release-keys","HARDWARE":"mt8696","HOST":"<HOST>","ID":"<ID>","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTKRT","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"karat","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1699337124000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"RP1A.200720.009","CODENAME":"REL","INCREMENTAL":"0021810856068","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2020-09-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160299,"VERSION_NAME":"0.16.2"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `Amazon`  
***Device product***: `karat`  
***Device model***: `AFTKRT`  

### Crash information

***Start time***: `2024-01-01T23:01:14.254+01:00`  
***Crash time***: `2024-01-01T23:01:14.768+01:00`  

### Application version

0.16.2

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Stick 4K Max 2nd gen (2023)

### Android version

FireOS 8

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment] 2024-01-06 12:40
Closing as duplicate of #2947

**Closed by nielsvanvelzen** 2024-01-06 12:40 UTC
Labels: bug
