### ISSUE TITLE
Cannot enter password

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-androidtv#536] opened 2020-08-01 21:57 UTC
**Describe the bug**
When logging in on androidTV, I can enter a username but it won’t let me enter a password. With any combination of toggling to the ok button or pushing enter in the keyboard in a Sony Android TV.

Workaround is to unhide username showing up and then you can enter password.

**To Reproduce**
Load program and select server
Enter username
It will disappear and there is no way to enter a password. 

**Expected behavior**
Allow to submit password

**Screenshots**
See video https://gofile.io/d/JFb235

**System (please complete the following information):**
 - Android TV
 - Device manufacturer: Sony
 - Device model: Android Oreo 8
 - Jellyfin server version: 10.6

**Additional context**

**Comment by thornbill** [comment] 2020-08-01 23:43
Duplicate of #167.

**Closed by thornbill** 2020-08-01 23:43 UTC
Labels: bug
