### ISSUE TITLE
Jellyfin on Fire TV exits after music playback reaches end of queue

### ISSUE THREAD

**Issue by ZachGill** [jellyfin/jellyfin-androidtv#2617] opened 2023-03-24 00:21 UTC
**Describe The Bug**
When playing music, Jellyfin on Fire TV will exit back to the (Fire TV) home screen once the last song in the queue ends

**Steps To Reproduce**
1. Open Jellyfin on Fire TV
2. Start playing music (could be a single song, an album, a queue composed of an arbitrary collection of songs, whatever)
3. Wait for the last song in the queue to finish playing
4. Jellyfin closes itself

**Expected Behavior**
Jellyfin should remain open and return to the main screen or elsewhere once music playback ends

**Logs**
As far as I can see, no errors are logged

**System (please complete the following information):**
 - Platform: Fire TV Stick 4K Max
 - Browser: Official Jellyfin app
 - Jellyfin Version: jellyfin-androidtv 0.15.5

Server is running Jellyfin 10.8.9, hosted directly on a machine running Ubuntu Server 22.04.2 LTS

**Comment by nielsvanvelzen** [comment] 2023-03-24 07:54
Unable to reproduce, please provide (crash)logs.

You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat. Make sure to reproduce the issue just before getting the logs.

**Comment by ZachGill** [comment] 2023-03-25 03:54
[Here's](https://github.com/jellyfin/jellyfin-androidtv/files/11067912/output.log) the full log file I was able to grab, I couldn't really pick out anything that seemed like an outright error so apologies for the long file

**Comment by nielsvanvelzen** [comment] 2023-03-25 12:56
Thanks for the report, issue will be fixed with the next release

**Closed** 2023-03-25 13:11 UTC
Labels: bug
