### ISSUE TITLE
[Issue]: [Android tv] Playing Image Always Starts with the First One

### ISSUE THREAD

**Issue by SirMartin** [jellyfin/jellyfin-androidtv#2798] opened 2023-05-27 10:02 UTC
I recover the issue jellyfin/jellyfin#4167 because it still an issue in the latest versions, and that one was closed.

In a photo library, it will always start at the first image when playing an image, but if you open in photos a video it plays the selected one.

It should start with the selected image (that is especially frustrating when viewing a photo library with a large amount of images).

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: docker on Debian on proxmox container 
- Virtualization:docker
- Clients:Android tv
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment] 2023-05-27 12:27
Please use our provided issue template and share reproducible steps so we can look into this.

**Comment by SirMartin** [comment] 2023-05-29 10:02
Ok, I will try.

Steps to reproduce.

In a photo library select one picture but not in the first position.
The first picture in the library will be open.

I expect that the picture select will be open in full size.

Android 9
Kernel version 4.9.125
Model device Philips TPM191E
App version: (from Google play store) 0.15.9
Jellyfin server version: 10.8.10

Please let me know if you need something more.

**Comment by nielsvanvelzen** [comment] 2023-05-30 20:25
Closing this issue as duplicate of #2767. The issue is likely fixed in the next release, otherwise let us know and we'll re-open the issue.

**Closed by nielsvanvelzen** 2023-05-30 20:25 UTC
Labels: bug
