### ISSUE TITLE
Missing subtitle delay controls in video player

### ISSUE THREAD

**Issue by JohnnyDeeee** [jellyfin/jellyfin-androidtv#3858] opened 2024-08-07 20:57 UTC
### Describe the bug

I'm missing the button to control the subtitle delay inside the media player. I'm running version 0.17.0. I have to be honest i didn't use this feature in a while so i'm not sure if it is missing since the 0.17.0 release... I also noticed that the option to change the preferred video player is gone from the settings. I can only check the option for external players.

### Application version

0.17.0

### Device information

Phillips TPM191E

### Android version

11

### Jellyfin server version

10.9.9

**Comment by rickysixx** [comment] 2024-08-08 10:36
> I also noticed that the option to change the preferred video player is gone from the settings. I can only check the option for external players.

If you are referring to LibVLC, this is expected. LibVLC backend was removed in 0.17 (see #3639 for more detail).

**Comment by nielsvanvelzen** [comment] 2024-08-08 17:09
The subtitle delay option was only ever implemented for the experimental LibVLC integration. So it is no longer available. Closing as duplicate of #2479

**Closed by nielsvanvelzen** 2024-08-08 17:09 UTC
Labels: bug, playback

**Comment by thor9898** [comment] 2024-08-13 20:29
> The subtitle delay option was only ever implemented for the experimental LibVLC integration. So it is no longer available. Closing as duplicate of #2479

In The Playback Rewrite issue, under restoring features it says "Add LibVLC backend" is there any estimated time on when it might be integrated?

**Comment by nielsvanvelzen** [comment] 2024-08-14 07:35
That list isn't entirely up-to-date (I'd rather spend time working on the actual code then updating lists). I've removed that item now 👍
