### ISSUE TITLE
Simultaneous PGS subtitles do not work properly

### ISSUE THREAD

**Issue by tydog98** [jellyfin/jellyfin-androidtv#4308] opened 2024-12-17 02:56 UTC
### Describe the bug

I am attempting to watch Lupin III Part 3, and sometimes subtitles will display on both the top and bottom of the screen. On Kodi this works fine, but on Jellyfin ATV it will attempt to show both subtitles on the bottom at the same time.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.18.2

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment] 2024-12-17 20:29
Duplicate of #2766. We currently do not support this.

**Closed by nielsvanvelzen** 2024-12-17 20:29 UTC
Labels: bug, playback
