### ISSUE TITLE
EAC3 no longer plays

### ISSUE THREAD

**Issue by faptaincrunch** [jellyfin/jellyfin-androidtv#1781] opened 2022-06-15 02:24 UTC
### Describe the bug

EAC3 will no longer play on AndroidTV but will play on Roku and Jellyfin media player on PC. Exoplayer nor libVLC works. Tried moving to older versions of jellyfin client but still EAC3 will not play without trying to transcode which is disabled on my server. 

### Application version

0.13.6

### Where did you install the app from?

Google Play

### Device information

Onn4k

### Android version

Android 10

### Jellyfin server version

10.8.0

**Comment by thornbill** [comment] 2022-06-15 04:24
Duplicate of #1723.

**Closed** 2022-06-15 04:24 UTC
Labels: bug, duplicate
