### ISSUE TITLE
Show playback information

### ISSUE THREAD

**Issue by BLACK4585** [jellyfin/jellyfin-androidtv#4356] opened 2024-12-30 10:45 UTC
### Describe the feature you'd like

Hey,
it would be nice if there was a button in the player controls menu in the player to show current playback information like resolution, bitrate, transcoding and so on.

**Comment by nielsvanvelzen** [comment] 2024-12-30 11:05
Duplicate of #1637

**Closed by nielsvanvelzen** 2024-12-30 11:05 UTC
Labels: enhancement
