### ISSUE TITLE
Shuffle All for Individual Seasons within a TV Show Does Not Work

### ISSUE THREAD

**Issue by ethaldeman** [jellyfin/jellyfin-androidtv#4359] opened 2024-12-30 22:42 UTC
### Describe the bug

1. Select a TV Series
2. Long press on one of the seasons.
3. Select the "Shuffle all" option
4. Observe that the episodes are replayed in season, not shuffled, order.

Notes: The built in "Shuffle all" button for the whole series seems to play in random order and the "Shuffle" option on the web client seems to play in random order. 

### Logs

[2024-12-30 17:35:22.552 -05:00] [INF] WS "84.239.41.140" request
[2024-12-30 17:36:06.239 -05:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-30 17:36:32.257 -05:00] [INF] User policy for "winthryth". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-12-30 17:36:32.411 -05:00] [INF] Adding playback tracker : a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-87c549a1da76ea783564248efea08989
[2024-12-30 17:36:32.411 -05:00] [INF] PlaybackTracker : Adding Start Event : 12/30/2024 17:36:32
[2024-12-30 17:36:32.411 -05:00] [INF] Creating StartPlaybackTimer Task
[2024-12-30 17:36:32.411 -05:00] [INF] StartPlaybackTimer : Entered
[2024-12-30 17:36:32.578 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f avi -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -i file:\"/Server_Media/Shows/SpongeBob SquarePants (1999)/Season 2/S02E01.avi\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -b:v 5281950 -maxrate 5281950 -bufsize 10563900 -profile:v:0 main -level 50 -g:v:0 90 -keyint_min:v:0 90 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(4096\,4096*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(4096/a\,4096))/2)*2,format=yuv420p\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467.m3u8\""
[2024-12-30 17:36:33.235 -05:00] [INF] Processing playback tracker : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:38.932 -05:00] [INF] Stopping ffmpeg process with q command for "/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467.m3u8"
[2024-12-30 17:36:39.230 -05:00] [INF] FFmpeg exited with code 0
[2024-12-30 17:36:39.234 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -ss 00:11:30.000 -f avi -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -i file:\"/Server_Media/Shows/SpongeBob SquarePants (1999)/Season 2/S02E01.avi\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -b:v 5281950 -maxrate 5281950 -bufsize 10563900 -profile:v:0 main -level 50 -g:v:0 90 -keyint_min:v:0 90 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(4096\,4096*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(4096/a\,4096))/2)*2,format=yuv420p\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 230 -hls_segment_filename \"/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467.m3u8\""
[2024-12-30 17:36:39.499 -05:00] [INF] FFmpeg exited with code 0
[2024-12-30 17:36:51.756 -05:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcodes/c8e5e80eda11fea077ec90aa82197467.m3u8"
[2024-12-30 17:36:52.411 -05:00] [INF] session.RemoteEndPoint : "192.168.1.1"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : event_playing_id     = "87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : event_user_id        = "632873292b554468a610c99d335e1c7a"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : session_playing_id   = "87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : session_user_id      = "632873292b554468a610c99d335e1c7a"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : play_method          = "Transcode (v:hevc a:direct)"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : e.ClientName         = "Android TV"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : e.DeviceName         = "Onn 4k TV"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : ItemName             = "SpongeBob SquarePants - s02e01 - Something Smells"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : ItemId               = "87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : ItemType             = "Episode"
[2024-12-30 17:36:52.411 -05:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-12-30 17:36:52.411 -05:00] [INF] Playback tracker found, adding playback info : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:52.411 -05:00] [INF] Saving playback tracking activity in DB
[2024-12-30 17:36:52.414 -05:00] [INF] StartPlaybackTimer : Exited
[2024-12-30 17:36:53.331 -05:00] [INF] Playback stopped reported by app "Android TV" "0.18.2" playing "Something Smells". Stopped at "701340" ms
[2024-12-30 17:36:53.335 -05:00] [INF] Playback stop tracker found, processing stop : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-87c549a1da76ea783564248efea08989"
[2024-12-30 17:36:53.335 -05:00] [INF] PlaybackTracker : Adding Stop Event : 12/30/2024 17:36:53
[2024-12-30 17:36:53.335 -05:00] [INF] Saving playback tracking activity in DB
[2024-12-30 17:37:32.526 -05:00] [INF] User policy for "winthryth". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-12-30 17:37:32.686 -05:00] [INF] Adding playback tracker : a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-6bff6c2208dec0353025b7eb47f5c7e9
[2024-12-30 17:37:32.687 -05:00] [INF] PlaybackTracker : Adding Start Event : 12/30/2024 17:37:32
[2024-12-30 17:37:32.687 -05:00] [INF] Creating StartPlaybackTimer Task
[2024-12-30 17:37:32.687 -05:00] [INF] StartPlaybackTimer : Entered
[2024-12-30 17:37:33.076 -05:00] [INF] Processing playback tracker : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:37.240 -05:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-12-30 17:37:52.687 -05:00] [INF] session.RemoteEndPoint : "192.168.1.1"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : event_playing_id     = "6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : event_user_id        = "632873292b554468a610c99d335e1c7a"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : session_playing_id   = "6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : session_user_id      = "632873292b554468a610c99d335e1c7a"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : play_method          = "DirectPlay"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : e.ClientName         = "Android TV"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : e.DeviceName         = "Onn 4k TV"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : ItemName             = "SpongeBob SquarePants - s01e01 - Help Wanted"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : ItemId               = "6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : ItemType             = "Episode"
[2024-12-30 17:37:52.687 -05:00] [INF] StartPlaybackTimer : All matches, playback registered
[2024-12-30 17:37:52.687 -05:00] [INF] Playback tracker found, adding playback info : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:52.687 -05:00] [INF] Saving playback tracking activity in DB
[2024-12-30 17:37:52.691 -05:00] [INF] StartPlaybackTimer : Exited
[2024-12-30 17:37:53.283 -05:00] [INF] Processing playback tracker : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:56.846 -05:00] [INF] Playback stopped reported by app "Android TV" "0.18.2" playing "Help Wanted". Stopped at "497420" ms
[2024-12-30 17:37:56.850 -05:00] [INF] Playback stop tracker found, processing stop : "a0268c3633077ae64e3b60c4271d2a4f2c2c91de-632873292b554468a610c99d335e1c7a-6bff6c2208dec0353025b7eb47f5c7e9"
[2024-12-30 17:37:56.850 -05:00] [INF] PlaybackTracker : Adding Stop Event : 12/30/2024 17:37:56
[2024-12-30 17:37:56.850 -05:00] [INF] Saving playback tracking activity in DB
[2024-12-30 17:39:05.773 -05:00] [INF] WS "84.239.41.140" closed
[2024-12-30 17:39:06.310 -05:00] [INF] WS "84.239.41.140" request
[2024-12-30 17:39:08.241 -05:00] [INF] "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds

### Application version

0.18.2

### Where did you install the app from?

Google Play

### Device information

Onn 4k TV (2021 version)

### Android version

Android 12

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment] 2024-12-31 15:08
Closing as duplicate of jellyfin/jellyfin#13224. The client does everything correctly but the server sends non-shuffled items back.

**Closed by nielsvanvelzen** 2024-12-31 15:08 UTC
Labels: bug, confirmed
