### ISSUE TITLE
MX player not seeing srt file automatically

### ISSUE THREAD

**Issue by JohnnyDrama** [jellyfin/jellyfin-androidtv#4349] opened 2024-12-28 10:43 UTC
### Describe the bug

When Jellyfin AndroidTV uses external MX player pro 1.86.0 (on Chromecast 4K) to play a movie from my NAS, MXplayer doesn't 'see' the .srt file, which is always in the same folder and always has the same name as the mp4.

When I open the same mp4 with MX player via Cx file Explorer (smb), MX player sees the subtitle file just fine. Also with Jellyfin phone version (latest) with MX player pro 1.86.0, I don't have this problem.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.18.2

### Device information

Chromecast with AndroidTV 4K

### Android version

Android TV 12 + Projectivy premium, latest versions

### Jellyfin server version

10.10.3-20

**Comment by nielsvanvelzen** [comment] 2024-12-28 10:49
Duplicate of #4310

**Closed by nielsvanvelzen** 2024-12-28 10:49 UTC
Labels: bug, playback

**Comment by JohnnyDrama** [comment] 2024-12-28 10:55
Ah, sorry to bother you, I've now learned to check not only the _open_ issues first :-)
