### ISSUE TITLE
Video speeds up and slows down breaking the sense of motion

### ISSUE THREAD

**Issue by BrightCandle** [jellyfin/jellyfin-androidtv#54] opened 2019-02-23 20:43 UTC
TV is a Philips 43pus7303.

The motion runs at a normal pace and then jumps so that the frames aren't consistently delivered. It interacts very badly with the TVs inbuilt motion smoothing to produce a very unpleasant image that does not give you the sense of motion.

Present in beta 1 and beta 3 builds for androidTV google version.

**Comment by thornbill** [comment] 2020-02-19 04:14
We have made a lot of progress updating the internal player libraries since this issue was created. Are you still experiencing this problem on new versions of the app?

**Comment by JoshStrobl** [comment] 2020-02-22 18:13
I have a Philips 58PUS7304 and I'm experience the same issue with the updated app, the videos are sped up about 7-8% (if I load up VLC Player on the TV and tinker with the video speed there I can get it to match).

**Comment by AndreasGB** [comment] 2020-02-23 13:50
Have you tried disabling refresh rate switching in the settings? Maybe it is caused by that, at least for me this sometimes leads to choppy playback.

**Comment by JoshStrobl** [comment] 2020-03-06 17:45
Apologies for the delayed response. After doing some further testing, I've confirmed my issues were not related to the Jellyfin AndroidTV application but rather related to my Philips TV's default Picture Style creating some undesired soap opera effect that seemed to only affect this specific application. Setting my Picture Style to none / disabling it resolved the issue and frankly I'm appalled that they set it to one by default in the first place.

**Comment by thornbill** [comment] 2020-03-06 18:31
Glad you found a solution @JoshStrobl!

Completely unrelated, but I'm a big fan of Solus and Budgie thanks for all the work you do over there!

**Comment by AndreasGB** [comment] 2020-03-06 18:36
@BrightCandle can you please check whether this resolves the issue for you as well?

I'll close the issue if we don't hear back from you in the next two weeks, of course feel free to re-open it if you still encounter the issue :)

**Closed** 2020-03-22 11:17 UTC
Labels: bug, question
