### ISSUE TITLE
Cards view shows the title of show/movie

### ISSUE THREAD

**Issue by gbals001** [jellyfin/jellyfin-androidtv#3949] opened 2024-08-30 11:15 UTC
### Describe the feature you'd like

Similar to how in the web client and others currently display in poster view, it would be *awesome* to display the title of the show/movie. below the poster.
This makes it much easier to navigate and in general makes for a much nicer user experience.

**Comment by nielsvanvelzen** [comment] 2024-12-29 10:05
Duplicate of #654

**Closed by nielsvanvelzen** 2024-12-29 10:05 UTC
Labels: enhancement
