### ISSUE TITLE
Suddenly unable to remote connect

### ISSUE THREAD

**Issue by jameskimmel** [jellyfin/jellyfin-androidtv#3457] opened 2024-03-20 20:55 UTC
### Describe the bug

1. Sony Android TV that was able to connect to jellyfin before
2. All of sudden, login in is not possible anymore
3. After inserting username and password, get error "unable to connect to server"
4. Do the same thing, on the same Wifi a tablet and the user is able to log in. 
5. See logs below about the SSl handshake

Jellyfin sits behind a NGINX reverse proxy. The affected client is remote. Valid Letsencrypt cert, HSTS preload active. 

### Logs

[2024-03-20 21:30:21.298 +01:00] [WRN] WS "remoteIP" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-03-20 21:30:21.302 +01:00] [INF] WS "remoteIP" closed

### Application version

0.16.7

### Where did you install the app from?

Google Play

### Device information

Sony Bravia 4k 2015

### Android version

AndroiD 7.0

### Jellyfin server version

10.8.13

**Comment by dglava** [comment] 2024-03-21 08:37
Same issue here on my Philips 48PFK5500/12 running Android 5. I am also using an Nginx reverse proxy and a certificate by LetsEncrypt. It works on other clients, including jellyfin-androidtv on other TV's.

The error I am getting also seems to be SSL related: "SSL Handshake failed" inside the jellyfin-androidtv app. I cannot access logs from the client on the TV itself (haven't found a way to connect via adb to it).

As mentioned in [this](https://github.com/jellyfin/jellyfin-androidtv/issues/3383#issuecomment-1961711351) issue, I have disabled TLSv1.3 on the server, because someone mentioned it might not work on those "older" TVs, but without success. Even with just TLSv1.2 I was getting the same error.
I haven't found a way to downgrade to an earlier version of jellyfin-androidtv to see if those work.

I understand that the Android version is old, but what has changed recently? There haven't been any updates on the TV, no updates to Nginx on my server and no Jellyfin updates. Did jellyfin-androidtv do any changes regarding this?

Jellyfin-androidtv: 0.16.7
Jellyfin: 10.8.13
Android version: 5
TV: Philips 48PFK5500/12

**Comment by jameskimmel** [comment] 2024-03-21 10:04
There are no crash logs on the server and I was unable to find a doc how to get them from AndroidTV.

The Cert is R3, so guess this new intermediate certs do not apply to me?

**Comment by dglava** [comment] 2024-03-23 11:08
> Without client logs we're just guessing but this change Lets Encrypt made might be the cause: https://letsencrypt.org/2024/03/19/new-intermediate-certificates.html

That was exactly the cause for me. The certificates don't appear to be trusted on the TV/Android version anymore. To be honest, this was such a sickening wake-up experience. The TV is perfectly fine, but due to the awful vendor (Philips) deciding that they don't support it anymore, it's rendered almost useless when using the TV's OS itself.

I switched to ZeroSSL and their certificates seem to still work on this TV. I wonder for how long. Either way, it's not a jellyfin-androidtv issue, at least on my end. Thanks for the hint.

**Comment by nielsvanvelzen** [comment] 2024-03-23 14:25
Closing the issue as this is a configuration issue (device does not support the user provided certificate).

For more information on supported devices with Lets Encrypt see this page: https://letsencrypt.org/docs/certificate-compatibility/

**Closed by nielsvanvelzen** 2024-03-23 14:25 UTC
Labels: bug
