### ISSUE TITLE
[0.14.0 beta] Music keeps playing when App is closed via back button

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1856] opened 2022-07-18 07:07 UTC
### Describe the bug

Also Music controls do not display, two ways to stop play back, find the song and press stop or force the app to close. When opening other apps the music keeps playing, although this kind of good I don't remember this happening before?

### Logs

Nothing in logs

### Application version

0.14.0

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD Android TV

### Android version

Android 11

### Jellyfin server version

10.8.1

**Comment by sourpatched** [comment] 2022-07-18 09:32
I expected the music to stop playing outside the app, does this issue need closing?

**Comment by nielsvanvelzen** [comment] 2022-07-18 11:06
Right now it's intended behavior to keep playing music so closing as not planned.

**Closed by nielsvanvelzen** 2022-07-18 11:06 UTC
Labels: bug
