### ISSUE TITLE
[10.6 beta] Intermittent crash on program launch on Fire Stick

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-androidtv#3161] opened 2023-11-04 02:53 UTC
### Describe the bug

1. Launch the application from the fire stick menu
2. Crashes

After 2-3 tries it launched successfully.  This happened a few days ago as well.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.5
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ea78282, Dispatchers.IO]

```  
***Logcat***: 
```log
--------- beginning of main
11-03 22:45:35.075 E/lyfin.androidt(11068): Not starting debugger since process cannot load the jdwp agent.
11-03 22:45:35.420 I/ACRA    (11068): ACRA is enabled for org.jellyfin.androidtv, initializing...
11-03 22:45:35.547 W/lyfin.androidt(11068): Accessing hidden method Landroid/view/View;->setTransitionVisibility(I)V (dark greylist, linking)
11-03 22:45:35.569 W/lyfin.androidt(11068): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (dark greylist, reflection)
11-03 22:45:35.570 W/lyfin.androidt(11068): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (dark greylist, reflection)
11-03 22:45:35.570 W/lyfin.androidt(11068): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (dark greylist, reflection)
11-03 22:45:35.604 I/LogInitializer(11068): Debug tree planted
11-03 22:45:35.651 I/MigrationContext(11068): Requested migration from 2 to 2. Found 1 migrations in total.
11-03 22:45:35.681 I/SessionRepositoryImpl(11068): Restoring session
11-03 22:45:35.697 I/org.jellyfin.sdk.api.client.KtorClient(11068): GET https://jellyfin.XXXXXX.XX:1234/Branding/Configuration
11-03 22:45:35.745 I/MigrationContext(11068): Requested migration from 7 to 7. Found 1 migrations in total.
11-03 22:45:35.750 I/ActivityThemeExtensionsKt(11068): Applying theme DARK
11-03 22:45:35.772 W/MainActivity(11068): Activity org.jellyfin.androidtv.ui.browsing.MainActivity started without a session, bouncing to StartupActivity
11-03 22:45:35.777 E/ACRA    (11068): ACRA caught a NullPointerException for org.jellyfin.androidtv
11-03 22:45:35.777 E/ACRA    (11068): java.lang.NullPointerException
11-03 22:45:35.777 E/ACRA    (11068): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResume(HomeFragmentHelper.kt:33)
11-03 22:45:35.777 E/ACRA    (11068): 	at org.jellyfin.androidtv.ui.home.HomeFragmentHelper.loadResumeVideo(HomeFragmentHelper.kt:51)
11-03 22:45:35.777 E/ACRA    (11068): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$onCreate$1.invokeSuspend(HomeRowsFragment.kt:123)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
11-03 22:45:35.777 E/ACRA    (11068): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
11-03 22:45:35.777 E/ACRA    (11068): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ea78282, Dispatchers.IO]

```  

### App information

***App version***: `0.16.0-beta.5` (`160005`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"kara","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"kara","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTKA","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"kara","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1695416575000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"[0029159767172](tel:0029159767172)","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2023-08-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160005,"VERSION_NAME":"0.16.0-beta.5"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `Amazon`  
***Device product***: `kara`  
***Device model***: `AFTKA`  

### Crash information

***Start time***: `2023-11-03T22:45:35.518-04:00`  
***Crash time***: `2023-11-03T22:45:35.854-04:00`

### Application version

0.16.0-beta.5

### Where did you install the app from?

Sideloaded APK

### Device information

Fire Stick 4K Max

### Android version

Latest

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment] 2023-11-15 12:56
Closing as duplicate of #2947.

**Closed by nielsvanvelzen** 2023-11-15 12:56 UTC
Labels: bug
