### ISSUE TITLE
Special Features Not Displayed on Android TV Client

### ISSUE THREAD

**Issue by djolker** [jellyfin/jellyfin-androidtv#2846] opened 2023-06-19 17:45 UTC
### Describe the bug

# Describe the bug

1. Navigate to TV Show in your Jellyfin server from the Android TV Client that contains a folder structure of "Show/Season 1/behind the scenes/item.mkv"
2. Navigate to the season with "behind the scenes" content
3. Expect to see said content listed somewhere in the UI

WebUI and iOS display a "Special Features" section 
![image](https://github.com/jellyfin/jellyfin-androidtv/assets/9284677/7b2d87e6-504c-42c3-8817-9c42b7caabc2)

Currently the AndroidTV client will only display the episodes listed directly in the "Season" directory, but not display any content in subfolders of those Seasons.

[Jellyfin docs](https://jellyfin.org/docs/general/server/media/shows/#extras-folders) states the server supports many naming conventions for "special features" like sub folders within Seasons of TV shows.

### Application version

0.15.10

### Where did you install the app from?

Google Play

### Device information

ChromeCast TV 

### Android version

Android TV OS version 12

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2024-01-15 08:17
Closing as duplicate of #3009, this feature will be available in the next release (0.17).

**Closed by nielsvanvelzen** 2024-01-15 08:17 UTC
Labels: enhancement
