### ISSUE TITLE
Music Playlists only show the first 150 items

### ISSUE THREAD

**Issue by silentTeee** [jellyfin/jellyfin-androidtv#3140] opened 2023-10-25 02:28 UTC
### Describe the bug

Not sure if this was always an issue, I just noticed it and figured I should document it.

1. Go to Music section
2. Go to any playlist with more than 150 entries
3. Scroll to the bottom of the list of song entries
4. Observe that it only shows the first 150.

### Application version

0.16.0-beta.5

### Where did you install the app from?

Google Play

### Device information

SONY BRAVIA 4K VH22

### Android version

Android 10

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment] 2023-10-27 20:01
The 150 item limit was already a thing in 0.15 and while technically the new playback code does support an unlimited amount of items, the user interface still only asks to play 150 items. It's fixable but not easily.

Closing as duplicate of #470.

**Closed by nielsvanvelzen** 2023-10-27 20:01 UTC
Labels: bug
