### ISSUE TITLE
Extra translucent shading when applying external subtitle(.srt)

### ISSUE THREAD

**Issue by mailbyms** [jellyfin/jellyfin-androidtv#1126] opened 2021-09-03 15:30 UTC
**Checks**
- Yes, Issue does not happen in the browser (jellyfin-web)

**Problem**
The following picture shows there is extra translucent shading as background, when I apply a external SRT subtitle.
Be noted, I've set up customized font（msyh.ttc, copied from windows 10） too, because it's a subtitle with Chinese words.
![image](https://user-images.githubusercontent.com/16809751/132028645-b80c8c8c-2385-49a9-af0f-21df5ea91150.png)

When choose the build-in subtitle, it looks good:
![image](https://user-images.githubusercontent.com/16809751/132029033-3b4d5932-3f6d-44cc-a19d-bba004a66640.png)

**System (please complete the following information):**
 - Android  7
 - Device manufacturer: Sony
 - Device model: 55x8000c
 - Jellyfin server version: 10.7.6
 - jellyfin-androidtv: v0.12.0-beta.5

**Additional context**

**Comment by thornbill** [comment] 2021-09-03 22:29
This is a duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/1055. We probably won't change the default but add settings.

**Closed by thornbill** 2021-09-03 22:29 UTC
Labels: playback
