### ISSUE TITLE
[Feature Request] Multiversion selection

### ISSUE THREAD

**Issue by manf0001** [jellyfin/jellyfin-androidtv#1086] opened 2021-08-14 00:04 UTC
In the web interface or the Android client, if I go to a movie or TV show, where it might have multiple versions of the Video, Audio, and subtitle tracks I can make a selection.

So if I have a regular version and a special edition of a movie, or select subtitle, or watch a movie with Commentary or not, I can choose.

On the AndroidTV client, there doesn't seem to be a way to select if I want the regular or special edition, or pick the audio track for commentary or not.

Thanks keep up the great work

**Comment by thornbill** [comment] 2021-08-14 01:30
Duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/685

**Closed** 2021-08-14 01:31 UTC
Labels: duplicate, enhancement
