### ISSUE TITLE
Jellyfin doesn't remember chosen subtitles on resume

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin-androidtv#3362] opened 2024-02-10 22:32 UTC
### Describe the bug

Almost every time i resume something, it has reverted to default and i have to manually re-select the subtitles.

### Application version

0.16

### Where did you install the app from?

Google Play

### Device information

chromecast 4k

### Android version

ATV13

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment] 2024-02-11 09:27
The server has no way to store the last used stream so the client can't implement it either.

Closing as not a bug / upstream feature request.

**Closed by nielsvanvelzen** 2024-02-11 09:27 UTC
Labels: bug

**Comment by fusk-l** [comment] 2024-02-11 20:47
> The server has no way to store the last used stream so the client can't implement it either.
> 
> Closing as not a bug / upstream feature request.

If that was the case, it would always be the case it doesn't remember the chosen subtitle. But this is not the case, sometimes it does. How come that is, and why can't this be universal for all media?

**Comment by nielsvanvelzen** [comment] 2024-02-11 21:19
The app will always start with the default streams. Those are set in the media (with default and forced flags) and sometimes Jellyfin will overwrite that based on user preferences. Changing them during playback is never saved.

**Comment by fusk-l** [comment] 2024-02-11 21:30
I see, so if the user preference is German, Danish or something else, it might pick the correct subtitle, but only maybe. Is there a way to increase that accuracy by adding different ways the subtitle might be named. Like DK/Danish/Dansk ?

**Comment by nielsvanvelzen** [comment] 2024-02-11 21:35
The client is not responsible for that behavior.

**Comment by fusk-l** [comment] 2024-02-11 21:37
What about the server, can that do anything?
