### ISSUE TITLE
Can this project be compatible with the minimum Android 4.4 version

### ISSUE THREAD

**Issue by FuXinLisc** [jellyfin/jellyfin-androidtv#4313] opened 2024-12-18 03:46 UTC
### Describe the feature you'd like

Can this project be compatible with the minimum Android 4.4 version

**Comment by thornbill** [comment] 2024-12-18 05:37
Duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/1747

**Closed by thornbill** 2024-12-18 05:37 UTC
Labels: duplicate, enhancement
