### ISSUE TITLE
[0.18.0 Beta] App crashes while trying to stream live tv if transcoding is disable

### ISSUE THREAD

**Issue by Hello-World-Traveler** [jellyfin/jellyfin-androidtv#4158] opened 2024-11-03 22:11 UTC
### Describe the bug

On a fresh install, transcoding is disabled the app will crash.

Error message would be better shown to the user "unable able to direct stream, check settings."

Logs are never uploaded to server.

### Logs

```
E/ACRA    ( 2378): ACRA caught a NullPointerException for org.jellyfin.androidtv.debug
E/ACRA    ( 2378): java.lang.NullPointerException: Parameter specified as non-null is null: method org.jellyfin.androidtv.util.apiclient.ReportingHelper.reportStopped, parameter streamInfo

I/ActivityManager(  734): Process org.jellyfin.androidtv.debug (pid 2378) early provider death
I/ActivityManager(  734): Process org.jellyfin.androidtv.debug (pid 2378) has died: fg  BTOP
 W/TGuardMemoryManagerPackageRecord(  964): skipped save pss as zero pkg:org.jellyfin.androidtv.debug
 I/ActivityManager(  734): Killing 2567:com.spocky.projengmenu/u0a89 (adj 0): depends on provider org.jellyfin.androidtv.debug/org.jellyfin.androidtv.integration.provider.ImageProvider in dying proc org.jellyfin.androidtv.debug (adj 0)
 W/InputDispatcher(  734): Attempted to unregister already unregistered input channel 'df983a org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.browsing.MainActivity (server)'

I/AvrcpMediaPlayerList(  982): onMediaKeyEventSessionChanged: packageName=org.jellyfin.androidtv.debug
W/AvrcpMediaPlayerList(  982): org.jellyfin.androidtv.debug is already the active player
W/AvrcpMediaPlayerWrapper(  982): The session was destroyed org.jellyfin.androidtv.debug
D/AvrcpMediaPlayerList(  982): sessionUpdatedCallback(): packageName: org.jellyfin.androidtv.debug
D/AvrcpMediaPlayerList(  982): Removing media player org.jellyfin.androidtv.debug
D/AvrcpMediaPlayerList(  982): org.jellyfin.androidtv.debug doesn't have a browse service. Recycle player ID

```

### Application version

0.18.0

### Where did you install the app from?

Sideloaded APK

### Device information

TV

### Android version

Android 11

### Jellyfin server version

10.10

**Comment by nielsvanvelzen** [comment] 2024-11-04 07:44
Duplicate of #4149 and already fixed for the next beta, thanks for reporting!

**Closed by nielsvanvelzen** 2024-11-04 07:44 UTC
Labels: bug
