### ISSUE TITLE
My Media (small) are large (Android TV 9) 

### ISSUE THREAD

**Issue by helptiger** [jellyfin/jellyfin-androidtv#2721] opened 2023-04-29 08:56 UTC
### Describe the bug

Set one section in Home as "My Media (small)". (And for comparison, if not available, one the normal My Media view.)

To me it appears on Android TV just like the normal My Media view. On all other platforms the correct smaller overview is displayed.

### Application version

0.15.7

### Where did you install the app from?

Google Play

### Device information

Sony Bravia Pro Display 4k (atv3)

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2023-04-29 09:04
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed by nielsvanvelzen** 2023-04-29 09:04 UTC
Labels: bug
