### ISSUE TITLE
[Issue]: My Media (small) does not work

### ISSUE THREAD

**Issue by drizzt09** [jellyfin/jellyfin-androidtv#3749] opened 2024-07-14 00:58 UTC
### Describe the bug

in Android TV. tried official and beta 0.17b3.
It defaults home first line to My Media(small) but it is not small like it is in the web interface.
Switching it to nonsmall leaves it the same size

### Application version

0.16.11

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick Max (gen1)

### Android version

Fire OS 7.6.7.3

### Jellyfin server version

10.9.7

**Comment by thornbill** [comment] 2024-07-14 01:56
Duplicate of #1499

> The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Closed** 2024-07-14 01:56 UTC
Labels: bug, duplicate

**Comment by drizzt09** [comment] 2024-07-14 02:46
> normal

Then why is the setting in the tv app settings?

**Comment by drizzt09** [comment] 2024-07-14 04:24
Reading the response in the dupe ticket. That is the dumbest/laziest response. 

If it is not available in the TV app then the option should not be there. 
If you infant as that post states, need it there for other apps then then it should be smart enough to recognize that it's the TV version and hide it. 

However not sure you would choose to not use consistent code across all devices. Makes no sense you would want to try to have uniform style where possible. 
If I launch on pc or phone I get small media buttons. But if I use my tv they are big. They don't behave or look the same.

**Comment by nielsvanvelzen** [comment] 2024-07-14 06:26
Feel free to spend your energy on implementing it yourself instead of being rude to volunteers.
