### ISSUE TITLE
Different aspect ratios in the library view

### ISSUE THREAD

**Issue by mwolos** [jellyfin/jellyfin-androidtv#4062] opened 2024-10-08 22:52 UTC
### Describe the bug

Since version 0.17.6, the library view shows cards with different aspect ratios when the movie has no poster and a thumbnail is used instead, even if the image type is set to poster. This causes columns to have different and changing widths as titles with a thumbnail appear and disappear from view.

### Application version

0.17.6

### Where did you install the app from?

Google Play

### Device information

Philips 65 OLED 707/77

### Android version

Android TV 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment] 2024-10-09 20:10
This may be fixed with the next release, let me know if it doesn't as I couldn't reproduce this exact issue.

**Closed** 2024-10-11 19:45 UTC
Labels: bug
