### ISSUE TITLE
Next Up only show after video

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#1083] opened 2021-08-13 08:46 UTC
**Describe the bug**
When watching TV Shows, the Next Up only pops-up after the entire video has been displayed (incl the credits). In Ver 0.11.5 this normal popped up 30sec before the end of the video (at 29:30 for at 30:00 video). 

**To Reproduce**
Watch episode 1 of a TV Series while episode 2 is flagged as non watched. At the end of the episode instead of the Watch Next to pop up 30sec before the end of the episode, the pop up only displays after the entire episode was played.

**Expected behavior**
In Ver 0.11.5 this popup showed up 30sec before the end of the episode. 

**Suggestion**
This time could even be increased by a setting or 30sec for 30min episodes & 1min for 1hour episodes
See also the additional info in Ver 0.11.5 that is currently not showing in Ver 0.12.0 Beta 4

**Screenshot**
Version 0.11.5
![Ver 0.11.5 Screenshot](https://user-images.githubusercontent.com/69896780/129326204-1e3dbe47-71b6-49bf-8ced-9499c3a5f387.png)

**System (please complete the following information):**
 - Android TV & Xiaomi MI tv stick (Android 9)
 - Device manufacturer: Skyworth TV & Xiaomi MI
 - Jellyfin server version: 10.7.6

**Comment by nielsvanvelzen** [comment] 2021-08-13 08:52
Duplicate of #357

**Closed by nielsvanvelzen** 2021-08-13 08:52 UTC
Labels: enhancement, playback
