### ISSUE TITLE
Add search for subtitle on AndroidTV version [Feature] 

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin-androidtv#406] opened 2020-03-24 05:28 UTC
On android version and web, there is an option to edit and then search missing subtitles. This option is missing on AndroidTv version. Is it possible to make it available also here?

**Comment by nielsvanvelzen** [comment] 2024-02-13 12:31
Closing as duplicate of #690 which also contains a recent status update.

**Closed by nielsvanvelzen** 2024-02-13 12:31 UTC
Labels: enhancement
