### ISSUE TITLE
0.12-beta seeking through video breaks pausing, buffering, subsequent seeking

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/jellyfin-androidtv#1146] opened 2021-09-16 07:20 UTC
**Checks**
- [ check✅] Issue does not happen in the browser (jellyfin-web)

**Media Info of the file**
All videos

Seeking through the video breaks something and the video randomly jumps back to the timestamp before the first seeking was done. This also happens on pausing, when attempting subsequent seeking, and when a video tries to buffer for too

To reproduce:
Open a video and play for a little while
Seek through the video and press play
Pause,btry to seek again, or have the stream buffer for too long, and often the video will jump back to where it was before the first seek

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 10
 - Device manufacturer: Google
 - Device model: Chromecast Google TV
 - Jellyfin server version: 10.7.7

**Comment by nielsvanvelzen** [comment] 2021-09-16 10:43
Duplicate of #400

**Closed by nielsvanvelzen** 2021-09-16 10:43 UTC
Labels: playback
