### ISSUE TITLE
0.17.3 breaking Jellyfin.Xtream plugin

### ISSUE THREAD

**Issue by mrklarth** [jellyfin/jellyfin-androidtv#3886] opened 2024-08-12 16:04 UTC
### Describe the bug

The background for the Xtream plugin is that, to the best of my knowledge, it creates pseudo libraries with subfolders for its contents. With the 0.17 updates, attempting to open this library now just tries to begin playback of a "blank" file, which doesn't appear to be creating anything on the server logs.

I have confirmed that the plugin is working correctly (being able to open the library, select/play items) on the standard Android Jelllyfin App (2.6.2) as well as through web client

### Application version

0.17.3

### Device information

Hisense Google TV

### Android version

Android TV

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment] 2024-08-12 16:35
For issues with third-party plugins it's best to report them to the plugin author. If they determine the issue is with our client they can then report it to us.

I have zero knowledge about this specific plugin so I have no idea what changes could've affected it.

**Comment by mrklarth** [comment] 2024-08-12 20:17
For anyone else with this issue, reverting to 0.16 is the workaround for now. The plug-in's author isn't particularly active lately so a fix is not likely any time soon, but here is the issue for reference: https://github.com/Kevinjil/Jellyfin.Xtream/issues/122

**Comment by Kevinjil** [comment] 2024-08-16 14:17
The plugin implements the Jellyfin `IChannel` interface to provide content (Video On-demand, Series, and TV Catch-up). I can confirm that the latest Android TV release tries to start a stream when opening these content libraries on the home screen, instead of displaying it just like the built-in movies and series libraries.
As such library (channel in JF terms) is obviously not streamable, it causes the following exception on the server side:
```
System.InvalidCastException: Unable to cast object of type 'MediaBrowser.Controller.Channels.Channel' to type 'MediaBrowser.Controller.Entities.IHasMediaSources'
```

This does seem to be a client issue. As I'm not familiar with this codebase and it's recent changes, I'm tagging you @nielsvanvelzen to see if you have any clue what could cause this regression.

**Comment by nielsvanvelzen** [comment] 2024-08-16 14:38
I don't have any plugins myself that implement channels but I believe I fixed the issue with #3902. Please side-load the apk file from the "build" workflow and let me know if it fixes the issue.

**Comment by mrklarth** [comment] 2024-08-16 14:55
I can confirm that change corrected the issue. Thank you!

**Comment by nielsvanvelzen** [comment] 2024-08-16 15:02
Awesome! I'll make sure that fix is included in the next release.

**Closed** 2024-08-16 18:29 UTC
Labels: bug, playback
