### ISSUE TITLE
Playback notification on Android TV

### ISSUE THREAD

**Issue by zynexiz** [jellyfin/jellyfin-androidtv#2416] opened 2023-01-14 13:23 UTC
### Describe the bug

At the moment there doesn't seem to be any "now playing" notification on my Android TV. I have all settings enabled for it, and the notification works with other apps like Deezer. When playing music with Deezer, there is a bar showing the current playing track (like this one https://www.androidheadlines.com/wp-content/uploads/2018/06/DoublePod-Android-TV-Podcast-3-1-1420x799.webp). With Jellyfin there nothing of a sort. That means I can't control media playback with my remote (or OpenHAB witch I use for rules and stuff), like play/pause except when I'm inside the apps player. When I exit to the main screen (or other apps) I have no method of controlling the payback.

With video media this isn't an issue, because I have the playback screen open for obvious reasons :)

Have I missed something or is this not yet implemented?

### Application version

0.15.2

### Device information

Philips TV

### Android version

Android 10

### Jellyfin server version

10.8.8-1

**Comment by nielsvanvelzen** [comment] 2023-01-14 16:22
The app doesn't implement media sessions right now. It will be added with the playback rewrite (#1057).

Closing as duplicate of #441 / #1057.

**Closed by nielsvanvelzen** 2023-01-14 16:22 UTC
Labels: bug, playback
