### ISSUE TITLE
upnext start 30 sec before end of episode and start button

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#2282] opened 2022-11-21 18:53 UTC
### Describe the feature you'd like

upnext shows after the end of a episode you can select in settings howlong it displays in seconds
its much better it starts about 30 seconds before the end of a episode and we get the option to start now button or close
so we can skip the end credits

**Comment by nielsvanvelzen** [comment] 2022-11-21 21:01
Duplicate of #357

**Closed by nielsvanvelzen** 2022-11-21 21:01 UTC
Labels: enhancement
