### ISSUE TITLE
subtitles not complete

### ISSUE THREAD

**Issue by Josegg0** [jellyfin/jellyfin-androidtv#746] opened 2021-02-28 16:33 UTC
**Describe the bug**
 Subtitle with this format are not complete. In the next example, it just shows on screen the first line "este lugar se convertirá". 

312
00:16:49,092 --> 00:16:51,470
este lugar se convertirá

en un maldito zoológico.

**To Reproduce**

Play any show/movie with subtitles with this format.

**Expected behavior**
 It should show on screen the first line "este lugar se convertirá en un maldito zoológico.". This does not happen when using an external media player like vlc.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/67025623/109425621-22843d80-79b7-11eb-962c-6c0d133750a6.png)
![image](https://user-images.githubusercontent.com/67025623/109425845-6461b380-79b8-11eb-8998-967cc7016737.png)

**System (please complete the following information):**
 - Android TV or Fire TV version: android 10
 - Device manufacturer: google
 - Device model: chromecast with google tv
 - Jellyfin server version: 10.5.4

**Additional context**
This happens in android tv, android and pc.

**Comment by nielsvanvelzen** [comment] 2021-02-28 16:42
Duplicate of jellyfin/jellyfin/issues/5323

**Closed by nielsvanvelzen** 2021-02-28 16:42 UTC
Labels: bug
