### ISSUE TITLE
AndroidTV 5.1.1 The experience was terrible.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1473] opened 2022-02-27 04:55 UTC
### Describe the bug

0.13 beta2/3/4
Selecting ExoPlayer playback on AndroidTV 5.1.1 system will drop frames.
Select libVLC, terminate randomly for about 10 minutes.It looks like it's related to the transcoding progress, and the closer you get to the end of the movie, the shorter the termination gap.
There is no problem on android 7,9 systems. There is also no prompt for logs on the server.

### Application version

0.13 beta4

### Device information

android TV

### Android version

Android 5.1.1

### Jellyfin server version

10.8.0 alpha5

**Comment by mueslimak3r** [comment] 2022-02-27 06:02
Can you clarify "terminate randomly for about 20 minutes"?

**Comment by shaino** [comment] 2022-02-27 06:48
I'm sorry, I didn't make it clear.
Play continuously for more than 10 minutes, and the playback automatically terminates and returns to the movie introduction page. The time is uncertain between about 10-20 minutes.

**Comment by mueslimak3r** [comment] 2022-02-27 06:58
Can you provide the server log (not the ffmpeg log), and make sure to remove identifying info.

I think this is the same issue that's discussed later in the threads of #1339 and #1061

**Comment by shaino** [comment] 2022-02-27 07:22
I also see the above issue.
0.13beat seems to improve a lot.Old versions of the use of PGS subtitles caused frame drops.Now,it's ok!
Can the new version allow PGS subtitles to be burned on the server?
Later I'll test videos without PGS subtitles or with PGS subtitles off.

**Comment by mueslimak3r** [comment] 2022-02-27 07:26
> I also see the above issue.

So the issue(s) described above are not the same as the issue you're experiencing with libVLC?

> Can the new version allow PGS subtitles to be burned on the server?

This would need to be discussed in a separate issue

**Comment by shaino** [comment] 2022-02-27 07:42
It's strange that this kind of problem doesn't occur frequently on my android 7/9 device.
This issue occurs 100% of Android 5.1.1 devices.
You should have no default Exoplayer player before version 0.12. At that time, I used libVLC for a long time and did not have such problems.
Android 7/9 devices are good with libVLC. Android 5.1.1 devices are almost useless. (LibVLC dropped frame due to PGS subtitles, exoplayer playback dropped frame).
Maybe I didn't test enough, and I did more comparisons before I could comment on the above questions.

**Comment by shaino** [comment] 2022-02-27 08:05
I also submitted this issue because the apparent downtime after playing the video was shorter.
Near the end of the movie, the termination time is 10 minutes, 5 minutes, 3 minutes....
This issue seems to be related to server transcoding. It may be that the server transcoding ended sending an error message to the client.

**Comment by shaino** [comment] 2022-02-27 12:14
@mueslimak3r 
Android 5.1.1/7/9 using libVLC is the same issue in 0.13 beta4.
Playback crashes occur after the server has completed the full video transcoding.
Enabling PGS subtitles or not is independent of this issue.
I have enabled limit transcoding speed in the console. Unfortunately, when the client plays anywhere, the server continues to transcode to the end.Then issues appeared.Curiously, with exoplayer playback, the server will also transcode the full video, but it will not trigger the issue.

**Comment by mueslimak3r** [comment] 2022-02-28 00:09
Based on the descriptions you've provided, I'm going to close this as a duplicate of #1339
This way discussion can happen in one place instead of being split across more than one issue. Please do check in there with a summery of what you've described here.

If you think your issue with libVLC isn't a duplicate of #1339 , reply here with more information (ideally some logs too), and I'll re-open this issue.

**Closed by mueslimak3r** 2022-02-28 00:09 UTC
Labels: bug
