### ISSUE TITLE
[Feature Request] Integrate with new Google TV

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-androidtv#617] opened 2020-09-30 18:45 UTC
I don't know if this is beyond the purview of the Chromecast app, but it seems like it would be a lofty goal for Jellyfin to sit on the screen beside Netflix, Disney+, HBO Max, and Hulu on the screen of the new "Chromecast with Google TV" device that has just been announced.

[https://youtu.be/q2HSJHOMDyk?t=308](https://youtu.be/q2HSJHOMDyk?t=308)

I have no idea how this might happen, or if it is even possible -- maybe it's a completely separate app -- but I know that whoever reads this issue is probably smarter than me.  I'm sure there are several sub-areas of this issue, like search, genre browsing, recommendations, and just getting the app on there in the first place.

Maybe this more in the realm of the Android TV app, but I wanted to get this down in text.

Thanks for all you guys are doing!

**Comment by nielsvanvelzen** [comment] 2020-11-08 08:59
Although planned we have not started integrating the cast receiver yet. We are still working on our next release (0.12)

**Comment by ipenovich** [comment] 2021-01-05 16:17
I think this would come under this ticket, but I believe SteveDinn was referring to the way Android TV (which powers the UI on the new Chromecast) indexes content from within your video apps, so when you search for a title it will give you deep links to all the installed apps that offer the title. 

For example, if I search for Die Hard, it shows me the info card saying the title is available from Netflix (included with sub), Amazon (for £x.xx), and Google Play Movies (for £x.xx). If the Jellyfin app were searchable, it would be included if I had the title in my library. 

See the details here:
https://developer.android.com/training/tv/discovery

**Comment by nielsvanvelzen** [comment] 2021-01-05 16:25
Search integration is planned but not possible with our current codebase (need the new apiclient).

**Comment by SteveDinn** [comment] 2021-01-05 16:57
Yes, I've installed Jellyfin, and the android TV client works well on the Chromecast with Google TV, but search integration would be awesome.

**Comment by nielsvanvelzen** [comment] 2021-09-30 20:22
The pull request for search integration is #900.

**Comment by brianjmurrell** [comment] 2021-12-05 18:52
I think all of this is achieve with https://developer.android.com/training/tv/start/google-tv#content-discovery.  If I am not mistaken/misunderstanding.

But indeed, having all of JF content surfaced up to the main Google TV UI level would be awesome.

**Comment by nielsvanvelzen** [comment] 2021-12-06 12:03
The "Media Actions Feed" feature can't be used as this data is dynamic (depends on the Jellyfin server) instead of static (like a hosted service as Netflix).
The "Play Next" feature is already implemented in 0.11

**Comment by brianjmurrell** [comment] 2021-12-06 13:32
> The "Media Actions Feed" feature can't be used as this data is dynamic (depends on the Jellyfin server) instead of static (like a hosted service as Netflix).

I'm not really sure I see the distinction.  Content comes and goes on Netflix, just like it would on a Jellyfin server.  New content is added all of the time, and other content is removed as Netflix's license to provide it expires, etc.

So what is the practical difference?

> The "Play Next" feature is already implemented in 0.11

I'm not sure what you are referring to as "Play Next", but ultimately, I don't see any of my JF content surfaced to the Google TV UI at all and I am using 0.12.3.  I always have to open the JF app to see any of it.

**Comment by Xyz00777** [comment] 2021-12-06 16:38
I dont Know how the feature in Google works but JF caches most or many of the needes info on the local system or not? Couldn't we just use them somehow?

**Comment by brianjmurrell** [comment] 2021-12-06 17:47
> You need to upload a static JSON file to Google's cloud, there can be only one database per app. So no this is impossible for an app like Jellyfin.

Ahhh.  This is where the disconnect is.  I read _For Google to obtain your feed, you need to store the feed in a file and host the file in a location where Google can access it._ as the feed being on the local device.  As in JF stores the feed file locally and Google TV uses the locally stored feed file.  I can see how I may have misinterpreted that.

Being able to search and have recommendations, and generally just have content from a local media server surfaced to the Google TV UI seems like a GTV feature gap.  I wonder if this is something they have decided they will never support.

> It's the second item in the link you posted

Ahh.  Interesting.  I am not seeing this behaviour in 0.12.3 either.

Does that feature just pull all of the in-progress TV shows (i.e new episodes) from every JF user account or does a JF account have to be associated to the GTV user in some way?  If so, can multiple JF users be associated with a single GTV account?

**Comment by nielsvanvelzen** [comment] 2021-12-06 17:54
The Jellyfin (authentication) settings have an option to set the "system user". This is the account used for integrations like nextup/search.

I don't have a Google TV device myself so my only testing with it is trough the emulator which doesn't really work for me. I know that some functions of the Google TV launcher use a whitelist made by Google to only show content from certain (google approved) apps. It might be possible they did this for all functions and Jellyfin won't be able to integrate with the system.

**Comment by Xyz00777** [comment] 2021-12-06 18:01
Okay, when I understood it correct its at the moment not possible correct? Did anybody possible know a launcher who support these?

**Comment by brianjmurrell** [comment] 2021-12-06 18:25
> The Jellyfin (authentication) settings have an option to set the "system user". This is the account used for integrations like nextup/search.

I do have such a user.  I think.  This is the user that has access to the admin dashboard, yes?  Does this user/account need to be named in any special way?

**Comment by nielsvanvelzen** [comment] 2021-12-07 08:13
No the system user is the account used to make the API calls, so if "user x" is the primary user of your television you should set it to "user x". The default value (Most recently used) should be fine though.

**Comment by brianjmurrell** [comment] 2021-12-12 16:42
I'm afraid I'm not understanding your explanation of what the "system user" is.  What is "user x"?  Is that one of my Jellyfin server user accounts?

> you should set it to "user x".

Set it how?  This seems to need some "how to" type documentation as this is something that is going to affect most users is it not?

**Comment by phirestalker** [comment] 2021-12-21 19:37
Do we know if google fetches these media lists from their servers or if the Chromecast downloads them?
If the Chromecast downloads them, then each person running their own Jellyfin server could run a DNS proxy and redirect the request to a file generated by their local Jellyfin server.
If google downloads the list, will they do any Oauth authentication? If so, then Jellyfin team might offer a service for say $10 a year to host the list for each user and when Google authenticates as that user, the right file is downloaded.

Just some raw thoughts, maybe it will trigger someone smarter to find an amicable solution.

**Comment by anthonylavado** [comment] 2021-12-21 20:11
> Do we know if google fetches these media lists from their servers or if the Chromecast downloads them?

It can either be hosted by Google or elsewhere, but the issue is twofold:

1. It requires a full list of content for the application/service and is not customizable by user (even the example feed for a service like Netflix includes the setting of country/region availability)

2.  The Media Actions feed is only available by invitation from Google at this time


In this case, neither of those work for us. At best someone would have to write an app (on Amazon Echo devices these are "Skills"), that a user could invoke to search their own server. We wouldn't run one ourselves as we try to avoid centralization for something like that.

**Comment by brianjmurrell** [comment] 2022-11-28 13:22
Of course #2 is a show-stopper for now.

But when it's not, then #1 seems plausible, with the kind of DNS (or ip address -- at the border router) redirection described by @phirestalker describes.

**Comment by nielsvanvelzen** [comment] 2022-11-29 14:13
As mentioned before, we integrate with Android TV and that doesn't work with the Google TV launcher because of limitations we can't workaround. Closing the issue as completed. If you truly believe it's possible I look forward to your pull request.

**Closed by nielsvanvelzen** 2022-11-29 14:13 UTC
Labels: enhancement
