### ISSUE TITLE
[0.17.0 beta 3] Crashes when accessing TV guide

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3748] opened 2024-07-13 23:56 UTC
### Describe the bug

Click on TV guide app crashes.

### Logs

**No logs are sent to server**

07-14 09:29:06.668   290   376 E RHWC2   : failed on ioctl GDMA_GET_FENCE_INFO
07-14 09:29:06.670  2011  2011 D mira-P2PService: Failed to set WFD info with reason 2.
07-14 09:29:06.670  2011  2011 D mira-P2PService: isWifiP2pEnabled = true
07-14 09:29:06.670  2011  2011 D mira-P2PService: device rename fail
07-14 09:29:06.685   290   376 E RHWC2   : failed on ioctl GDMA_GET_FENCE_INFO
07-14 09:29:06.689  2656  2656 D ItemRowAdapterHelperKt: Creating items from 0 existing and 5 new, adapter size is 0
07-14 09:29:06.693  2656  2702 P Quality : 09 03 info 1720913340560 procName:org.jellyfin.androidtv.debug 1 what:149,obj:android.os.BinderProxy@85af129,target:android.app.ActivityThread$H callback:android.view.Choreographer$FrameDisplayEventReceiver,target:android.view.Choreographer$FrameHandler,maxWallTime:1196 latencyTime:1164,WallTime:35,normalLatencySlowTimes:10 $ $ $ $
07-14 09:29:06.693  2656  2656 W androidtv.debu: Accessing hidden method Landroid/view/KeyEvent;->isMediaSessionKey(I)Z (blacklist, linking, denied)
07-14 09:29:06.699  2656  2676 I androidtv.debu: Background concurrent copying GC freed 94156(3922KB) AllocSpace objects, 11(480KB) LOS objects, 49% free, 10005KB/19MB, paused 29.329ms total 939.743ms
07-14 09:29:06.700  2656  2676 P Quality : 07 02 block_gc block_gc androidtv.debug 2656 4017024 939
07-14 09:29:06.702   290   376 E RHWC2   : failed on ioctl GDMA_GET_FENCE_INFO

### Application version

0.17.0 beta 3

### Where did you install the app from?

Sideloaded APK

### Device information

NS

### Android version

Android 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment] 2024-07-14 12:21
Unable to reproduce. Please share (crash-)logs.

**Comment by nielsvanvelzen** [comment] 2024-07-16 12:46
There were some timezone issues that should be fixed in the next beta. Thanks for reporting.

**Comment by nielsvanvelzen** [comment] 2024-07-20 11:23
I've checked with multiple instances and the TV guide does not crash for me nor some of the other team members that verified it. I'd really need some more details (adb logs / reproduction steps / screenshots / video recordings) of the issue.

This guide may help with the logging part https://gist.github.com/nielsvanvelzen/96fd588194729d6845f2d5e414cffb8d

**Closed** 2024-07-23 15:53 UTC
Labels: bug
