### ISSUE TITLE
Crash when opening a media folder that contains RTP/MP4S-01 streaming codecs videos.

### ISSUE THREAD

**Issue by HoloByteus** [jellyfin/jellyfin-androidtv#2134] opened 2022-10-02 01:38 UTC
### Describe the bug

Jellyfin will crash when you attempt to open a media folder if it contains any videos with RTP or MP4S-01/2 codecs.  I'm not familiar with these codecs, they show up under mediainfo as Other like the following.  I've seen them listed as Type:  Scene descriptions and Hints with both RTP and MP4S-01 listed as codecs.  Removing the videos or Re-encoding with FFMPEG to just copy the Video/Audio streams resolves the problem.   I've had some of these videos for years and only recently have I noticed the issue which would lead to me suspect a recent change to the app may be at the root of the cause.   Unfortunately I don't have a video to share having re-encoded them but thought I'd make you aware hoping you're familiar with these codecs.

With MP4 videos:

Other #1
ID                                       : 2
Type                                     : Object description
Format                                   : System
Codec ID                                 : mp4s-01
Duration                                 : 1 s 0 ms
Encoded date                             : UTC 2016-01-11 23:22:37
Tagged date                              : UTC 2016-01-11 23:22:37

Other #2
ID                                       : 1
Type                                     : Scene description
Format                                   : System Core
Codec ID                                 : mp4s-02
Duration                                 : 1 s 0 ms
Encoded date                             : UTC 2016-01-11 23:22:37
Tagged date                              : UTC 2016-01-11 23:22:37

Other #3
ID                                       : 65736
Type                                     : Hint
Format                                   : RTP
Codec ID                                 : rtp 
Duration                                 : 15 s 0 ms
Encoded date                             : UTC 2016-01-11 23:22:37
Tagged date                              : UTC 2016-01-11 23:22:37

Other #4
ID                                       : 65636
Type                                     : Hint
Format                                   : RTP
Codec ID                                 : rtp 
Duration                                 : 15 s 168 ms
Bit rate mode                            : Variable
Encoded date                             : UTC 2016-01-11 23:22:37
Tagged date                              : UTC 2016-01-11 23:22:37

With WMV videos a Time code listed under Others in MediaInfo can cause the crash.

Other
Type                                                : Time code
Format                                            : WM TC
Time code of first frame                 : 01:00:00:00

### Application version

0.14.3

### Where did you install the app from?

Google Play

### Device information

Hisense 65H9F

### Android version

Android 9

### Jellyfin server version

10.8.5

**Comment by HoloByteus** [comment] 2022-10-02 02:17
Log file.
[upload_org.jellyfin.androidtv_0.14.3_20221002015508_40d3da5ad2604996a0e853d6d916ba41.log](https://github.com/jellyfin/jellyfin-androidtv/files/9691500/upload_org.jellyfin.androidtv_0.14.3_20221002015508_40d3da5ad2604996a0e853d6d916ba41.log)

**Comment by thornbill** [comment] 2022-10-02 04:15
Duplicate of #2125

**Closed** 2022-10-02 04:30 UTC
Labels: bug, duplicate
