### ISSUE TITLE
Grey bars when playing HDR content on Sony Bravia

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-androidtv#2967] opened 2023-08-14 05:38 UTC
### Describe the bug

1. Play HDR content
2. Profit

Was previously fixed in #369, but apparently this bug is back.

### Application version

0.16.0-beta2

### Where did you install the app from?

Google Play

### Device information

Sony Bravia X900F

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by viggy96** [comment] 2023-08-15 23:51
I see a total of 9 squares.

The top row has 7 in the following order:
black black black red black red black

The second row contains:
red black

All the "black" squares are completely black. No grey squares at all.

**Comment by nielsvanvelzen** [comment] 2023-08-17 19:26
Thanks for testing. I'm surprised they are proper black with this test app as the way some of those boxes are drawn are the exact same way as the Jellyfin app does. Since it only affects a select set of Sony Bravia devices it won't be a release blocker for 0.16, but I'll try to think about possible solutions.

**Comment by quietvoid** [comment] 2023-10-14 10:48
It's a bit annoying if this issue still exists, it used to be fixed by setting the app background transparent but maybe that was reverted since #369.

It was reverted in Kodi too, but since it's still only in the Alpha builds I haven't heard much from Sony TV owners if the issue is still present.

**Comment by nextlooper42** [comment] 2023-11-09 10:08
The issue still exists in latest beta. As mentioned, if the video is not perfect 16:9 material it will show somewhat brigts gray bars on bottom and the top where is no real video anymore - and it's extremely annoying.

Also can confirm this is problem on all Android Sony Bravia TV's - tested on 2018 model and on 2022 model.

It maybe worth to mention that this is not an issue in Kodi, where HDR content is shown as it should.

**Comment by nextlooper42** [comment] 2023-11-09 10:34
Here are two examples how it looks on Sony Bravia XF9005 running Android 9 and latest update from Sony.

This is how your test blackdroid app, you can also see approximetely these colours in real life - deep black and red squares with grey bacground.
![sony_app](https://github.com/jellyfin/jellyfin-androidtv/assets/29764734/a6cf8e53-f22a-4e55-9fa0-65756e379a49)

And this is how Jellyfin TV show HDR content (blue suppose to be video in not perfect 16:9 ratio)
![sony_hdrcontext](https://github.com/jellyfin/jellyfin-androidtv/assets/29764734/b2b21010-8ffe-4a44-90ab-c94c31d2f468)

I can personally test any build on Sony Bravia XF9005 if you want to test something.

**Comment by nielsvanvelzen** [comment] 2023-11-15 14:34
Updated the test app (https://github.com/nielsvanvelzen/blackdroid/commit/a2b8ba93d41de802c14957e321cf91465b665a31) to add a sample HDR video, can you guys test again and see if it makes any difference? [app-debug.zip](https://github.com/jellyfin/jellyfin-androidtv/files/13365937/app-debug.zip)

**Comment by viggy96** [comment] 2023-11-20 02:04
Apologies for the delay. The video square for me appears to have a grey background.

**Comment by nextlooper42** [comment] 2024-02-02 09:31
It's still present in debug app. Also it's still problem in normal app updated to latest version.

![20240120_022346](https://github.com/jellyfin/jellyfin-androidtv/assets/29764734/02dba2f6-08ae-462e-9952-bd3654de6bc7)

**Comment by nielsvanvelzen** [comment] 2024-02-03 14:12
Unfortunately I have no other ideas to try right now. Without a Sony TV to test it is extremely hard to workaround a Sony-specific issue.

**Comment by AppleGuyBerlin** [comment] 2024-02-14 21:58
Hi, 

I wanted to add to this thread and say that I also have the same issue with my Sony KD-55AG8 Android TV. 

It's super annoying and it takes away all the joy of going through the trouble of downloading a 25gb file, watching on an OLED tv to only have the experience ruined with the rather kinda bright grey bars on the top and bottom of the screen. 

Please please please fix the issue! 🙏🏼🙏🏼🙏🏼

[image](https://github.com/jellyfin/jellyfin-androidtv/assets/46817747/289aca0b-e089-4539-b419-f9a5d1f464a0)

**Comment by nielsvanvelzen** [comment] 2024-03-04 18:49
(quoting partially from my comment on #3411)

I've made a potential fix in #3411. I've updated the "Muted Purple" theme to have a very obvious pink background. If someone encountering this issue would test it for me we can finally solve the bug, please test:

1. The pink background showing while browsing etc.
2. The background being properly black during video playback

If this fix work I'll make sure it will be in the next 0.16 release.

The debug version of the app can be downloaded by opening the [pull request](https://github.com/jellyfin/jellyfin-androidtv/pull/3411), going to the "checks" tab, pressing on "app / build" on the left side and then click on "build-artifacts" to download a zip, you can then sideload the apk file with "debug" in the name to your device.

**Comment by JPVenson** [comment] 2024-03-08 15:28
Hey @viggy96 

Could you please share the media info of the file you were trying to play?

**Comment by TimGels** [comment] 2024-03-08 16:14
Tested this on a `kd-49xe8005`. The normal app has the bug and the bars are grey. The debug PR artifact has black bars and does not appear to have the issue for me.

**Closed** 2024-03-10 08:35 UTC
Labels: bug, confirmed

**Comment by viggy96** [comment] 2024-03-11 02:38
@nielsvanvelzen I don't see a pink background when browsing with the muted purple theme and when browsing settings menu, some menus are transparent in your version for me. However, playback shows a black background as expected.

**Comment by nielsvanvelzen** [comment] 2024-03-11 07:51
I removed the pink background so I could merge the pull request as @TimGels confirmed the fix worked.

>  some menus are transparent in your version for me

Can you elaborate? Does something with the menus not look right?

**Comment by viggy96** [comment] 2024-03-11 15:11
Yes, for example in the app theme selection.

The background of that panel is transparent.

**Comment by nielsvanvelzen** [comment] 2024-03-11 16:29
Thanks, fixed that now.
