### ISSUE TITLE
Feature request: Focus on the resume button when in a movie/show page

### ISSUE THREAD

**Issue by protik77** [jellyfin/jellyfin-androidtv#194] opened 2019-11-11 17:48 UTC
At the moment, when selecting any movie or show from "Continue watching" menu, the focus is on the text information panel. Which means pressing select button there expands the text information. This is a bit misleading. If I'm resuming the movie, I already know the text information. 

In order to resume the movie, one has to press `down`, then press `resume` to resume a movie or TV show. Which means two more button press to resume. Is it feasible to put the focus on the resume button directly to reduce number of button press?

**Comment by thornbill** [comment] 2019-11-12 02:28
Duplicate of #100

**Closed by thornbill** 2019-11-12 02:28 UTC
