### ISSUE TITLE
Duplicate playback

### ISSUE THREAD

**Issue by azeunkn0wn** [jellyfin/jellyfin-androidtv#2865] opened 2023-07-01 17:53 UTC
### Describe the bug

1. play a movie/episode
2. finish the video or press back to end playback 

expected:
return to jellyfin "Play Next" screen or media details screen. (marked as watched if you finished the video)

actual:
the video will play again from where it started. (from resume time or 0:00:00).
you have press back again to return to jellyfin.
the "watched" status will not be marked as watched.

more info that would really be helpful:
only happens when external player is prefered and when you have assigned a default player.
I recreate the bug with MX player, MX Player pro, and VLC.
this bug won't occur if you don't assign a default player (always "open with")

### Application version

0.15.10

### Where did you install the app from?

Google Play

### Device information

Somy Bravia 4K UR2

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2023-07-01 18:36
Sounds like a duplicate of #2426

**Closed by nielsvanvelzen** 2023-07-01 18:36 UTC
Labels: bug
