### ISSUE TITLE
Jellyfin can’t log in anymore in a fire TV 

### ISSUE THREAD

**Issue by pbranly** [jellyfin/jellyfin-androidtv#2830] opened 2023-05-06 05:59 UTC
### Please describe your bug

From the last versions given by Amazon, I can’t log in anymore. Either with quick method or with login password, the answer is always bad user name or password 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:firetv 
- Linux Kernel:
- Virtualization:
- Clients:10.8.10
- Browser:applet 0.15.9
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravardhanreddy** [comment] 2023-06-18 19:36
Facing the exact same issue. This used to work few months ago and now when I enter the server address, it says Unable to connect to server with the URLs it tried and https;//jellyfin.mydomain.com says SSL handshake failed.

I am using a fire tv stick 4k and the latest jellyfin app available on the fire tv store. I am exposing my server to the internet using cloudflare tunnels. I do have TLS v1.3 enabled but the minimum TLS version is set to TLS V1.0. 

When I monitor the server logs in portainer its not even creating any logs. Maybe its not able to negotiate a connection with Cloudflare in the first place? It works on my android phone and also from the browser. Not sure whats wrong with the fire tv client.

**Comment by xsteadfastx** [comment] 2023-06-21 09:49
im glad im not alone on this. happens since last week or so.

**Comment by nielsvanvelzen** [comment] 2023-06-21 09:51
Closing as duplicate of #2830.

**Closed by nielsvanvelzen** 2023-06-21 09:51 UTC
Labels: bug
