### ISSUE TITLE
empty library on android tv

### ISSUE THREAD

**Issue by albebert** [jellyfin/jellyfin-androidtv#3064] opened 2023-09-22 08:25 UTC
### Describe the bug

On android TV library are empty. All works great on web version, windows 11 app and android app.

Collections show movies but can't enter into it. 

have the same result with 0.14 from Google playstore and Amazon Store on a xiaomi 3S Tv and a fire stick. Same result on Mi TV with 0.16 beta version. 
picture for example : 

![image](https://github.com/jellyfin/jellyfin-androidtv/assets/1460379/044cad84-415e-492d-a1fc-3caf0d869fd4)

i've installed the 0.16 debug version, i d'ont know if i can export logs from it but if it's possible i can add logs without problem.

i can share a video that show the issue. I past log but nothing seems relevant.

### Logs

[2023-09-22 03:40:44.895 +02:00] [INF] Watching directory "/media/tr-data"
[2023-09-22 10:22:50.095 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous.mkv"
[2023-09-22 10:22:50.096 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Indiana Jones et le Cadran de la Destinée [FR-EN] (2023).mkv"
[2023-09-22 10:22:50.104 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/julie21/Spider-Man.Homecoming.2017.MULTI.VFF.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-HDForever.mkv"
[2023-09-22 10:23:09.232 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous.mkv"
[2023-09-22 10:23:09.233 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Indiana Jones et le Cadran de la Destinée [FR-EN] (2023).mkv"
[2023-09-22 10:23:17.214 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous.mkv"
[2023-09-22 10:23:17.215 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Indiana Jones et le Cadran de la Destinée [FR-EN] (2023).mkv"
[2023-09-22 10:23:32.633 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous/Meg.2.The.Trench.2023.MULTi.1080p.AMZN.WEB-DL.DDP5.1.H265-Anonymous.mkv"
[2023-09-22 10:23:32.635 +02:00] [WRN] Unable to find linked item at path "/media/tr-data/brico24/Indiana Jones et le Cadran de la Destinée [FR-EN] (2023).mkv"

### Application version

0.14.0

### Where did you install the app from?

Google Play

### Device information

MiTV-MSSP3 and Amazon AFTSSS

### Android version

Android 9, FireOS 7.6.5.2

### Jellyfin server version

10.8.1

**Comment by albebert** [comment] 2023-09-22 08:41
OK i've found the problem ! 

my Web Application Firewal in front of jellyfin server reject lot of queries. 

i don't know why there are no problem on other apps. 

perhaps the auth method that is deffirent (login/password on all execpt on android TV that use "speed connection"

**Comment by nielsvanvelzen** [comment] 2023-09-22 19:01
Good to hear you've found (and fixed) the issue. This might be caused by our mix of two HTTP libraries to access the server. The view in the screenshot is using the old stack.

Closing as the issue is fixed.

**Closed by nielsvanvelzen** 2023-09-22 19:01 UTC
Labels: bug

**Comment by albebert** [comment] 2023-09-22 22:53
for information, exclude "bad sql query" from the WAF do the job.
