### ISSUE TITLE
Nullpointer Exception when playing a media file via merge-versions plugin and selecting another file first

### ISSUE THREAD

**Issue by PinPhreek** [jellyfin/jellyfin-androidtv#3910] opened 2024-08-18 23:30 UTC
### Describe the bug

1. Go to the media you want to play
2. go on the versions and select another version, I'm doing this with anime, so I select the original with subtitles file
3. The App crashes

### Logs

---
client: Jellyfin for Android TV
client_version: 0.17.3
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.updatePlayState()' on a null object reference
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.setPlayPauseActionState(CustomPlaybackOverlayFragment.java:1241)
	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause(CustomPlaybackOverlayFragment.java:706)
	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

```  
***Logcat***: 
```log
08-19 00:23:09.183 D/LeanbackChannelWorker(20478): Updating channel content://android.media.tv/channel/52
08-19 00:23:09.245 D/ItemRowAdapterHelperKt(20478): Creating items from 0 existing and 50 new, adapter size is 0
08-19 00:23:09.262 D/LeanbackChannelWorker(20478): Updating channel content://android.media.tv/channel/50
08-19 00:23:09.569 D/LeanbackChannelWorker(20478): Updating channel content://android.media.tv/channel/53
08-19 00:23:09.809 D/LeanbackChannelWorker(20478): Updating channel content://android.media.tv/channel/54
08-19 00:23:09.926 D/LeanbackChannelWorker(20478): Updating channel content://android.media.tv/channel/51
08-19 00:23:09.992 I/WM-WorkerWrapper(20478): Worker result SUCCESS for Work [ id=482c078b-2fc5-4cc2-b18a-29d6a6cea2cf, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
08-19 00:23:17.498 D/ItemLauncher(20478): Item selected: Zögern (Episode)
08-19 00:23:17.499 D/NavigationRepositoryImpl(20478): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment (Kotlin reflection is not available), arguments=Bundle[{ItemId=f2fe254f-4e67-f253-087d-07990e7fa00d}]) (via navigate function)
08-19 00:23:17.508 I/org.jellyfin.sdk.api.sockets.DefaultSocketApi(20478): Subscription count changed to 15
08-19 00:23:17.509 I/org.jellyfin.sdk.api.sockets.DefaultSocketApi(20478): Subscription count changed to 14
08-19 00:23:17.561 I/org.jellyfin.sdk.api.ktor.KtorClient(20478): GET http://192.168.3.3:8096/Items/f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.562 V/io.ktor.client.plugins.HttpPlainText(20478): Adding Accept-Charset=UTF-8 to http://192.168.3.3:8096/Items/f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.580 W/RecyclerView(20478): No adapter attached; skipping layout
08-19 00:23:17.583 V/io.ktor.client.plugins.HttpCallValidator(20478): Validating response for request http://192.168.3.3:8096/Items/f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.583 V/io.ktor.client.plugins.DefaultResponseValidation(20478): Skipping default response validation for http://192.168.3.3:8096/Items/f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.593 V/io.ktor.client.plugins.defaultTransformers(20478): Transformed with default transformers response body for http://192.168.3.3:8096/Items/f2fe254f-4e67-f253-087d-07990e7fa00d to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
08-19 00:23:17.658 I/org.jellyfin.sdk.api.ktor.KtorClient(20478): GET http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?adjacentTo=f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.659 V/io.ktor.client.plugins.HttpPlainText(20478): Adding Accept-Charset=UTF-8 to http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?adjacentTo=f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.666 D/FullDetailsFragment(20478): Item type: Episode
08-19 00:23:17.674 I/org.jellyfin.sdk.api.ktor.KtorClient(20478): GET http://192.168.3.3:8096/Items?startIndex=7&limit=20&parentId=80bbec26-5bfd-5701-3578-f6472c2de25f&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true
08-19 00:23:17.676 V/io.ktor.client.plugins.HttpPlainText(20478): Adding Accept-Charset=UTF-8 to http://192.168.3.3:8096/Items?startIndex=7&limit=20&parentId=80bbec26-5bfd-5701-3578-f6472c2de25f&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true
08-19 00:23:17.873 V/io.ktor.client.plugins.HttpCallValidator(20478): Validating response for request http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?adjacentTo=f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.873 V/io.ktor.client.plugins.DefaultResponseValidation(20478): Skipping default response validation for http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?adjacentTo=f2fe254f-4e67-f253-087d-07990e7fa00d
08-19 00:23:17.927 V/io.ktor.client.plugins.HttpCallValidator(20478): Validating response for request http://192.168.3.3:8096/Items?startIndex=7&limit=20&parentId=80bbec26-5bfd-5701-3578-f6472c2de25f&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true
08-19 00:23:17.927 V/io.ktor.client.plugins.DefaultResponseValidation(20478): Skipping default response validation for http://192.168.3.3:8096/Items?startIndex=7&limit=20&parentId=80bbec26-5bfd-5701-3578-f6472c2de25f&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true
08-19 00:23:17.932 V/io.ktor.client.plugins.defaultTransformers(20478): Transformed with default transformers response body for http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?adjacentTo=f2fe254f-4e67-f253-087d-07990e7fa00d to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
08-19 00:23:17.955 I/lyfin.androidt(20478): Background concurrent copying GC freed 107074(6008KB) AllocSpace objects, 93(2244KB) LOS objects, 49% free, 7277KB/14MB, paused 343us total 161.151ms
08-19 00:23:17.996 V/io.ktor.client.plugins.defaultTransformers(20478): Transformed with default transformers response body for http://192.168.3.3:8096/Items?startIndex=7&limit=20&parentId=80bbec26-5bfd-5701-3578-f6472c2de25f&fields=PrimaryImageAspectRatio&fields=Overview&fields=ItemCounts&fields=DisplayPreferencesId&fields=ChildCount&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
08-19 00:23:18.023 D/ItemRowAdapterHelperKt(20478): Creating items from 0 existing and 5 new, adapter size is 0
08-19 00:23:18.326 D/FullDetailsFragment(20478): current time 1724019798326 last playback event time null last refresh time 1724019797665
08-19 00:23:19.684 D/mali_winsys(20478): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-19 00:23:19.706 D/gralloc (20478): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
08-19 00:23:19.718 D/gralloc (20478): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
08-19 00:23:19.726 D/gralloc (20478): mali_gralloc_select_format: req_format=0x00000001, usage=0x20000b00, req_base_format=0x1, alloc_format=0x8700000001, internal_format=0x8700000001
08-19 00:23:21.315 I/org.jellyfin.sdk.api.ktor.KtorClient(20478): GET http://192.168.3.3:8096/Items/46dc6a2b-5854-1895-1a1d-f4f6ba625129
08-19 00:23:21.316 V/io.ktor.client.plugins.HttpPlainText(20478): Adding Accept-Charset=UTF-8 to http://192.168.3.3:8096/Items/46dc6a2b-5854-1895-1a1d-f4f6ba625129
08-19 00:23:21.330 V/io.ktor.client.plugins.HttpCallValidator(20478): Validating response for request http://192.168.3.3:8096/Items/46dc6a2b-5854-1895-1a1d-f4f6ba625129
08-19 00:23:21.330 V/io.ktor.client.plugins.DefaultResponseValidation(20478): Skipping default response validation for http://192.168.3.3:8096/Items/46dc6a2b-5854-1895-1a1d-f4f6ba625129
08-19 00:23:21.334 V/io.ktor.client.plugins.defaultTransformers(20478): Transformed with default transformers response body for http://192.168.3.3:8096/Items/46dc6a2b-5854-1895-1a1d-f4f6ba625129 to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
08-19 00:23:21.660 W/libEGL  (20478): EGLNativeWindowType 0xba57cf48 disconnect failed
08-19 00:23:23.158 I/org.jellyfin.sdk.api.ktor.KtorClient(20478): GET http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&isMissing=false&startItemId=46dc6a2b-5854-1895-1a1d-f4f6ba625129&limit=150
08-19 00:23:23.160 V/io.ktor.client.plugins.HttpPlainText(20478): Adding Accept-Charset=UTF-8 to http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&isMissing=false&startItemId=46dc6a2b-5854-1895-1a1d-f4f6ba625129&limit=150
08-19 00:23:23.175 V/io.ktor.client.plugins.HttpCallValidator(20478): Validating response for request http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&isMissing=false&startItemId=46dc6a2b-5854-1895-1a1d-f4f6ba625129&limit=150
08-19 00:23:23.175 V/io.ktor.client.plugins.DefaultResponseValidation(20478): Skipping default response validation for http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&isMissing=false&startItemId=46dc6a2b-5854-1895-1a1d-f4f6ba625129&limit=150
08-19 00:23:23.178 V/io.ktor.client.plugins.defaultTransformers(20478): Transformed with default transformers response body for http://192.168.3.3:8096/Shows/39423d00-57b4-082d-032a-a9fcf2ee0447/Episodes?fields=MediaSources&fields=MediaStreams&fields=Chapters&fields=Path&fields=Overview&fields=PrimaryImageAspectRatio&fields=ChildCount&isMissing=false&startItemId=46dc6a2b-5854-1895-1a1d-f4f6ba625129&limit=150 to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
08-19 00:23:23.182 D/NavigationRepositoryImpl(20478): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=646086}]) (via navigate function)
08-19 00:23:23.189 D/DefaultPlayerQueueState(20478): Queue changed, setting index to 0
08-19 00:23:23.196 D/NavigationRepositoryImpl(20478): Navigating back
08-19 00:23:23.249 W/LeanbackOverlayFragment(20478): PlaybackController is null, skipping initialization.
08-19 00:23:23.299 D/NavigationRepositoryImpl(20478): Navigating back
08-19 00:23:23.302 D/AndroidRuntime(20478): Shutting down VM
--------- beginning of crash
08-19 00:23:23.303 E/AndroidRuntime(20478): FATAL EXCEPTION: main
08-19 00:23:23.303 E/AndroidRuntime(20478): Process: org.jellyfin.androidtv, PID: 20478
08-19 00:23:23.303 E/AndroidRuntime(20478): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.updatePlayState()' on a null object reference
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.setPlayPauseActionState(CustomPlaybackOverlayFragment.java:1241)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause(CustomPlaybackOverlayFragment.java:706)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at android.os.Handler.handleCallback(Handler.java:883)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at android.os.Looper.loop(Looper.java:214)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at java.lang.reflect.Method.invoke(Native Method)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-19 00:23:23.303 E/AndroidRuntime(20478): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
08-19 00:23:23.303 E/ACRA    (20478): ACRA caught a NullPointerException for org.jellyfin.androidtv
08-19 00:23:23.303 E/ACRA    (20478): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.updatePlayState()' on a null object reference
08-19 00:23:23.303 E/ACRA    (20478): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.setPlayPauseActionState(CustomPlaybackOverlayFragment.java:1241)
08-19 00:23:23.303 E/ACRA    (20478): 	at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onPause(CustomPlaybackOverlayFragment.java:706)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2155)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
08-19 00:23:23.303 E/ACRA    (20478): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)
08-19 00:23:23.303 E/ACRA    (20478): 	at android.os.Handler.handleCallback(Handler.java:883)
08-19 00:23:23.303 E/ACRA    (20478): 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-19 00:23:23.303 E/ACRA    (20478): 	at android.os.Looper.loop(Looper.java:214)
08-19 00:23:23.303 E/ACRA    (20478): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-19 00:23:23.303 E/ACRA    (20478): 	at java.lang.reflect.Method.invoke(Native Method)
08-19 00:23:23.303 E/ACRA    (20478): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-19 00:23:23.303 E/ACRA    (20478): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
08-19 00:23:23.303 D/ACRA    (20478): Building report
08-19 00:23:23.304 D/ACRA    (20478): Starting collectors with priority FIRST
08-19 00:23:23.305 D/ACRA    (20478): Calling collector org.acra.collector.DropBoxCollector
08-19 00:23:23.305 D/ACRA    (20478): Calling collector org.acra.collector.LogCatCollector
08-19 00:23:23.305 D/ACRA    (20478): Collector org.acra.collector.DropBoxCollector completed
08-19 00:23:23.305 D/ACRA    (20478): Calling collector org.acra.collector.StacktraceCollector
08-19 00:23:23.305 D/ACRA    (20478): Collector org.acra.collector.StacktraceCollector completed
08-19 00:23:23.309 D/ACRA    (20478): Retrieving logcat output (buffer:default)...
08-19 00:23:23.317 E/libc    ( 9891): Access denied finding property "persist.vendor.system.svp.dbg.loglevel"

```  

### App information

***App version***: `0.17.3` (`170399`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mt5895","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_VH21","DISPLAY":"BRAVIA_VH21_M_EU-user 10 QTG3.200305.006.S362 674801 release-keys","FINGERPRINT":"Sony\/BRAVIA_VH21_M_EU\/BRAVIA_VH21:10\/QTG3.200305.006.S362\/674801:user\/release-keys","HARDWARE":"mt5895","HOST":"BuildHost721","ID":"QTG3.200305.006.S362","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA 4K VH21","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"BRAVIA_VH21_M_EU","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1698890294000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":29,"INCREMENTAL":"674801","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2023-09-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":170399,"VERSION_NAME":"0.17.3"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_VH21_M_EU`  
***Device model***: `BRAVIA 4K VH21`  

### Crash information

***Start time***: `2024-08-19T00:16:42.906+02:00`  
***Crash time***: `2024-08-19T00:23:23.346+02:00`  

### FFmpeg logs

```shell
There haven't been ffmpeg logs, so I can't provide them here.
```

### Media info of the file

```shell
ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Blue Exorcist - S03E07 - Hesitatione - OmU.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.39.101
  Duration: 00:23:40.09, start: 0.000000, bitrate: 1371 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 1201 kb/s, 23.98 fps, 23.98 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 162 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

### Application version

0.17.3

### Device information

BRAVIA 4K VH21

### Android version

Android 10

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment] 2024-08-20 11:36
I'm unable to reproduce this issue but from my understanding the issue is that you have multiple episodes merged into one item (with a third-party plugin), and this will have the app show the version select. Then when you change the version to something different from the default and playing the item it fails?

It might be fixed with #3915, if you feel comfortable testing that you can find instructions here:
https://gist.github.com/nielsvanvelzen/96fd588194729d6845f2d5e414cffb8d

**Closed** 2024-08-20 14:44 UTC
Labels: bug, playback
