### ISSUE TITLE
Subtitles set to "none" being ignored by some movies

### ISSUE THREAD

**Issue by rlsmntr** [jellyfin/jellyfin-androidtv#303] opened 2020-02-06 03:43 UTC
Currently have some movies that even though subtitles are set to none the "default" ones not Forced ones play.  I can not disable subtitles on some files.  Even manually selecting "none" does not resolve it. This issue is not present on the same media on android or web browser just android tv.

**Comment by thornbill** [comment] 2020-02-06 04:04
If you enable subtitles do you see them twice? I have a feeling this is the same issue as #290.

**Comment by rlsmntr** [comment] 2020-02-06 04:14
I got a "unable to load subtitles" but yes, it could be similar.  I just tried libvlc instead of exoplayer and this issue went away (cant get subtitles to play at all using libvlc).  The way the subtitles being displayed it looks like this is sort of related to #290

**Comment by rlsmntr** [comment] 2020-02-06 04:24
Going to add that if I switch them over to a different subtitle track that plays instead.  Going back to "none" doesn't disable them it falls back to "default".

**Comment by nielsvanvelzen** [comment] 2020-02-06 10:33
Closing this issue in favor of #290, as they are caused by the same problem

**Closed by nielsvanvelzen** 2020-02-06 10:33 UTC
Labels: bug
