### ISSUE TITLE
Queueing music using Jellyfin mobile app or web as remote results in only the first track being added and nothing else

### ISSUE THREAD

**Issue by bjlanger** [jellyfin/jellyfin-androidtv#4358] opened 2024-12-30 21:28 UTC
### Describe the bug

1. Connect to Android TV Jellyfin via mobile app or web.
2. Attempt to add an album, artist, playlist to queue
3. Browse the queue and see that only one track is there. This also sometimes results in the queue being blank on the device acting as the remote or it displays what was last queued and you cannot remove it. https://github.com/user-attachments/assets/071eb03c-d7c2-4f6d-ade3-fc60ce052ba2

### Logs

[Jellyfin_music_weirdness.txt](https://github.com/user-attachments/files/18277833/Jellyfin_music_weirdness.txt)
[Log.txt](https://github.com/user-attachments/files/18277834/Log.txt)

### Application version

18.2

### Where did you install the app from?

Google Play

### Device information

Hisense SmartTV 4K FFM

### Android version

Android 12

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment] 2024-12-31 10:36
We do not currently support this. Closing as duplicate of #4263

**Closed by nielsvanvelzen** 2024-12-31 10:36 UTC
Labels: bug
