### ISSUE TITLE
Black screen with audio in native player, but working with VLC

### ISSUE THREAD

**Issue by suncokret12** [jellyfin/jellyfin-androidtv#4185] opened 2024-11-09 02:15 UTC
### Describe the bug

I'm a first-time user and installed the latest beta app on my TV. When I play 4k movies with Dolby and HDR, I get a black screen with only audio; however, if I go into the options and choose the external player option, then play the movie with VLC, it works just fine, but it doesn't work with the native player. My TV supports Dolby and HDR10. I have transcoding disabled because it's not supported on my seedbox, but I shouldn't need it. Also, if I check on the web client, I can see that the message that the media is playing fine under active devices, and no transcoding is required. Also, I switched from the Plex free version, and everything worked fine there without transcoding.

### FFmpeg logs

```shell

```

### Media info of the file

```shell
Container: mkv

Size: 120185 MB

Video
Title: 4K HEVC Dolby Vision Profile 7.6 (HDR10)
Codec: HEVC
AVC: No
Profile: Main 10
Level: 153
Resolution: 3840x2160
Aspect ratio: 16:9
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 73634 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
DV title: Dolby Vision Profile 7.6 (HDR10)
DV version major: 1
DV version minor: 0
DV profile: 7
DV level: 6
DV rpu preset flag: 1
DV el preset flag: 1
DV bl preset flag: 1
DV bl signal compatibility id: 6
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: TrueHD Atmos 7.1 - English - Dolby TrueHD + Dolby Atmos - Default
Language: eng
Codec: TRUEHD
AVC: No
Profile: Dolby TrueHD + Dolby Atmos
Layout: 7.1
Channels: 8 ch
Bitrate: 2995 kbps
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No

Audio
Title: AC-3 5.1-EX - English - Dolby Digital
Language: eng
Codec: AC3
AVC: No
Layout: 5.1
Channels: 6 ch
Bitrate: 448 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Commentary by Peter Jackson/Fran Walsh/Philippa Boyens - English - Dolby Digital - Stereo
Language: eng
Codec: AC3
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Commentary by Grant Major/Ngila Dickson/Richard Taylor/Alan Lee/John Howe/Dan Hennah/Chris Hennah/Tania Rodger - English - Dolby Digital - Stereo
Language: eng
Codec: AC3
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Commentary by Barrie Osborn/Mark Ordesky/Andrew Lesnie/John Gilbert/Rick Porras/Howard Shore/Jim Rygiel/Ethan van der Ryn/Mike Hopkins/Randy Cook/Christian Rivers/Brian Vant Hul/Alex Funke - English - Dolby Digital - Stereo
Language: eng
Codec: AC3
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Commentary by Elijah Wood/Ian McKellen/Liv Tyler/Sean Astin/John Rhys-Davies/Billy Boyd/Dominic Monaghan/Orlando Bloom/Christopher Lee/Sean Bean - English - Dolby Digital - Stereo
Language: eng
Codec: AC3
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: English (SDH) - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Cantonese) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Traditional) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Czech - PGSSUB
Language: cze
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Danish - PGSSUB
Language: dan
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Dutch - PGSSUB
Language: dut
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Finnish - PGSSUB
Language: fin
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French - PGSSUB
Language: fre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: German (SDH) - PGSSUB
Language: ger
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Greek - PGSSUB
Language: gre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Hebrew - PGSSUB
Language: heb
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Hungarian - PGSSUB
Language: hun
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Icelandic - PGSSUB
Language: ice
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Italian (SDH) - PGSSUB
Language: ita
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Japanese - PGSSUB
Language: jpn
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Korean - PGSSUB
Language: kor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Norwegian - PGSSUB
Language: nor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Polish - PGSSUB
Language: pol
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Portuguese (Brazilian) - PGSSUB
Language: por
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Portuguese (Iberian) - PGSSUB
Language: por
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Romanian - Rum - PGSSUB
Language: rum
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Russian - PGSSUB
Language: rus
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Spanish (Castilian) - PGSSUB
Language: spa
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Spanish (Latin American) - PGSSUB
Language: spa
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Swedish - PGSSUB
Language: swe
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Thai - PGSSUB
Language: tha
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Turkish - PGSSUB
Language: tur
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: English (Commentary #1) - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Commentary #1) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Dutch (Commentary #1) - PGSSUB
Language: dut
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French (Commentary #1) - PGSSUB
Language: fre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Italian (Commentary #1) - PGSSUB
Language: ita
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Korean (Commentary #1) - PGSSUB
Language: kor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: English (Commentary #2) - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Commentary #2) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Dutch (Commentary #2) - PGSSUB
Language: dut
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French (Commentary #2) - PGSSUB
Language: fre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Italian (Commentary #2) - PGSSUB
Language: ita
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Korean (Commentary #2) - PGSSUB
Language: kor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: English (Commentary #3) - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Commentary #3) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Dutch (Commentary #3) - PGSSUB
Language: dut
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French (Commentary #3) - PGSSUB
Language: fre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Italian (Commentary #3) - PGSSUB
Language: ita
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Korean (Commentary #3) - PGSSUB
Language: kor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: English (Commentary #4) - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Chinese (Commentary #4) - PGSSUB
Language: chi
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Dutch (Commentary #4) - PGSSUB
Language: dut
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: French (Commentary #4) - PGSSUB
Language: fre
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Italian (Commentary #4) - PGSSUB
Language: ita
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: Korean (Commentary #4) - PGSSUB
Language: kor
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No
```

### Application version

0.18.2

### Device information

VOX TV

### Android version

Android 9

### Jellyfin server version

10.10.1

**Comment by nielsvanvelzen** [comment] 2024-11-09 09:30
Duplicate of #3817 - additionally the mentioned app version does not exist.

**Closed by nielsvanvelzen** 2024-11-09 09:30 UTC
Labels: bug, playback
