### ISSUE TITLE
Live TV issues (TV Guide and playback)

### ISSUE THREAD

**Issue by SystemsAndOutsourcing** [jellyfin/jellyfin-androidtv#61] opened 2019-03-02 18:28 UTC
I'm using the amazon beta 3 version on a Fire TV stick.  TV Guide never displays, just shows "Loading...".  Weirdly, TV Guide works fine on the beta 6 android client but that version is basically unusable navigation-wise on a Fire TV stick.  Seemingly no explanation of what the issue is in the logs.

Also, when tuning to channels, for about the first minute it plays a few seconds then loops / jumps back to the start.  That does seem to sort itself out after a while but obviously hardly ideal.  Again, nothing in the logs to indicate what's going on, otherwise I'd post a snippet...

**Comment by poolco1** [comment] 2019-03-04 16:52
> Also, when tuning to channels, for about the first minute it plays a few seconds then loops / jumps back to the start.

I too have had this same experience, although doesn't affect all the channels I watch. Some are perfectly fine, others are unwatchable.

**Comment by thornbill** [comment] 2019-03-05 04:54
We just released a version of the app (beta 4) which includes an update to the base version of the app. These changes resolved a lot of the playback issues that I was seeing in my testing. It's possible a fix for your issues were included in the update, so please test the new version and let us know! If the issue is still present, any additional information about your Live TV setup could be helpful. Thanks!

**Comment by 3kk0** [comment] 2019-03-14 13:50
Still seems to be doing it with the new version. It appears to only happen on certain channels for me. That, and some channels outright fail to load with an error 500.

**Comment by thornbill** [comment] 2020-01-08 04:18
Can anyone confirm if this is still an issue? We have fixed a lot of issues with live TV since this was opened.

**Comment by thornbill** [comment] 2020-02-19 04:13
Closing since no one has confirmed this is still an issue. If anyone is still experiencing this, let us know!

**Closed by thornbill** 2020-02-19 04:13 UTC
Labels: bug, question
