### ISSUE TITLE
Jellyfin 0.15.3 still appears leaving an item puts the "cursor" back to the first item of the library

### ISSUE THREAD

**Issue by Soizzer** [jellyfin/jellyfin-androidtv#2414] opened 2023-01-13 23:39 UTC
### Describe the bug

Jellyfin 0.15.3 still has unresolved bugs (#2363)，steps to reproduce：

**1、Play the video for a few seconds, Jellyfin it will appear:**

2、Enter a library (TV, Movies and Playlists all seem to be affected);
3、Select any item that is not the first and click it to open the detailed view with the summary and seasons;
4、Click the back button on the remote, the cursor will not be over current item anymore, but over the first item.

### Application version

0.15.3 / 0.15.2

### Where did you install the app from?

Sideloaded APK

### Device information

Tmall MagicBox_M16S

### Android version

YUN OS TV

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment] 2023-01-14 11:14
I can't reproduce this issue after it was fixed with #2395 in 0.15.2. Can you share some more information?
- How many items are in the library?
- Which item index is selected (the number before the total count)
- What image size & type is used?
- What grid direction is used?
- Which sorting is used?
- Are the watched/favorite filter enabled?

**Comment by Soizzer** [comment] 2023-01-14 11:40
> I can't reproduce this issue after it was fixed with #2395 in 0.15.2. Can you share some more information?
> 
> * How many items are in the library?
> * Which item index is selected (the number before the total count)
> * What image size & type is used?
> * What grid direction is used?
> * Which sorting is used?
> * Are the watched/favorite filter enabled?

After starting jellyfin for the first time, everything works fine, but after quitting jellyfin and restarting, I have this problem.

 The same problem occurs after uninstalling and reinstalling.

 1. Less than 200 items in the library
 2. Any item except the first item
 3. Any image size is the same, poster format, landscape
 4. Sort by adding time
 5. Not using watched/favorite filter

**Comment by Soizzer** [comment] 2023-01-14 22:04
> I can't reproduce this issue after it was fixed with #2395 in 0.15.2. Can you share some more information?
> 
> * How many items are in the library?
> * Which item index is selected (the number before the total count)
> * What image size & type is used?
> * What grid direction is used?
> * Which sorting is used?
> * Are the watched/favorite filter enabled?

After starting jellyfin for the first time, everything works fine, but **after playing a few video files, exiting jellyfin and restarting**, I have this bug again.

**The same bug occurs after uninstalling and reinstalling.**

1. Less than 200 items in the library
2. Any item except the first item
3. Any image size is the same, poster format, landscape
4. Sort by adding time
5. Not using watched/favorite filter

If the bug still does not reproduce, **please try to play a few video files, then exit Jellyfin, restart Jellyfin** and test again.

I have reproduced the bug on another TV.

**Comment by Schwalch** [comment] 2023-01-20 14:36
I also still have the problem that the cursor jumps back to the first item. It also doesn't matter whether I start Jellifin for the first time or not.. the cursor bug is always present!

Device: Sony KD-55XH9005
Android version: 10 (Kernel 4.19.75)
Jellyfin client: 0.15.2
Jellyfin server: 10.8.8

I have created several libraries with different numbers of items, but it did not work. 
The bug comes as soon as you play a video for the first time. As long as you don't play a video and just click on the items and go back to the item overview without playing the item, it works.

Workflow without the bug:   Item overview -> Click on item -> Back to the items overview
Workflow with bug:    Item overview -> Click on item -> Start video -> Back to the item view -> Back to the items overview

**Comment by NeobinX** [comment] 2023-01-23 22:03
I also encounter it. Exactly as @Schwalch has already described.

Device: Sony TV
OS: AndroidTV 9
Kernel: 4.9.125
Jellyfin server: 10.8.9 (10.8.8 was the same)
Jellyfin app: 0.15.2 (from Google Play Store)

- _How many items are in the library?_
Same with almost 30 as well as almost 400
- _Which item index is selected (the number before the total count)_
Any except the first one
- _What image size & type is used?_
Same for all sizes & poster
- _What grid direction is used?_
Horizontal
- _Which sorting is used?_
Name
- _Are the watched/favorite filter enabled?_
No

Starting point: Jellyfin app force exited
- Select a library
- Select an item (not first one)
- Go back
- Cursor is on the correct item
- Select an item (not first one)
- Play that item (few seconds is already enough)
- Go back to item overview
- Cursor jumps to the first item

From now on, even if you only select an item, but do not play it and go back (where it worked before), the cursor jumps ever to the first item.
Exiting the app does not change this behavior for me. Only if I force exit it via the AndroidTV apps menu and start it afterwards again, then it works (cursor on correct position) as long as I do **not** play an item again.

**Comment by silentTeee** [comment] 2023-02-15 03:50
So I was having the same issue on my Hisense HiSmartTV A4, but it looks like I was able to get it to stop by force stopping the app and clearing the app data. 

Once I did that, I couldn't reproduce the issue in any of the Genre, Artist, or Album views, so it might be worth trying this.

**Comment by NeobinX** [comment] 2023-02-15 07:34
> So I was having the same issue on my Hisense HiSmartTV A4, but it looks like I was able to get it to stop by force stopping the app and clearing the app data.
> 
> Once I did that, I couldn't reproduce the issue in any of the Genre, Artist, or Album views, so it might be worth trying this.

Thanks, but unfortunately this did not work for me.

A **really** annoying issue and it seems to not even be reproducible and/or traceable by the maintainers?

**Comment by wolfiiy** [comment] 2023-03-26 12:28
Exact same behavior as https://github.com/jellyfin/jellyfin-androidtv/issues/2363 on version 0.15.5, Play Store, Shield TV Pro 2019, Android 11, JF 10.8.9. Clearing the cache fixes the issue until any piece of media is played, then the issue persists.

**Comment by alex3305** [comment] 2023-04-21 19:19
I have encountered this bug on every release of 0.15.x of Jellyfin Android. Just tested this on 0.15.6. Downgrading to 0.14.x fixes the issue. I'm using an Nvidia Shield and even with a factory reset of the device and Jellyfin with stock settings.

### Application version
Any 0.15.x release

### Where did you install the app from?
Play Store or sideloaded APK (for older versions)

### Device information
Nvidia Shield Pro 2019

### Android version
Android TV 8 / Nvidia Shield EXPERIENCE 8.2.3

### Jellyfin server version
10.8.8

- How many items are in the library? **anywhere between 2 and 800**
- Which item index is selected (the number before the total count) **any, except the first one**
- What image size & type is used? **stock Jellyfin Android TV (medium)**
- What grid direction is used? **horizontal**
- Which sorting is used? **alphabetical or alphabetical reverse**
- Are the watched/favorite filter enabled? **no, but doesn't seem to matter**

**Comment by vortex91** [comment] 2023-06-27 16:29
Not sure if this is just me but the issue seems to resolve itself when changing view to vertical instead of horizontal.  Going back to horizantal the issue comes back.  v15.10

**Comment by nielsvanvelzen** [comment] 2023-06-30 20:45
Thanks for all the additional information everyone, I've found the culprit and it will be fixed in the upcoming 0.15.11 release.

**Closed** 2023-07-01 09:44 UTC
Labels: bug

**Comment by McClane1988** [comment] 2023-07-02 17:39
i updated to the latest android tv version, cleared my cache and tried different versions and this bug still happens for me. any suggestions?
