### ISSUE TITLE
Cannot go backwards during LiveTV stream

### ISSUE THREAD

**Issue by avionics75** [jellyfin/jellyfin-androidtv#2019] opened 2022-08-29 12:25 UTC
### Describe the bug

Hi ! 

It seems that when watching liveTV, there is no way to jump backwards on the stream. The playing cursor just won't move.

This feature is possible on the jellyfin web client with liveTV (of course it's not possible to jump backwards more than the point where you started the livetv stream).

Do you think it's a bug ?

### Application version

0.14.2

### Where did you install the app from?

Google Play

### Device information

MI Stick 4K / Philips TV / TCL TV

### Android version

11 / 9 / 8

### Jellyfin server version

10.8.4

**Comment by mueslimak3r** [comment] 2022-09-01 04:03
This was relabeled as an enhancement because there currently isn't code that handles seeking based on available video buffer; so it's not a bug. Seeking is intentionally disabled with live tv for the above reason.

**Comment by avionics75** [comment] 2022-09-01 07:58
Oh I see :)

thanks for the reply !

**Comment by nielsvanvelzen** [comment] 2024-12-30 20:10
Closing as duplicate of #1067

**Closed by nielsvanvelzen** 2024-12-30 20:10 UTC
Labels: enhancement, playback, live-tv
