### ISSUE TITLE
[Beta 0.16.0] Crash while clearing music queue

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3096] opened 2023-10-03 04:52 UTC
### Describe the bug

As title says, crash while clearing music queue

Music still plays when you back out the app into the android launcher.  Is there going to be a stop button that clears the music, like it was never playing?

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9106)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1676)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4927)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at android.view.View.requestLayout(View.java:25414)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4927)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:6106)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:6081)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:13229)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:8232)
	at androidx.leanback.widget.ItemBridgeAdapter$1.onItemRangeInserted(ItemBridgeAdapter.java:188)
	at androidx.leanback.widget.ObjectAdapter$DataObservable.notifyItemRangeInserted(ObjectAdapter.java:124)
	at androidx.leanback.widget.ObjectAdapter.notifyItemRangeInserted(ObjectAdapter.java:260)
	at org.jellyfin.androidtv.ui.presentation.MutableObjectAdapter.add(MutableObjectAdapter.kt:31)
	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter.loadStaticAudioItems(ItemRowAdapter.java:805)
	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter.Retrieve(ItemRowAdapter.java:726)
	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$refreshRows$1.invokeSuspend(HomeRowsFragment.kt:229)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8a24540, Dispatchers.IO]

```  
***Logcat***: 
```log
10-03 15:16:40.517 D/SocketHandler( 9230): Updated 122 items
10-03 15:16:40.534 I/org.jellyfin.sdk.api.client.KtorClient( 9230): GET http://Jellyfin.server/Users/f0c73868-f5a1-416d-uh574-tf6ss88677af/Views?includeHidden=false
10-03 15:16:40.664 D/LeanbackChannelWorker( 9230): Updating channel content://android.media.tv/channel/167
10-03 15:16:40.687 D/LeanbackChannelWorker( 9230): Updating channel content://android.media.tv/channel/165
10-03 15:16:40.796 D/LeanbackChannelWorker( 9230): Updating channel content://android.media.tv/channel/168
10-03 15:16:40.916 D/LeanbackChannelWorker( 9230): Updating channel content://android.media.tv/channel/169
10-03 15:16:40.977 D/LeanbackChannelWorker( 9230): Updating channel content://android.media.tv/channel/166
10-03 15:16:41.029 I/WM-WorkerWrapper( 9230): Worker result SUCCESS for Work [ id=89904d1a-03b5-4bf2-a82b-00ad1d635a98, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
10-03 15:16:41.060 I/android_os_HwBinder( 9230): HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
10-03 15:16:41.077 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_ASYNC"
10-03 15:16:41.077 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
10-03 15:16:41.077 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
10-03 15:16:41.077 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
10-03 15:16:41.115 E/Surface ( 9230): freeAllBuffers: 1 buffers were freed while being dequeued!
10-03 15:16:41.118 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_ASYNC"
10-03 15:16:41.118 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
10-03 15:16:41.118 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
10-03 15:16:41.118 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
10-03 15:16:42.894 D/jellyfin-apiclient( 9230): Adding request to queue: http://Jellyfin.server/Sessions/Playing/Progress
10-03 15:16:42.929 I/jellyfin-apiclient( 9230): Response received from: http://Jellyfin.server/Sessions/Playing/Progress
10-03 15:16:43.915 D/LegacyMediaManager( 9230): clearing the audio queue
10-03 15:16:43.916 D/LegacyMediaManager( 9230): Stopping audio
10-03 15:16:43.917 I/LegacyMediaManager( 9230): stopping progress loop
10-03 15:16:43.917 I/jellyfin-apiclient( 9230): ReportPlaybackStopped: Item 9658356b-cft8-6hc3-bde0-h8b3d94b3588, Ticks: 466780000
10-03 15:16:43.917 D/jellyfin-apiclient( 9230): Adding request to queue: http://Jellyfin.server/Sessions/Playing/Stopped
10-03 15:16:43.918 D/AudioNowPlayingFragment( 9230): **** Got playstate change: IDLE
10-03 15:16:43.919 D/AudioNowPlayingFragment( 9230): Updating buttons
10-03 15:16:43.920 D/LegacyMediaManager( 9230): releasing audio player
10-03 15:16:43.920 I/ExoPlayerImpl( 9230): Release 8ee6a2e [ExoPlayerLib/2.19.1] [sif, SHIELD Android TV, NVIDIA, 30] [goog.exo.core, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor, goog.exo.ffmpeg, goog.exo.hls]
10-03 15:16:43.922 I/LegacyMediaManager( 9230): Firing queue state change listener. false
10-03 15:16:43.923 I/HomeRowsFragment( 9230): Updating audio queue in HomeFragment (onQueueStatusChanged)
10-03 15:16:43.923 I/LegacyMediaManager( 9230): Firing queue state change listener. false
10-03 15:16:43.923 D/AudioNowPlayingFragment( 9230): Queue status changed
10-03 15:16:43.924 D/NavigationRepositoryImpl( 9230): Navigating back
10-03 15:16:43.939 D/LegacyMediaManager( 9230): Removed event listener.  Total listeners: 1
10-03 15:16:43.966 D/HomeRowsFragment( 9230): Refresh item 01. Doja Cat - Paint The Town Red
10-03 15:16:43.967 I/HomeRowsFragment( 9230): Updating audio queue in HomeFragment (onResume)
10-03 15:16:43.967 I/org.jellyfin.sdk.api.client.KtorClient( 9230): GET http://Jellyfin.server/Users/f0c73868-f5a1-416d-uh574-tf6ss88677af/Items/9658356b-cft8-6hc3-bde0-h8b3d94b3588
10-03 15:16:43.968 I/org.jellyfin.sdk.api.sockets.SocketInstance( 9230): Adding subscription for SessionsMessage
10-03 15:16:43.968 D/NavigationRepositoryImpl( 9230): Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.home.HomeFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via reset)
10-03 15:16:43.969 I/org.jellyfin.sdk.api.sockets.SocketInstance( 9230): Adding subscription for ActivityLogEntryMessage
10-03 15:16:43.969 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 9230): Sending (raw) message {"MessageType":"SessionsStart","Data":"0,1000"}
10-03 15:16:43.969 I/org.jellyfin.sdk.api.sockets.SocketInstance( 9230): Adding subscription for ScheduledTasksInfoMessage
10-03 15:16:43.970 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 9230): Sending (raw) message {"MessageType":"ActivityLogEntryStart","Data":"0,1000"}
10-03 15:16:43.970 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 9230): Sending (raw) message {"MessageType":"ScheduledTasksInfoStart","Data":"0,1000"}
10-03 15:16:44.076 I/androidtv.debu( 9230): Background concurrent copying GC freed 494925(23MB) AllocSpace objects, 90(10224KB) LOS objects, 50% free, 19MB/38MB, paused 156us total 127.839ms
10-03 15:16:44.167 I/jellyfin-apiclient( 9230): Response received from: http://Jellyfin.server/Sessions/Playing/Stopped
10-03 15:16:44.232 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_ASYNC"
10-03 15:16:44.232 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
10-03 15:16:44.232 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
10-03 15:16:44.232 E/libc    ( 9230): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
10-03 15:16:44.286 E/Surface ( 9230): freeAllBuffers: 1 buffers were freed while being dequeued!
10-03 15:16:44.443 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession( 9230): Receiving (raw) message {"MessageType":"UserDataChanged","MessageId":"5ef3a5b8dcf44bcebc681a329b05a09d","Data":{"UserId":"f0c73868f5a1416db050ef6e068677af","UserDataList":[{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2023-10-03T04:15:59.8688455Z","Played":true,"Key":"01. Doja Cat - Paint The Town Red","ItemId":"9651783cbfc80ec3bfe0f8b3d94b3588"},{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"95d51458-3fa0-8496-7559-d5a4594d4ac5","ItemId":"95d514583fa084967559d5a4594d4ac5"}]}}
10-03 15:16:44.460 E/ACRA    ( 9230): ACRA caught a CalledFromWrongThreadException for org.jellyfin.androidtv.debug
10-03 15:16:44.460 E/ACRA    ( 9230): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9106)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1676)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4927)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at android.view.View.requestLayout(View.java:25414)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4927)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:6106)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:6081)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:13229)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:8232)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.leanback.widget.ItemBridgeAdapter$1.onItemRangeInserted(ItemBridgeAdapter.java:188)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.leanback.widget.ObjectAdapter$DataObservable.notifyItemRangeInserted(ObjectAdapter.java:124)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at androidx.leanback.widget.ObjectAdapter.notifyItemRangeInserted(ObjectAdapter.java:260)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at org.jellyfin.androidtv.ui.presentation.MutableObjectAdapter.add(MutableObjectAdapter.kt:31)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter.loadStaticAudioItems(ItemRowAdapter.java:805)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapter.Retrieve(ItemRowAdapter.java:726)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at org.jellyfin.androidtv.ui.home.HomeRowsFragment$refreshRows$1.invokeSuspend(HomeRowsFragment.kt:229)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
10-03 15:16:44.460 E/ACRA    ( 9230): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
10-03 15:16:44.460 E/ACRA    ( 9230): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8a24540, Dispatchers.IO]
10-03 15:16:44.460 D/ACRA    ( 9230): Building report
10-03 15:16:44.461 D/ACRA    ( 9230): Starting collectors with priority FIRST
10-03 15:16:44.462 D/ACRA    ( 9230): Calling collector org.acra.collector.StacktraceCollector
10-03 15:16:44.462 D/ACRA    ( 9230): Calling collector org.acra.collector.LogCatCollector
10-03 15:16:44.463 D/ACRA    ( 9230): Calling collector org.acra.collector.DropBoxCollector
10-03 15:16:44.463 D/ACRA    ( 9230): Collector org.acra.collector.DropBoxCollector completed
10-03 15:16:44.463 D/ACRA    ( 9230): Collector org.acra.collector.StacktraceCollector completed
10-03 15:16:44.468 D/ACRA    ( 9230): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.16.0-beta.4` (`160004`)  
***Package name***: `org.jellyfin.androidtv.debug`  
***Build***: 
```json
{"BOARD":"sif","BOOTLOADER":"32.00.2019.50-t210-69ebfcbe","BRAND":"NVIDIA","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"sif","DISPLAY":"RQ1A.210105.003.7825199_3167.5736","FINGERPRINT":"NVIDIA\/sif\/sif:11\/RQ1A.210105.003\/7825199_3167.5736:user\/release-keys","HARDWARE":"sif","HOST":"mobile-u64-5306-d6000","ID":"RQ1A.210105.003","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"NVIDIA","MODEL":"SHIELD Android TV","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"sif","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1665975946000,"TYPE":"user","UNKNOWN":"unknown","USER":"NVIDIA","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"7825199_3167.5736","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"11","RELEASE_OR_CODENAME":"11","SDK":"30","SDK_INT":30,"SECURITY_PATCH":"2022-04-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv.debug","BUILD_TYPE":"debug","DEBUG":true,"DEVELOPMENT":false,"VERSION_CODE":160004,"VERSION_NAME":"0.16.0-beta.4"}
```  

### Device information

***Android version***: `11`  
***Device brand***: `NVIDIA`  
***Device product***: `sif`  
***Device model***: `SHIELD Android TV`  

### Application version

0.16.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2023-10-08 19:49
What steps did you specifically take to clear the music queue? There are a few paths to do it and I want to make sure I reproduce it correctly.

>  Is there going to be a stop button that clears the music, like it was never playing?

Audio will keep playing in the background, this is intentional. Your launcher should have a stop button for it, otherwise you'll need to open the app and use the media controls there.

**Comment by nielsvanvelzen** [comment] 2023-10-15 09:04
Closing as can't reproduce.

**Closed by nielsvanvelzen** 2023-10-15 09:04 UTC
Labels: bug
