### ISSUE TITLE
Android TV App error on launch on Sony TV

### ISSUE THREAD

**Issue by Jtav1** [jellyfin/jellyfin-androidtv#1963] opened 2022-08-13 04:01 UTC
### Describe the bug

Attempting to launch the app on my Sony X90H results in an application crash and close. A message toast pops up saying an error occurred and was reported to the server (see logs below).

Currently using beta version of the app, 0.14.1, but this issue did not occur until recently. I suspect it may have been related to an Android TV update that was pushed to the TV and I chose to install the other day. I didn't test it before and after, but that's the only thing that has changed since the last time the app worked. 

TV running Android 10 / Kernel 4.19.75 / OS Build in logs 

Server using official jellyfin/jellyfin:stable docker container.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.1
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
kotlinx.serialization.json.internal.JsonDecodingException: Cannot begin reading element, unexpected token: 10 at path: $
JSON input: 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)
	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:104)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:51)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:27)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:128)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore.load(AuthenticationStore.kt:51)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore.access$load(AuthenticationStore.kt:28)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore$store$2.invoke(AuthenticationStore.kt:43)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore$store$2.invoke(AuthenticationStore.kt:42)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore.getStore(AuthenticationStore.kt:42)
	at org.jellyfin.androidtv.auth.store.AuthenticationStore.getServer(AuthenticationStore.kt:80)
	at org.jellyfin.androidtv.auth.repository.ServerRepositoryImpl.getServer(ServerRepository.kt:162)
	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:121)
	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:77)
	at org.jellyfin.androidtv.SessionInitializer$create$1.invokeSuspend(SessionInitializer.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:20)
	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:12)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a3f857d, Dispatchers.Main.immediate]

```  
***Logcat***: 
```log
--------- beginning of main
08-12 22:55:41.785 W/lyfin.androidt( 3156): Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
08-12 22:55:41.794 E/lyfin.androidt( 3156): Not starting debugger since process cannot load the jdwp agent.
08-12 22:55:41.889 W/lyfin.androidt( 3156): JIT profile information will not be recorded: profile file does not exits.
08-12 22:55:41.889 I/chatty  ( 3156): uid=10111(org.jellyfin.androidtv) identical 1 line
08-12 22:55:41.889 W/lyfin.androidt( 3156): JIT profile information will not be recorded: profile file does not exits.
08-12 22:55:41.970 D/ACRA    ( 3156): ACRA processName='org.jellyfin.androidtv'
08-12 22:55:41.974 I/ACRA    ( 3156): ACRA is enabled for org.jellyfin.androidtv, initializing...
08-12 22:55:41.975 D/ACRA    ( 3156): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@1ef943
08-12 22:55:41.976 D/ACRA    ( 3156): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.collector.Collector]
08-12 22:55:42.030 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.ConfigurationCollector
08-12 22:55:42.031 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.CustomDataCollector
08-12 22:55:42.031 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.DeviceFeaturesCollector
08-12 22:55:42.031 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.DeviceIdCollector
08-12 22:55:42.031 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.DisplayManagerCollector
08-12 22:55:42.032 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.DropBoxCollector
08-12 22:55:42.032 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.LogCatCollector
08-12 22:55:42.032 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.LogFileCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.MediaCodecListCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.MemoryInfoCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.PackageManagerCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.ReflectionCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.SettingsCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.SharedPreferencesCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.SimpleValuesCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.StacktraceCollector
08-12 22:55:42.033 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.ThreadCollector
08-12 22:55:42.052 D/ACRA    ( 3156): Loaded Collector of type org.acra.collector.TimeCollector
08-12 22:55:42.060 D/ACRA    ( 3156): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@1ef943
08-12 22:55:42.060 D/ACRA    ( 3156): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
08-12 22:55:42.060 D/ACRA    ( 3156): SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@1ef943
08-12 22:55:42.060 D/ACRA    ( 3156): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
08-12 22:55:42.082 I/LogInitializer( 3156): Debug tree planted
08-12 22:55:42.134 W/lyfin.androidt( 3156): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
08-12 22:55:42.134 W/lyfin.androidt( 3156): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
08-12 22:55:42.135 W/lyfin.androidt( 3156): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
08-12 22:55:42.148 D/SessionRepositoryImpl( 3156): Restoring session
08-12 22:55:42.180 E/ACRA    ( 3156): ACRA caught a JsonDecodingException for org.jellyfin.androidtv
08-12 22:55:42.180 E/ACRA    ( 3156): kotlinx.serialization.json.internal.JsonDecodingException: Cannot begin reading element, unexpected token: 10 at path: $
08-12 22:55:42.180 E/ACRA    ( 3156): JSON input: 
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:104)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:33)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:51)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:27)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:128)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore.load(AuthenticationStore.kt:51)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore.access$load(AuthenticationStore.kt:28)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore$store$2.invoke(AuthenticationStore.kt:43)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore$store$2.invoke(AuthenticationStore.kt:42)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore.getStore(AuthenticationStore.kt:42)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.store.AuthenticationStore.getServer(AuthenticationStore.kt:80)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.repository.ServerRepositoryImpl.getServer(ServerRepository.kt:162)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:121)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:77)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.SessionInitializer$create$1.invokeSuspend(SessionInitializer.kt:21)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:20)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:12)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
08-12 22:55:42.180 E/ACRA    ( 3156): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.os.Looper.loop(Looper.java:214)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at java.lang.reflect.Method.invoke(Native Method)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-12 22:55:42.183 E/ACRA    ( 3156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
08-12 22:55:42.183 E/ACRA    ( 3156): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a3f857d, Dispatchers.Main.immediate]
08-12 22:55:42.183 D/ACRA    ( 3156): Building report
08-12 22:55:42.186 D/ACRA    ( 3156): Starting collectors with priority FIRST
08-12 22:55:42.188 D/ACRA    ( 3156): Calling collector org.acra.collector.DropBoxCollector
08-12 22:55:42.189 D/ACRA    ( 3156): Calling collector org.acra.collector.LogCatCollector
08-12 22:55:42.189 D/ACRA    ( 3156): Collector org.acra.collector.DropBoxCollector completed
08-12 22:55:42.189 D/ACRA    ( 3156): Calling collector org.acra.collector.StacktraceCollector
08-12 22:55:42.190 D/ACRA    ( 3156): Collector org.acra.collector.StacktraceCollector completed
08-12 22:55:42.196 D/ACRA    ( 3156): Retrieving logcat output (buffer:default)...
08-12 22:55:42.207 E/libc    ( 3192): Access denied finding property "persist.vendor.system.svp.dbg.loglevel"

```  

### App information

***App version***: `0.14.1` (`140199`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mt5895","BOOTLOADER":"unknown","BRAND":"Sony","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"BRAVIA_VH1","DISPLAY":"BRAVIA_VH1_UC-user 10 QTG3.200305.006.S165 617721 release-keys","FINGERPRINT":"Sony\/BRAVIA_VH1_UC\/BRAVIA_VH1:10\/QTG3.200305.006.S165\/617721:user\/release-keys","HARDWARE":"mt5895","HOST":"BuildHost677","ID":"QTG3.200305.006.S165","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Sony","MODEL":"BRAVIA VH1","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"BRAVIA_VH1_UC","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1654163033000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"617721","PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"10","RESOURCES_SDK_INT":29,"SDK":"29","SDK_INT":29,"SECURITY_PATCH":"2022-04-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140199,"VERSION_NAME":"0.14.1"}
```  

### Device information

***Android version***: `10`  
***Device brand***: `Sony`  
***Device product***: `BRAVIA_VH1_UC`  
***Device model***: `BRAVIA VH1`  

### Crash information

***Start time***: `2022-08-12T22:55:42.060-04:00`  
***Crash time***: `2022-08-12T22:55:42.224-04:00`  

### Application version

0.14.1

### Where did you install the app from?

Google Play

### Device information

Sony Bravia X900h - XBR75X900H

### Android version

Android 10

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment] 2022-08-13 07:08
It looks like the storage file for authentication got corrupted. That file saves your servers and users and is loaded when the app starts to see which user to use.
I'm not sure how that happened. It shouldn't be caused by the app so maybe the app forcefully closed while saving the file or something else happened. I've created a "fix" that will clear the file when it's corrupt instead of crashing the app (#1964) which will be released in the next bugfix release.

For now to keep using the app you should clear the app data in your system settings.

**Comment by Jtav1** [comment] 2022-08-13 07:33
Seems like that did the trick, thanks for the quick response. It is working properly now after clearing data and launching the app. I'm glad I could identify an opportunity to gracefully handle an error condition at least, have a good one.

**Closed** 2022-08-13 07:59 UTC
Labels: bug
