### ISSUE TITLE
i can not delete media from app

### ISSUE THREAD

**Issue by somethingGoneWrong** [jellyfin/jellyfin-androidtv#2417] opened 2023-01-14 14:30 UTC
### Describe the bug

i run jellyfin with docker and in the web ui with the USER account a can delete the media but when i use the same account on jellyfin app installed on fire stick the delete button is missing.

1. open jellyfin app 
2. select one library
3. select one media from the list
4. can NOT delete the media because the presence of the delete button is missing

### Logs

```
[14:05:28] [INF] [28] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[14:05:28] [INF] [28] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[14:05:29] [INF] [28] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:05:49] [INF] [23] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:06:09] [INF] [28] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:06:29] [INF] [26] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:06:49] [INF] [26] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:07:09] [INF] [27] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:07:29] [INF] [8] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:07:49] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:08:09] [INF] [23] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:08:29] [INF] [23] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:08:49] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:09:09] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:09:26] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.15.2 playing MEDIA VIDEO. Stopped at 256668 ms
[14:09:26] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:09:26] [INF] [25] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 01/14/2023 14:09:26
[14:09:26] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[14:12:20] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for USER. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:12:20] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=AndroidTV-libVLC, Path=/temp_yt/MEDIA VIDEO.mp4, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/21cdd9ef-9e4f-b970-9788-1b5422b446f7/stream.mov?MediaSourceId=21cdd9ef9e4fb97097881b5422b446f7&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=8b181c381ebfb9c633c6dcd7188cab8c
[14:12:20] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for USER. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:12:20] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=AndroidTV-ExoPlayer, Path=/temp_yt/MEDIA VIDEO.mp4, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/21cdd9ef-9e4f-b970-9788-1b5422b446f7/stream.mov?MediaSourceId=21cdd9ef9e4fb97097881b5422b446f7&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=8b181c381ebfb9c633c6dcd7188cab8c
[14:12:20] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:12:20] [INF] [41] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 01/14/2023 14:12:20
[14:12:20] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[14:12:20] [INF] [24] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[14:12:21] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:12:32] [INF] [39] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP request
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 10.60.0.40
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = 21cdd9ef9e4fb97097881b5422b446f7
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 4b733de24be749b19b709fed30fb2aed
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 2
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = 21cdd9ef9e4fb97097881b5422b446f7
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 4b733de24be749b19b709fed30fb2aed
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = DirectPlay
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = Fire TV
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = MEDIA VIDEO
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = 21cdd9ef9e4fb97097881b5422b446f7
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Movie
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : All matches, playback registered
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback tracker found, adding playback info : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[14:12:40] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[14:12:41] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:12:47] [INF] [41] Emby.Server.Implementations.Session.SessionManager: Logging out access token d134a5f1215949ba9c93582a11747a80
[14:12:47] [INF] [34] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP closed
[14:12:51] [INF] [34] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[14:12:51] [INF] [34] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 0/0
[14:12:51] [INF] [34] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 17b6a31c-76e9-4617-b5cd-e6c0982b8a35
[14:12:51] [INF] [32] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP request
[14:13:01] [INF] [36] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:13:22] [INF] [36] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:13:42] [INF] [35] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[14:13:42] [INF] [36] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:13:54] [INF] [35] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[14:14:02] [INF] [35] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:14:22] [INF] [35] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:14:42] [INF] [40] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:15:03] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:15:23] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:15:43] [INF] [34] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:16:03] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:16:23] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:16:43] [INF] [38] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:17:03] [INF] [38] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:17:23] [INF] [44] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:17:37] [INF] [38] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.15.2 playing MEDIA VIDEO. Stopped at 572075 ms
[14:17:37] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : 3f9831402dd8c2d4229a6e3b9c156e2492e3b5c2-4b733de24be749b19b709fed30fb2aed-21cdd9ef9e4fb97097881b5422b446f7
[14:17:37] [INF] [46] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 01/14/2023 14:17:37
[14:17:37] [INF] [46] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
```

### Application version

0.15.2

### Where did you install the app from?

Amazon Appstore

### Device information

amazon fire tv 4k max

### Android version

fire os 7.6.1.4

### Jellyfin server version

 10.8.8

**Comment by thornbill** [comment] 2023-01-14 14:54
Duplicate of #2368

**Closed** 2023-01-14 14:55 UTC
Labels: bug, duplicate
