### ISSUE TITLE
0.17.1 player crashes on DTS 7.1 direct playback

### ISSUE THREAD

**Issue by borkedporcupine** [jellyfin/jellyfin-androidtv#3868] opened 2024-08-09 13:57 UTC
### Describe the bug

1. Select media with DTS 7.1 audio
2. Hit play
3. Observe a few retries then player failure warning.
4. Crashes back to library  

Changing audio from direct to downmix to stereo allows successful playback.  Media with other audio formats work without error. 

Prior to the latest release I could also select LibVLC for playback when Exoplayer failed to play media.  However that option seems to have been stripped out in the latest build. 

### Application version

0.17.1

### Where did you install the app from?

Google Play

### Device information

Chromcast 4k

### Android version

12

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment] 2024-08-09 17:57
Please share the app crash logs.

**Comment by borkedporcupine** [comment] 2024-08-09 18:08
> Please share the app crash logs.

Not really sure how to get them since it's on the chromecast.  The server side logs don't show the crash they just show the disconnect from the media when it crashes.

**Comment by nielsvanvelzen** [comment] 2024-08-09 18:10
When the app crashes it always reports those logs to the server, available in the dashboard. Without logs I can't do much.

**Comment by borkedporcupine** [comment] 2024-08-09 18:13
> When the app crashes it always reports those logs to the server, available in the dashboard. Without logs I can't do much.

Hmm, to be clear the entire app isn't crashing just the player.  "encountered too many errors" is the toast.  Does the player crash report to the server?  Can you point me to where that is?  I'd be glad to provide it if it's something I have.

**Comment by borkedporcupine** [comment] 2024-08-09 18:17
My logs look like below, to me seems like all the server knows is playback stopped. 

`[2024-08-09 18:14:58.164 +00:00] [INF] User policy for "redacted". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-08-09 18:14:59.103 +00:00] [INF] Playback stopped reported by app "Android TV" "0.17.1" playing "Encounter at Farpoint (1) / Encounter at Farpoint (2)". Stopped at "0" ms
[2024-08-09 18:14:59.110 +00:00] [INF] User policy for "redacted". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-08-09 18:14:59.739 +00:00] [INF] User policy for "redacted". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-08-09 18:14:59.753 +00:00] [INF] Playback stopped reported by app "Android TV" "0.17.1" playing "Encounter at Farpoint (1) / Encounter at Farpoint (2)". Stopped at "0" ms
[2024-08-09 18:15:00.357 +00:00] [INF] Playback stopped reported by app "Android TV" "0.17.1" playing "Encounter at Farpoint (1) / Encounter at Farpoint (2)". Stopped at "0" ms`

**Comment by borkedporcupine** [comment] 2024-08-09 18:27
I also just noticed that DTS bitstream option is now missing.  I still see a DD bitstream option now.  Could this be the root of the issue?

**Comment by nielsvanvelzen** [comment] 2024-08-09 20:35
> Hmm, to be clear the entire app isn't crashing just the player. "encountered too many errors" is the toast. Does the player crash report to the server? Can you point me to where that is? I'd be glad to provide it if it's something I have.

Then it is not a crash, just a playback failure. In which case you used the wrong template and didn't provide any media info.

> I also just noticed that DTS bitstream option is now missing. I still see a DD bitstream option though. Could this be the root of the issue?

This option did nothing and was therefor removed. The app claims DTS support when the audio behavior is set to direct stream.

**Comment by borkedporcupine** [comment] 2024-08-09 20:40
> Then it is not a crash, just a playback failure. In which case you used the wrong template and didn't provide any media info.
Sorry... wasn't intentional.  How would you like me to proceed?  Should I provide more info in this thread or would you like to delete/close this and I'll try again with the proper template?

**Comment by rickysixx** [comment] 2024-08-12 08:14
I am facing the same issue on 0.17.3 and server version 10.9.8. Here are my logs.

Exception which causes playback error in ExoPlayer:
```
[OMX.MS.HEVC.Decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
createTrack returned error -38
createTrack_l(1148657408): AudioFlinger could not create track, status: -38 output 0
Error -38 initializing AudioTrack
Error code -20 when initializing AudioTrack.
Audio sink error
androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 6396, 48000) Format(2, Surround 7.1, null, audio/vnd.dts, null, -1, en, [-1, -1, -1.0, null], [8, 48000])
    at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2229)
    at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1070)
    at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1049)
    at androidx.media3.exoplayer.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:828)
    at androidx.media3.exoplayer.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:927)
    at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:773)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2358)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:868)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:223)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
    at android.media.AudioTrack$Builder.build(AudioTrack.java:1277)
    at androidx.media3.exoplayer.drm.FrameworkMediaDrm$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
    at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2276)
    at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2255)
    at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2221)
```

Media info:

```
General
Format                                   : Matroska
Format version                           : Version 4
File size                                : 69.6 GiB
Duration                                 : 2 h 49 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 58.7 Mb/s
Frame rate                               : 23.976 FPS
Encoded date                             : 2024-07-10 15:43:07 UTC
Writing application                      : Lavf59.27.100
Writing library                          : Lavf59.27.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 49 min
Bit rate                                 : 52.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.263
Stream size                              : 62.1 GiB (89%)
Writing library                          : ATEME Titan File 3.8.16 (4.8.16.0)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 155 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL X
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD MA + DTS:X
Codec ID                                 : A_DTS
Duration                                 : 2 h 49 min
Bit rate mode                            : Variable
Bit rate                                 : 5 793 kb/s
Channel(s)                               : 8 channels
Channel layout                           : C L R LFE Lb Rb Lss Rss Objects
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 6.87 GiB (10%)
Title                                    : Surround 7.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4355 (0x1103)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 2 h 49 min
Bit rate mode                            : Constant
Bit rate                                 : 447 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 543 MiB (1%)
Title                                    : Stereo
Language                                 : Italian
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray
```

This movie contains also a stereo track in Italian, but I'm not able to select it because the player refreshes completely after an error.

No playback error occurs when preferring extension renderers (see [186ab31](https://github.com/jellyfin/jellyfin-androidtv/pull/3818/commits/186ab3196655d3e7b2f4bc40969dea2ac0c80850); don't know if this fixes OP problem too).

This error line in the above log
```
[OMX.MS.HEVC.Decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
```
seems to be irrelevant, becuae it's there also when the movie plays correctly.

**Comment by anthonymag** [comment] 2024-08-13 23:51
Similar issue with playback on the Android TV app since updating. Other clients work fine. This is happening on two different "Chromecast with Google TV" devices.
I'm getting the "Player error encountered" failure when I try playing an episode.
`adb logcat`: 
```
08-13 19:02:07.592  7327  7327 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment (Kotlin reflection is not available), arguments=Bundle[{Position=0}]) (via navigate function)
08-13 19:02:07.748  3918  5859 I MediaFocusControl: requestAudioFocus() from uid/pid 10071/7327 AA=USAGE_MEDIA/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@d791ee7org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@bc81a13 callingPack=org.jellyfin.androidtv req=1 flags=0x0 sdk=34
08-13 19:02:12.832  3918  5859 I MediaFocusControl: abandonAudioFocus() from uid/pid 10071/7327 clientId=android.media.AudioManager@d791ee7org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@bc81a13
08-13 19:02:12.834  3918  5859 I MediaFocusControl: abandonAudioFocus() from uid/pid 10071/7327 clientId=android.media.AudioManager@d791ee7org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment$6@bc81a13
08-13 19:02:13.497  3918  5859 W NotificationService: Toast already killed. pkg=org.jellyfin.androidtv token=android.os.BinderProxy@65f7e82
08-13 19:02:17.557  3918  5859 W NotificationService: Toast already killed. pkg=org.jellyfin.androidtv token=android.os.BinderProxy@391b80b
```

Jellyfin container logs:
```
[23:02:09] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for anthony. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[23:02:09] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:09] [INF] [33] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/13/2024 23:02:09
[23:02:09] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[23:02:09] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[23:02:10] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:10] [INF] [15] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for anthony. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[23:02:10] [INF] [17] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.3 playing A Top Officer! The Sweet 3 General Cracker Appears!. Stopped at 0 ms
[23:02:11] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:11] [INF] [15] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 08/13/2024 23:02:11
[23:02:11] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[23:02:11] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:11] [INF] [17] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/13/2024 23:02:11
[23:02:11] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[23:02:11] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[23:02:11] [INF] [15] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:12] [INF] [17] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.3 playing A Top Officer! The Sweet 3 General Cracker Appears!. Stopped at 0 ms
[23:02:12] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for anthony. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[23:02:12] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:12] [INF] [21] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 08/13/2024 23:02:12
[23:02:12] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[23:02:12] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:12] [INF] [19] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 08/13/2024 23:02:12
[23:02:12] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[23:02:12] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[23:02:13] [INF] [19] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:14] [INF] [15] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Android TV 0.17.3 playing A Top Officer! The Sweet 3 General Cracker Appears!. Stopped at 0 ms
[23:02:14] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : 3248a9408298f8caa11dc1cf0e1a409f31b9fd45-359d73f376e74e27a72d7bc8486cf11e-5942bba4a87190881a77eded036e611e
[23:02:14] [INF] [33] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 08/13/2024 23:02:14
[23:02:14] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 2600:1700:17cd:42f:f5f4:3344:7508:2e7b
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = 5942bba4a87190881a77eded036e611e
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 359d73f376e74e27a72d7bc8486cf11e
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 3
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   =
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 359d73f376e74e27a72d7bc8486cf11e
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = na
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = Living Room Chromecast
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = One Piece - s19e797 - A Top Officer! The Sweet 3 General Cracker Appears!
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = 5942bba4a87190881a77eded036e611e
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Episode
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[23:02:29] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 2600:1700:17cd:42f:f5f4:3344:7508:2e7b
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = 5942bba4a87190881a77eded036e611e
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 359d73f376e74e27a72d7bc8486cf11e
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 3
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   =
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 359d73f376e74e27a72d7bc8486cf11e
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = na
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = Living Room Chromecast
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = One Piece - s19e797 - A Top Officer! The Sweet 3 General Cracker Appears!
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = 5942bba4a87190881a77eded036e611e
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Episode
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[23:02:31] [INF] [21] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[23:02:31] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : 2600:1700:17cd:42f:f5f4:3344:7508:2e7b
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = 5942bba4a87190881a77eded036e611e
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = 359d73f376e74e27a72d7bc8486cf11e
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 3
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   =
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = 359d73f376e74e27a72d7bc8486cf11e
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = na
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = Android TV
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = Living Room Chromecast
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = One Piece - s19e797 - A Top Officer! The Sweet 3 General Cracker Appears!
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = 5942bba4a87190881a77eded036e611e
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = Episode
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Details do not match for play item
[23:02:32] [INF] [33] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[23:03:01] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
[23:03:12] [INF] [21] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[23:03:31] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
```

Jellyfin server 10.9.9
Jellyfin for Android TV 0.17.3

**other content plays fine** though I know that these particular episodes have a subtitle codec that my device doesn't support (special fonts? I guess? It's ASS subtitles) so they are always burned in, **when it works**.

It also seems that if I start the episode on another device, then resume from the ATV, it works.

**Comment by rickysixx** [comment] 2024-08-14 06:48
I think your issue is off topic here @anthonymag. I do not see any error in your logs and I highly doubt that anime use DTS as audio codec.

I guess it's better if you create a new issue (maybe there might be some already regarding ASS subtitles).

**Comment by rickysixx** [comment] 2024-08-17 19:33
> Prior to the latest release I could also select LibVLC for playback when Exoplayer failed to play media. However that option seems to have been stripped out in the latest build.

Are you able to direct play DTS audio on 0.16.11 using ExoPlayer (not LibVLC)?

**Comment by borkedporcupine** [comment] 2024-08-18 14:01
> > Prior to the latest release I could also select LibVLC for playback when Exoplayer failed to play media. However that option seems to have been stripped out in the latest build.
> 
> Are you able to direct play DTS audio on 0.16.11 using ExoPlayer (not LibVLC)? (you can check for direct play by going in your server's dashboard when you are playing the media on your TV)

Both ExoPlayer and LibVLC worked without crashing in 0.16, earlier builds in ExoPlayer crashed with DTS very similarly to this, but I don't recall what build as it wasn't big deal with LibVLC as a fallback.

**Comment by nielsvanvelzen** [comment] 2024-08-20 11:41
Closing as duplicate of #3896, as they appear to be the same issue.

**Closed by nielsvanvelzen** 2024-08-20 11:41 UTC
Labels: bug
