### ISSUE TITLE
On latest TV Shows it shows a mixture of posters and thumbnails

### ISSUE THREAD

**Issue by MrMookdog** [jellyfin/jellyfin-androidtv#1926] opened 2022-08-03 00:14 UTC
### Describe the bug

On the latest media (TV Shows only) it shows thumbnails instead of posters

### Application version

0.14.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2019)

### Android version

Android 11

### Jellyfin server version

10.8.1

**Comment by sourpatched** [comment] 2022-08-03 04:19
Do you have any screenshots of this?

**Comment by MrMookdog** [comment] 2022-08-03 04:47
![Jellyfin_20220801_014254](https://user-images.githubusercontent.com/34116943/182526113-ff9cc9f9-bdf0-4e08-badb-2cf9444cbb38.png)

Thats the screenshot. I think it would look 10x better if it showed the posters instead of thumbnails. It looks too much like the next up section with the thumbnails.

**Comment by sourpatched** [comment] 2022-08-03 05:57
I don't see an issues here, this is how it has been for single episodes for while?

**Comment by MrMookdog** [comment] 2022-08-03 06:49
Thats the thing its not single episodes. I have quite a few eps for those shows that I havent watched and it still comes up that way

**Comment by nielsvanvelzen** [comment] 2022-08-03 07:08
This is not a bug but a feature request

**Comment by MRobi1** [comment] 2022-08-03 18:38
Not a bug? Weird how every other media platform shows 1 or the other and Jellyfin shows a random mixture of both with no rhyme or reason as to why. As @MrMookdog said, it's not just single episodes, it appears completely at random. It also functions properly using the WebUI, so it is 100% a bug.

Also, I reported back in December.
https://github.com/jellyfin/jellyfin-androidtv/issues/1294

I would love to switch from Emby to Jellyfin for the open source community, but until even the basic of layout issues can be resolved it's a non-starter for me.

**Comment by thornbill** [comment] 2022-08-03 18:58
A bug is when something does not work as intended... not when something does not work according to your personal preference or work in the same manner as a different service.

I'll close this since it is a duplicate of #1294

**Closed by thornbill** 2022-08-03 18:58 UTC
Labels: enhancement
