### ISSUE TITLE
"Play" Button on Details page should be focused by default

### ISSUE THREAD

**Issue by Florianisme** [jellyfin/jellyfin-androidtv#245] opened 2020-01-01 22:49 UTC
When selecting a movie from the collection, the details page is shown with all the information about it. The movies description is focused by default which means that I have to press down and left on my remote everytime to press play and start the movie.

The "Play" or "Resume" button should be focused by default because it makes much more sense than focusing the description.
I can fix this issue by myself and submit a pull request.

**Comment by thornbill** [comment] 2020-01-02 04:28
I’m going to close this issue because it seems like a duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/126.

I was having trouble reproducing this issue on demand the last time I looked at it. I knew I had encountered it before but failed to find the right steps to reproduce it.

If you are able to create a PR with a fix we would happily accept it!

**Closed by thornbill** 2020-01-02 04:28 UTC
