### ISSUE TITLE
Nvidia Shield issue

### ISSUE THREAD

**Issue by tibinet** [jellyfin/jellyfin-androidtv#2604] opened 2023-03-22 06:34 UTC
### Describe the bug

Hello,

on my MacBook Pro, I had installed Jellyfin and using the folder view (which is the most convenient way for me). On the Nvidia Shield, I had the same folder view. 
Now I have bought a new MacBook Pro, installed the Jellyfin, set the folder view, which works. However, on the Nvidia Shield, I have all movies from all folders in one group (instead of structured).
Is that possible, that I was using an older version of Jellyfin on my previous MacBook Pro, and now I have a newer one, which does not support the folder view on the Nvidia Shield?

Thank you in advance for your help.

### Application version

0.15.5

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield 2017

### Android version

Android 9.1

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment] 2023-03-22 07:53
The folder view was removed about 2 years ago because it didn't work properly and fixing it was not trivial. Closing as duplicate of #700.

**Closed by nielsvanvelzen** 2023-03-22 07:53 UTC
Labels: bug
