### ISSUE TITLE
Shuffle and playlist management on videoclip playback (parity with music playback fonctionality)

### ISSUE THREAD

**Issue by waps11** [jellyfin/jellyfin-androidtv#1782] opened 2022-06-16 11:49 UTC
### Describe the feature you'd like

Music playing as nice functionality as playlist management, shuffling and instant mix but these are sadly not available while playing videoclips. For UI consistency these functionality should be on par IMO.

**Comment by BotBlake** [comment] 2024-12-28 20:39
Duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/159
`Shuffle Play for music Videos`

**Closed by BotBlake** 2024-12-28 20:39 UTC
Labels: duplicate, enhancement
