### ISSUE TITLE
[Feature Request] Language selection for audio and subtitles

### ISSUE THREAD

**Issue by Obegg** [jellyfin/jellyfin-androidtv#3339] opened 2024-01-31 18:38 UTC
### Describe the feature you'd like

A feature that will add the option to set language for audio and subtitles, since currently the only way to adjust such feature is using web access, it isn't available on the android tv version.

**Comment by nielsvanvelzen** [comment] 2024-01-31 20:55
I'm not sure what you're asking for, you can already change the subtitle and audio tracks in the video player.

**Comment by tannisroot** [comment] 2024-02-01 23:28
Yes, I have some media files that have multiple tracks and Jellyfin always uses the default track instead of my preferred language for the profile. It respects the default in the web player but not on Android TV, and I have no control over it on the latter.

**Comment by tannisroot** [comment] 2024-02-01 23:34
Even if it respected the preferred language I set up in the web version or in the Android app (it doed not, which seems more like a bug TBH), some folks may only have Jellyfin on their Android TV, and they essentially have no way of changing  it on their TV.

**Comment by tannisroot** [comment] 2024-02-01 23:38
> I'm not sure what you're asking for, you can already change the subtitle and audio tracks in the video player.

It is very tedious to change audio language to the one you actually understand for each episode in a series when a new one begins when it can just always default to the one you prefer.

**Comment by dweremeichik** [comment] 2024-12-23 00:36
Duplicate of #2289

**Closed** 2024-12-23 16:14 UTC
Labels: duplicate, enhancement
