### ISSUE TITLE
Regular crash while playing Video

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-androidtv#606] opened 2020-10-25 17:04 UTC
**Describe the bug**
The application crashes after playing a specific video.

**To Reproduce**
Launch a video

**Expected behavior**
Whole android TV App crashes every 4 or 5 minutes while playing a specific video.
Here the info from jellyfin server

**Logs**
I don't know how to get logs from Android TV I just have logs from Jellyfin server
![image](https://user-images.githubusercontent.com/8579/97113541-630f3a00-16eb-11eb-9b63-c25761257255.png)
[jellyfin.log](https://github.com/jellyfin/jellyfin-androidtv/files/5435436/jellyfin.log)

**System (please complete the following information):**
 - Android TV or Fire TV version: Android TV from Freebox Pop
 - Device manufacturer: ISP Free (site freebox.fr)
 - Device model: Freebox Pop
 - Jellyfin server version: 10.6.4

**Additional context**

**Comment by overlordt** [comment] 2020-11-12 21:01
This also happens on my Nvidia Shield with Jellyfin version 0.11.4. 
Playback starts stuttering and finally crashes (stops) after a few minutes.

**Comment by TheLonelinessOfHS** [comment] 2020-12-05 21:58
Same issue here please fix. Thanks.

**Comment by smidley** [comment] 2021-01-04 21:42
Also experiencing this same issue if the playback is from a remote client.  Makes media playback impossible.

**Comment by douglasg14b** [comment] 2021-06-07 00:25
Same issue a @overlordt .

Playback will be stuttery on Android TV (2019 Shield Pro) app, and then it will just crash back to the Jellyfin home. Regardless of what is being played or if it's being transcoded or played natively. I can play anything just fine on other devices like a Roku, phones, and computers (web).

**Comment by mzramna** [comment] 2021-06-24 22:25
same issue here,it cannot play 2 episodes of a serie in a row without suddenly close the android app into phone

**Comment by arlion-dev** [comment] 2021-07-06 00:17
same issue for me...

**Comment by markmutai** [comment] 2021-07-31 07:12
Ive tried it on mutiple devices, it can go on nicely playing videos, but suddenly crashes. Cant tell any pattern to it, nor a file causing issue

**Comment by bmillemathias** [comment] 2021-07-31 07:16
I've tested the version beta 0.12 and it regularly crashes (around every 5 minutes).

**Comment by nielsvanvelzen** [comment] 2021-10-14 12:17
Closing this issue as duplicate of #1061. See my comment (https://github.com/jellyfin/jellyfin-androidtv/issues/1061#issuecomment-939736611) for some additional information.

Let me know if this issue is different (not a crash during/before/after playback) so I can re-open it.

**Closed by nielsvanvelzen** 2021-10-14 12:17 UTC
Labels: bug, playback
