### ISSUE TITLE
Amazon app store cannot install on Fire TV devices

### ISSUE THREAD

**Issue by The-Randalorian** [jellyfin/jellyfin-androidtv#2387] opened 2023-01-06 14:06 UTC
### Describe the bug

When attempting to install the latest version of the Jellyfin for Fire TV app, Amazon reports the app as unavailable for my device. When viewing the app page through my browser, it reports it can only be installed to my fire tablet. I wonder if the wrong check boxes were checked on supported devices? To my knowledge, Fire OS 7 is the latest version, so I don't think it's a version issue.

### Application version

0.15.0

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Cube 1

### Android version

Fire OS 7.6.1.4

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment] 2023-01-06 14:18
Duplicate of #2377

**Closed by nielsvanvelzen** 2023-01-06 14:18 UTC
Labels: bug
