### ISSUE TITLE
"Next episode" widget starts at the wrong episode when season contains multi-part episodes

### ISSUE THREAD

**Issue by Znuff** [jellyfin/jellyfin-androidtv#3600] opened 2024-05-21 21:45 UTC
### Describe the bug

If you are currently watching a season of a TV Show that contains multi-part episode(s), the "Next Episode" widget will show the wrong episode as being next.

For example, I'm currently watching Stargate Universe, Season 1

The first episode/file is S01E01E02E03 (all 3 episodes).

If I just finished Episode 6, the Widget will show me Episode 9 as being next.

![screen](https://github.com/jellyfin/jellyfin-androidtv/assets/496793/8713d1a8-3610-43a7-8e0b-7e2a3bd5a726)

![screen2](https://github.com/jellyfin/jellyfin-androidtv/assets/496793/ae8c25ef-5e92-4f23-a5e6-298f51d2fd2f)

_Not a new occurence, same issue was present on Jellyfin 10.8.x server_

### Logs

Not applicable.

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

Philips UHD Android TV

### Android version

Android TV OS 11

### Jellyfin server version

10.9.2

**Comment by fice-t** [comment] 2024-06-05 23:07
Duplicate of #1297.

**Closed** 2024-06-06 06:03 UTC
Labels: bug
