### ISSUE TITLE
java.lang.IllegalStateException: FragmentManager is already executing transactions Jellyfin for Android TV

### ISSUE THREAD

**Issue by Kein90** [jellyfin/jellyfin-androidtv#4121] opened 2024-10-30 10:17 UTC
### Describe the bug

java.lang.IllegalStateException: FragmentManager is already executing transactions error when navigating between fragments in Jellyfin Android TV app. This happens consistently when using the mouse scroll wheel to view menu items in the app but also in other conditions as seen in the logs below. 

I know I'm using a Chinese full android box to display a App specifically designated for Android TV, but the software on this things was designed to work with the TV apps and up till now really didn't had any issues. 

I cleared the cache the app data, reinstalled, tried both the local IP and my domain, but as far as the error cant state, it's not related to the server. 

I quite like the Jellyfin for Android TV app and would still like to use it if possible - any help would be greatly appreciated. 
Cheers!

### Logs

[Log 6.txt](https://github.com/user-attachments/files/17570256/Log.6.txt)
[Log 1.txt](https://github.com/user-attachments/files/17570257/Log.1.txt)
[Log 2.txt](https://github.com/user-attachments/files/17570258/Log.2.txt)
[Log 3.txt](https://github.com/user-attachments/files/17570259/Log.3.txt)
[Log 4.txt](https://github.com/user-attachments/files/17570261/Log.4.txt)
[Log 5.txt](https://github.com/user-attachments/files/17570262/Log.5.txt)

### FFmpeg logs

```shell
No relevant information available related to this issue
```

### Media info of the file

```shell
The error happens mostly in the main menu.
```

### Application version

0.17.8

### Device information

GS-King_X_AT 

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment] 2024-11-01 21:26
Closing as duplicate of #4099. Also, we don't support Jellyfin 10.8 😉

**Closed by nielsvanvelzen** 2024-11-01 21:26 UTC
Labels: bug, playback
