### ISSUE TITLE
Specials Show Up Under "#" in "By Letter" view

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-androidtv#2425] opened 2023-01-16 22:54 UTC
### Describe the bug

1. Go to a library with TV shows in the AndroidTV App
2. Go to the bottom and choose "By Letter"
3. Note the "#" row which includes a huge list of specials

A large number of specials appear in this list.  Reviewing the specific special, there appears to be nothing special about the metadata which would have it appear here.  A couple have numbers in the title (ie: "A Look at Season 2") but many don't.

Moreover, if enabled "missing" and "future" specials also appear in this list of "by letter".

Note that these shouldn't show at all.  There is no 'by letter' view in the WebUI or iPhone app, so I am pointing to an AndroidTV issue, but of course it could be with the main Jellyfin server if it's returning something it shouldn't.

![image](https://user-images.githubusercontent.com/7321259/212776504-031e9b05-05ba-4f7e-b192-d0298120d65a.png)
![image](https://user-images.githubusercontent.com/7321259/212776513-3cbc8819-140d-43a6-b19a-c53dbeb41a2f.png)

### Application version

0.15.2

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick 4K Max

### Android version

FireOS 7

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment] 2023-01-17 07:44
Duplicate of #2403

**Closed by nielsvanvelzen** 2023-01-17 07:44 UTC
Labels: bug

**Comment by michaelkrieger** [comment] 2023-01-17 14:20
Sorry about that. Didn’t catch the duplicate.

I’m not sure why it’s not planned, as it’s clearly a bug. Will follow the other bug though

**Comment by nielsvanvelzen** [comment] 2023-01-17 14:27
"not planned" is the status we use for duplicate issues, the other issue is still open.

**Comment by tukilo** [comment] 2023-03-01 15:07
As I understand it, does the # symbol represent any numerical content in the list?

I'm not 100% sure but in the class  "**ByLetterFragment**" line 15 it seems that it doesn't add the filter "**includeItemTypes**" in the query. When I do it returns only content that is numeric.

https://github.com/jellyfin/jellyfin-androidtv/blob/ca37eafb3dc93623fd72abe9e0d2c089c7d51d48/app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt#L15

`includeType?.let { includeItemTypes = arrayOf(it) }`

Could this solve the issue or am I missing something else/breaking something else? @nielsvanvelzen

**Comment by michaelkrieger** [comment] 2023-03-03 18:41
Looks to be fixed by #2556 in case anyone comes across this.
