### ISSUE TITLE
Shows List Truncates when toggling "do not displayed watched" if not all shows have been previously viewed

### ISSUE THREAD

**Issue by KarmaPoliceT2** [jellyfin/jellyfin-androidtv#2540] opened 2023-02-26 03:51 UTC
### Describe the bug

1. Open Shows List
2. Toggle the "do not display watched content" checkmark icon in the top right
3. Observe that not all shows are displayed/scrollable in the list

Observations:
- You will only be able to see the shows which you had previously "seen" prior to toggling the checkmark icon
- If you scroll through your entire list of shows THEN click the icon, you'll see everything displayed and filtered correctly
- But if you have more than a single page of shows content, you'll only see the checkmark take effect (filter out the watched stuff) on the shows that you have previously scrolled down through (if you haven't reached the bottom, you'll never see those shows, even those unwatched, after the checkmark is toggled on)

### Logs

There is no crash log for this

### Application version

0.15.3

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

Latest

### Jellyfin server version

10.8.9.0

**Comment by nielsvanvelzen** [comment] 2023-02-26 15:37
Duplicate of #2470, Fixed by #2472.

**Closed by nielsvanvelzen** 2023-02-26 15:37 UTC
Labels: bug
