### ISSUE TITLE
[Bug] Not showing Latest TV Shows

### ISSUE THREAD

**Issue by emnaudin** [jellyfin/jellyfin-androidtv#125] opened 2019-07-20 12:48 UTC
Using this on an Nvidia Shield, I've noticed that the home screen shows only Latest Movies and Next Up Shows Only, is there a way to show the Latest TV Shows or is it a bug?

Device: Nvidia Shield, jellyfin version 0.9

Thanks

**Comment by thornbill** [comment] 2019-07-20 13:46
Thanks for the feedback! This is a known issue on Android TV. 

Closing as a duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/81

**Closed by thornbill** 2019-07-20 13:46 UTC
