### ISSUE TITLE
"Next Episode" broken after a combined episode in a season.

### ISSUE THREAD

**Issue by mfsiii** [jellyfin/jellyfin-androidtv#2011] opened 2022-08-25 18:12 UTC
### Describe the bug

If there is an episode that is combined (Lost-s6e1-e2) all of the following "Next Episode" entries are off by one for that season. So if I click on Episode 5, and I go to "Next Episode" it will display Episode 7 and onward instead of Episode 6 and onward. The "Next Episode" entries are all fine for seasons without combined episodes, or have combined episodes at the end of a season. This is also cumulative. The more combined episodes there are, the more the "Next Episode" entries are off.

### Application version

0.14.2

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield

### Android version

Android 9

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment] 2022-08-25 20:04
Duplicate of #1297

**Closed by nielsvanvelzen** 2022-08-25 20:04 UTC
Labels: bug
