### ISSUE TITLE
Support for system media events

### ISSUE THREAD

**Issue by DJPlaya** [jellyfin/jellyfin-androidtv#1624] opened 2022-04-15 17:53 UTC
### Describe the bug

Hello, 
The play/pause button I have assigned my remote dosent seem to work in the Jellyfin App. 
To be precise, the button I am talking about is:
http://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_MEDIA_PLAY_PAUSE
Other apps like Kodi or Spotify work fine with it, and I haven't seen an setting regarding that.

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

 Xiaomi MiTV 4s 

### Android version

9 (build: Machu a-user 9 PI 4633 release-keys)

### Jellyfin server version

10.7.7, 10.8.1

**Comment by nielsvanvelzen** [comment] 2022-04-15 17:57
The app does not support media sessions right now and therefor doesn't respond to media events from the system. It registers it's own key handler for the play / pause keys though so this should work. The media keys on my remotes work as expected.

**Comment by DJPlaya** [comment] 2022-04-16 19:32
Ah, okay.
Then this should propably changed into an feature request if not already existing.

**Comment by DJPlaya** [comment] 2022-08-23 22:31
#Push
.ref > https://features.jellyfin.org/posts/1736

**Comment by nielsvanvelzen** [comment] 2022-08-24 07:46
Duplicate of #441

**Closed by nielsvanvelzen** 2022-08-24 07:46 UTC
Labels: bug
