### ISSUE TITLE
Selected item of library listview on back action from item view

### ISSUE THREAD

**Issue by thomcuddihy** [jellyfin/jellyfin-androidtv#2365] opened 2022-12-26 09:20 UTC
### Describe the bug

On pressing "back" from the item description view, it returns the selected item index to 0 on the library list view. Previously returned with selected item same as the item from the description view (both with and without watching item first).

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield P2571

### Android version

Android 9.1.1

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment] 2022-12-26 10:37
Duplicate of #2363

**Closed by nielsvanvelzen** 2022-12-26 10:37 UTC
Labels: bug
