### ISSUE TITLE
Guide does not sync to current time when returning to guide from live tv playback

### ISSUE THREAD

**Issue by samwathegreat** [jellyfin/jellyfin-androidtv#440] opened 2020-04-18 01:04 UTC
Currently, the guide does not refresh (reload / sync guide data with current time) after stopping live tv playback.  This becomes an issue when enough time elapses that the guide should have moved forward because it will show programs that have ended already as if they are on tv now.  Manually moving the guide forward using the remote's "right" button to advance forward is not a good solution because as you scroll the channels, the guide will keep reverting to the prior value (original time, so it shows programs that are already ended).  The "workaround" is to use the back arrow to return to the jellyfin home screen.  Then you can select "Live tv guide" again and it will refresh/advance to the current time.

**Steps to reproduce**:

- From the guide, tune a live tv channel in jellyfin
- Watch long enough to pass the next :30 or 1:00
- Arrow back once to return to the guide.  Though it will show the correct actual time in the corner, It will still be at the same time (guide data) it was when you originally began viewing the first channel.  Programs that have already ended are shown.
- Attempting to use the right arrow button to advance forward to the appropriate time in the guide timeline works (but is awkward because it often jumps :30 and advanced to the next :00) until you start to arrow up and down through channels.  It will keep reverting back to the previous time.

Completely backing out of the guide back to the home screen of jellyfin, then re-entering the guide re-syncs the guide to the current time and everything works as intended.

**Expected behavior**:  When returning to the guide after having been watching live TV, the guide should automatically "move forward" such that programs that are on NOW are shown on the left rather than programs that are already over.

Recommend having jellyfin automatically sync guide data to the current time if time has advanced to the next half or full hour when exiting live tv by pressing the back button on the remote.

Happy to provide any further details and/or logs needed.

**Comment by samwathegreat** [comment] 2020-04-18 21:01
![20200418_165914](https://user-images.githubusercontent.com/4813336/79671165-4de2ad00-8196-11ea-96e5-edcd66fb7743.jpg)

**Comment by thornbill** [comment] 2020-04-28 17:04
Thanks for the thorough description!

I believe this is a duplicate of #284.

**Closed by thornbill** 2020-04-28 17:04 UTC
